### PR TITLE
lux: Update to version 0.17.2

### PR DESCRIPTION
**Pull request by DoveBoy**
* Add arm64 architecture

* Fix 'autoupdate'

Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
The link for 32bit variant is https://github.com/iawia002/lux/releases/download/v0.17.2/lux_0.17.2_Windows_i386.zip

**Comment by DoveBoy** [comment]
> The link for 32bit variant is [iawia002/lux@`v0.17.2` lux_0.17.2_Windows_i386.zip (download)](https://github.com/iawia002/lux/releases/download/v0.17.2/lux_0.17.2_Windows_i386.zip), please fix it

Fixed

**Pull request merged**
