### PR TITLE
Add Redis 5.0.10

### PR DESCRIPTION
**Pull request by dungvv**
- create new entry for redis 5.0.10 (redis5) as default redis 3.2 of main bucket is out dated
- related to #1525

### CODE REVIEW

**Comment by dungvv** [comment]
#1525

**Comment by pratikpc** [comment]
@dungvv wouldn't checkver.github be a better option?

Check [ISX](https://github.com/ScoopInstaller/Main/blob/master/bucket/isx.json)

**Comment by dungvv** [comment]
> @dungvv wouldn't checkver.github be a better option?
> 
> Check [ISX](https://github.com/ScoopInstaller/Main/blob/master/bucket/isx.json)

Yes you're right. I have updated to use checkver.github and add autoupdate
Please help me review it again

**Review by rasa — APPROVED** [review]

**Pull request merged**
