### PR TITLE
bento4: Add version 1.6.0-640

### LINKED ISSUE #5054: [Request]: bento4
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

bento4

### Description

Full-featured MP4 format, MPEG DASH, HLS, CMAF SDK and tools

### Homepage

https://www.bento4.com

### Download Link(s)

https://www.bento4.com/downloads/

### Some Indication of Popularity/Repute

1.7k stars
https://github.com/axiomatic-systems/Bento4

Bento4 supports a wide range of MP4 files, including MPEG DASH, HLS, and CMAF. CLI tools are often used to package MPEG DASH, HLS and add DRM, etc.

Bento4 is featured on the official DASH-IF website[^1].
It is also used to create DRM-protected MPEG-DASH in Adobe's learning documentation[^2] and JW Player documentation[^3].

[^1]: https://dashif.org/tools/sample/
[^2]: https://experienceleague.adobe.com/docs/primetime/drm/multi-drm-workflows/package-license-play/package-for-widevine-with-bento.html
[^3]: https://docs.jwplayer.com/platform/reference/studio-drm-standalone-bento4

### PR DESCRIPTION
**Pull request by tobigumo**
Adds Bento4 MP4 tool to scoop bucket: Main

Closes #5054

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Excellent manifest @tobigumo! 

Just one small change: the binaries are 64bit, so you'll need to use the architecture field.

**Comment by tobigumo** [comment]
Thank you for your review @rashil2000 !
I have been fixed the problem.
How about this?

**Pull request merged**
