### PR TITLE
shadowsocks-rust: Add version 1.8.11

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Comment by Ash258** [comment]
Move this PR into versions. There is no reason to keep both in extras .

**Comment by linsui** [comment]
This is not in extras. It's a cli application and it icontains a server and a client while shadowsocks-windows is noly a gui client.

**Comment by Ash258** [comment]
I see. Sorry my bad.

The `-rust` suffix is needed?

**Comment by linsui** [comment]
There are some other implementations of the shadowsocks protocol with some different features. Without `-rust` users may feel confused. Also the name `shadowsocks`  is not available.

**Pull request merged**
