### PR TITLE
protobuf: Add Version 3.19.3

### PR DESCRIPTION
**Pull request by JalonWong**
Protocol Buffers - Google's data interchange format

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/blob/master/bucket/protobuf.json

**Comment by JalonWong** [comment]
Hi @rashil2000 . Thanks to your reply.
I would also like to add https://github.com/bazelbuild/buildtools/releases. Where should I add them?

**Comment by rashil2000** [comment]
In the Main bucket. Create a new PR.

**Pull request closed without merging**
