### PR TITLE
LLVM: Update to version 11.0.0

### PR DESCRIPTION
**Pull request by pratikpc**
Remove clang-import-test shim because it is not distributed anymore

### CODE REVIEW

**Comment by chawyehsu** [comment]
Please also fix the checkver

**Comment by pratikpc** [comment]
I would love to help out with the checkver @chawyehsu but I have no idea how to

**Comment by pratikpc** [comment]
@chawyehsu the issue lies with Scoop's parsing of the webpage or maybe with LLVM's webpage

I presume it's down to them not specifying Content-Type in HEAD

Using checkver.ps1 file, and printing $page on the console I saw gibberish, unicode esque gibberish on the screen while the same doesn't occur for 7zip

To face the same issue, add `echo $page` to https://github.com/lukesampson/scoop/blob/731d878490a7bb1aa9d2bf1c15cd27ef2c31c2fb/bin/checkver.ps1#L257

**Comment by batkiz** [comment]
Maybe we could use
```json
"checkver": {
    "url": "https://llvm.org/",
    "regex": "([\\d.]+):"
},
```

to fix the `checkver`, because every release would be listed in the *Release Emails* section on homepage.

I've tried the `checkver` code above and it actually works
```
> cat .\bucket\llvm.json
{
    "version": "10.0.0",
    ...
    "checkver": {
        "url": "https://llvm.org/",
        "regex": "([\\d.]+):"
    },
    ...
}

> .\bin\checkver.ps1  -dir .\bucket\ -app llvm
llvm: 11.0.0 (scoop version is 10.0.0) autoupdate available
```

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
