### PR TITLE
Fix virtualenv creation bug

### PR DESCRIPTION
**Pull request by WqyJh**
See https://github.com/lukesampson/scoop/issues/2383#issuecomment-520114024

### CODE REVIEW

**Comment by hagaigold** [comment]
@WqyJh @h404bi 
should i open new issue ? should you consider this bug fix ?

**Comment by copdips** [comment]
@hagaigold 

I made a test.
No issue when switching between python 3.5 and 3.7.

But after I installed python27 by `scoop install python27`, the python is redirected to python27, but the pip is still the one for python37,

Than I ran `scoop reset python` and `scoop reset python27`, it was OK after that. both (python.exe and pip.exe) are python27.

At last, I swtiched back to python37 by `scoop reset python`, both are python37.

Could you please recheck ?

**Comment by hagaigold** [comment]
@copdips 

in my paths the root directory of python37 is above the shims directory, so it is not working for me.
can you do `where python` after you switch to python35 or python27 ?

**Comment by copdips** [comment]
@hagaigold,

I'm at work, I will give you the output tonight.

Yesterday I tested the version by 'python -V' and 'pip -V' and I also checked the content of 'python.ps1' as 'gcm python' only gives python.ps1, they are all pointed to the correct folders.

**Comment by copdips** [comment]
@hagaigold 

initially, i'm on python37:

```powershell
> python -V ; pip -V
Python 3.7.4
pip 19.0.3 from d:\xiang\tools\scoop\apps\python\3.7.4\lib\site-packages\pip (python 3.7)

> where.exe python
D:\xiang\tools\Scoop\shims\python.exe

> where.exe pip
D:\xiang\tools\Scoop\apps\python\current\Scripts\pip.exe
D:\xiang\tools\Scoop\apps\python27\current\Scripts\pip.exe
D:\xiang\tools\Scoop\apps\python35\current\Scripts\pip.exe
```

then, move to python27:

```powershell
> scoop reset python27
Resetting python27 (2.7.16).
Linking D:\xiang\tools\Scoop\apps\python27\current => D:\xiang\tools\Scoop\apps\python27\2.7.16
Creating shim for 'python'.
WARN  Overwriting shim to python.exe installed from python
Creating shim for 'pythonw'.
WARN  Overwriting shim to pythonw.exe installed from python
Creating shim for 'python2'.
Creating shim for 'idle'.
WARN  Overwriting shim to idle.bat installed from python
Creating shim for 'idle2'.

> where.exe python
D:\xiang\tools\Scoop\shims\python.exe

> where.exe pip
D:\xiang\tools\Scoop\apps\python27\current\Scripts\pip.exe
D:\xiang\tools\Scoop\apps\python\current\Scripts\pip.exe
D:\xiang\tools\Scoop\apps\python35\current\Scripts\pip.exe

> python -V ; pip -V
Python 2.7.16
pip 18.1 from d:\xiang\tools\scoop\apps\python27\current\lib\site-packages\pip (python 2.7)
```

at last, switch back to python37:

```powershell
> scoop reset python
Resetting python (3.7.4).
Linking D:\xiang\tools\Scoop\apps\python\current => D:\xiang\tools\Scoop\apps\python\3.7.4
Creating shim for 'python'.
WARN  Overwriting shim to python.exe installed from python27
Creating shim for 'pythonw'.
WARN  Overwriting shim to pythonw.exe installed from python27
Creating shim for 'python3'.
Creating shim for 'idle'.
WARN  Overwriting shim to idle.bat installed from python27
Creating shim for 'idle3'.

> python -V ; pip -V
Python 3.7.4
pip 19.0.3 from d:\xiang\tools\scoop\apps\python\3.7.4\lib\site-packages\pip (python 3.7)

> where.exe python
D:\xiang\tools\Scoop\shims\python.exe

> where.exe pip
D:\xiang\tools\Scoop\apps\python\current\Scripts\pip.exe
D:\xiang\tools\Scoop\apps\python27\current\Scripts\pip.exe
D:\xiang\tools\Scoop\apps\python35\current\Scripts\pip.exe
```

**Comment by hagaigold** [comment]
> @hagaigold
> 
> initially, i'm on python37:
> 
> ```powershell
> > python -V ; pip -V
> Python 3.7.4
> pip 19.0.3 from d:\xiang\tools\scoop\apps\python\3.7.4\lib\site-packages\pip (python 3.7)
> 
> > where.exe python
> D:\xiang\tools\Scoop\shims\python.exe
> 
> > where.exe pip
> D:\xiang\tools\Scoop\apps\python\current\Scripts\pip.exe
> D:\xiang\tools\Scoop\apps\python27\current\Scripts\pip.exe
> D:\xiang\tools\Scoop\apps\python35\current\Scripts\pip.exe
> ```
> 

you are missing the root directory of python which this commit all about:
```
"env_add_path": [
        "Scripts",
        "."
],
```

I suspect you install python37 before this fix, so the manifest.json is the previous one.
scoop keep the manifest.json together with the installed version.
can you check the value of env_add_path in `scoop\apps\python\3.7.4\manifest.json` ?

**Comment by copdips** [comment]
@hagaigold 

yes, I got it by reinstalling scoop from scratch, and you're right. Something is broken. Better to open a new issue and refer this PR.

**Pull request merged**
