### PR TITLE
Fix OpenSSL Light URL

### PR DESCRIPTION
**Pull request by bluerememberedearth**
Current URL 404s

Updates to latest working URL from https://slproweb.com which is v3.3.2:
https://slproweb.com/download/Win32OpenSSL_Light-3_3_2.exe

### CODE REVIEW

**Comment by bluerememberedearth** [comment]
Please review @sitiom @HUMORCE

**Comment by sitiom** [comment]
> Please review @sitiom @HUMORCE

Unfortunately, I only have access to the https://github.com/ScoopInstaller/Extras repo 😅

**Comment by bluerememberedearth** [comment]
Oh no, maybe @stevehipwell or @shiena are online?

**Pull request merged**
