### PR TITLE
opam: Add version 2.2.1

### PR DESCRIPTION
**Pull request by sharno**
Opam started supporting windows. Adding version 2.2.1

Fixes ScoopInstaller/Extras#14217.

https://github.com/ocaml/opam/releases/tag/2.2.1

### CODE REVIEW

**Review by NoahELE — APPROVED** [review]

**Comment by aliesbelik** [comment]
Please follow the standard order of fields in the json file, as per [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).
Otherwise looks good.

**Comment by aliesbelik** [comment]
Fixes ScoopInstaller/Extras#14217.

**Comment by sharno** [comment]
@aliesbelik rearranged the fields to follow the guide

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
