### PR TITLE
kind: Add version 0.8.1

### PR DESCRIPTION
**Pull request by stevehipwell**
Add `kind` to _Scoop_.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@Ash258 could we get this merged?

**Comment by Ash258** [comment]
Stop tagging me in conversation which I do not want to be part of.

There is like 10 people in this repo who can take it instead of me.

**Comment by stevehipwell** [comment]
I'm sorry #Ash258 you were on the participant list. @rasa do you have a suggestion of who would be able to merge this?

**Comment by rasa** [comment]
Sorry for delay. Been without power these last few days.

**Comment by stevehipwell** [comment]
Thanks @rsa.

**Comment by Ash258** [comment]
@rasa Can you merge the PRs with correct names and name them right next time? 

image

image

**Pull request merged**
