### PR TITLE
Vim: use stable build

### PR DESCRIPTION
**Pull request by linsui**
Close https://github.com/lukesampson/scoop/issues/1871

The vim build on github is nightly build, see https://www.vim.org/download.php

>If you want the most recent improvements, with a small risk that something is broken, you can get the nightly build from
    vim-win32-installer

Scoop changed vim to nightly build in https://github.com/lukesampson/scoop/commit/e5e06d72f4ff2fcdcd604480801662def1e8e5fc for some reasons. 

I add a vim-nightly and change vim back to stable build. Add Edit with Vim context. Persist some config files.

### CODE REVIEW

**Comment by rasa** [comment]
@linsui Can you resolve these conflicts?

**Comment by rasa** [comment]
I’m still seeing a conflict in the GitHub UI:
<details><summary>details</summary>
<pre>
<<<<<<< vim
    "version": "8.1.1",
    "url": [
        "https://ftp.nluug.nl/pub/vim/pc/gvim81.exe#/dl.7z",
        "https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/vim/install-context.reg",
        "https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/vim/uninstall-context.reg"
    ],
    "hash": [
        "md5:14391c74929552db62acc6bca9efbe1b",
        "16a29881837047d783e8556506c73bbb292bdfefe042d77564d3c166d92b9d98",
        "49225d3470bf4b397d3cab865eddca6e47610be356f812588588c2661a11557e"
    ],
    "extract_dir": "$0",
    "pre_install": [
        "Remove-Item \"$dir\\`$*\", \"$dir\\uninstal.*\", \"$dir\\install.exe\" -Recurse",
        "if (!(Test-Path \"$persist_dir\\_vimrc\")) {",
        "    Copy-Item \"$dir\\vimrc_example.vim\" \"$dir\\_vimrc\"",
        "    Copy-Item \"$dir\\gvimrc_example.vim\" \"$dir\\_gvimrc\"",
        "    Add-Content \"$dir\\_vimrc\" \"set shell=$((Get-Command powershell).Path)\\ -ExecutionPolicy\\ Bypass\" -Encoding Ascii",
        "}",
        "'install-context.reg', 'uninstall-context.reg' | ForEach-Object {",
        "    $vimpath = \"$(current_dir $dir)\\gVim.exe\".Replace('\\', '\\\\')",
        "    $content = (Get-Content \"$dir\\$_\").Replace('$vim', $vimpath)",
        "    if ($global) { $content = $content.Replace('HKEY_CURRENT_USER', 'HKEY_LOCAL_MACHINE') }",
        "    Set-Content \"$dir\\$_\" $content",
        "}"
    ],
=======
    "version": "8.2.0008",
    "architecture": {
        "64bit": {
            "url": "https://github.com/vim/vim-win32-installer/releases/download/v8.2.0008/gvim_8.2.0008_x64.zip",
            "hash": "0607b91d2869a75986af504f2cab56b73e58b80a86e30d090d8e5b3ef3ae3434"
        },
        "32bit": {
            "url": "https://github.com/vim/vim-win32-installer/releases/download/v8.2.0008/gvim_8.2.0008_x86.zip",
            "hash": "2c79d0b141568d5d614d432dae333e3c7b0ebe578bac795930af9405310ed548"
        }
    },
    "extract_dir": "vim\\vim82",
</pre>
</details>

**Comment by linsui** [comment]
Since it's a nightly build there will be new conflict every day.

**Comment by matoro** [comment]
Something seems to be broken here in the new 8.2, it is setting `$VIMRUNTIME` to `$HOME\scoop\apps\vim\current\vim82` but all the runtime files such as `defaults.vim` are located one directory up.  Trying to figure out a workaround right now but this is broken even without custom vimrc files.

**Comment by rasa** [comment]
@matoro This may be due to the bump to 8.2, and not due to our splitting vim in stable and nightly versions. I will create a new issue from your comment above. Thanks for the report.

**Comment by i-give-up** [comment]
Some notes regarding the 8.2 stable build:
- seems to only be available in 32-bit. This can be verified by running `:version` or `:echo has("win64")` in vim.
- seems to be compiled with older versions of python and others. This can be verified by running `:version` in vim.

Essentially, this means that this change from nightly build to stable build can cause certain issues like python-based vim plugins stop working when user upgrades vim via scoop. This happened to me and I was wondering if there's something wrong with my python installation before eventually finding out about this change.

**Pull request merged**
