### PR TITLE
clink: Change to chrisant996/clink version

### PR DESCRIPTION
**Pull request by Slach**
fix https://github.com/chrisant996/clink/issues/24

### CODE REVIEW

**Comment by Slach** [comment]
@chawyehsu could you look at this pull request?
sorry, I don't familiar with scoop main bucket review workflow, will be appreciated for suggestions

**Comment by chawyehsu** [comment]
Is there any official statement for the fork to be a suggest maintained version?

**Comment by Slach** [comment]
@chawyehsu please look to https://github.com/mridgers/clink/issues/546
and https://github.com/mridgers/clink/network
image

@chrisant996 fork is a most actively developed fork with every many useful commits

unfortunately, @mridgers, don't answer me in private so long time
and maybe @chrisant996 can have official answers from @mridgers

**Comment by chrisant996** [comment]
mridgers has been absent for a few years.

I have forked the repo and have made hundreds of fixes and enhancements.  The fork has a stable pre-release build, and is nearing an official release.

I can officially say I will be maintaining and enhancing this fork.  It's not the original repo, but with mridgers' extended absence there's no way to move the original repo forward; it was necessary to fork it.

Does that answer the question?

**Comment by Slach** [comment]
@chawyehsu are you satisfied with the answer? could you look this PR again?

**Review by chawyehsu — APPROVED** [review]

**Comment by Slach** [comment]
@chawyehsu which next steps in workflow? what else need for merge this PR?

**Comment by Slach** [comment]
> This commit does not belong to any branch on this repository?

@rasa this commit just outside main repository, and belongs to this pull request

**Pull request merged**
