### PR TITLE
qemu: Fix decompress error

### LINKED ISSUE #4164: [Bug]: QEMU 7.2.0-rc2 unable to extract qemu-uninstall.exe.nsis
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

QEMU

### Expected/Current Behaviour

Expected behaviour is to successfully install/update qemu.
Current behaviour is that 7z is unable to extract lib\gdk-pixbuf-2.0\2.10.0\qemu-uninstall.exe.nsis from the archive during the installation process.
[7zip.log](https://github.com/ScoopInstaller/Main/files/10082934/7zip.log)

### Steps to Reproduce

```console
PS> scoop install qemu -k
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'qemu' (7.2.0-rc2) [64bit] from main bucket
WARN  Cache is being ignored.
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 27e395|OK  |   6.9MiB/s|C:/Tools/Scoop/cache/qemu#7.2.0-rc2#https_qemu.weilnetz.de_w64_qemu-w64-setup-20221123.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of qemu-w64-setup-20221123.exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Tools\Scoop\apps\qemu\7.2.0-rc2\dl.7z.
Log file:
  C:\Tools\Scoop\apps\qemu\7.2.0-rc2\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=qemu%407.2.0-rc2%3a+decompress+error
```

### Possible Solution

While I don't have a solution, I did note that the same error occurs in the GUI version of 7-zip 22.01 if you try to manually extract the executable. The file that causes the error may be related to this change in the history notes for the new version:
2022-11-23: New QEMU installers (7.2.0-rc2). Signed uninstaller, enhanced file properties.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
ca9395116 (HEAD -> master, origin/master, origin/HEAD) winscan2pdf: Update to version 8.31

'java' bucket:
6ca994b1 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.362-3.0.202211231817

'main' bucket:
a9e99dd18 (HEAD -> master, origin/master, origin/HEAD) git-istage: Update to version 0.3.88

'nirsoft' bucket:
28db834 (HEAD -> master, origin/master, origin/HEAD) Excluded two pad files that require a password. They need to be updated manually.
```

### Scoop Config

```console
PS> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2022-11-24T08:33:58.7296808+00:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by brian6932**
Closes #4164 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Has this been tested with a clean (new) installation?

**Comment by brian6932** [comment]
yesz

**Pull request merged**
