### PR TITLE
pdfbox: Add version 2.0.23

### PR DESCRIPTION
**Pull request by digrouz**

### CODE REVIEW

**Comment by digrouz** [comment]
I took those hashes from:
* https://downloads.apache.org/pdfbox/2.0.23/preflight-2.0.23.jar.sha512
* https://downloads.apache.org/pdfbox/2.0.23/preflight-2.0.23.jar.sha512

So i'm wondering how they can fail ^^

**Comment by digrouz** [comment]
should be good now.

I added autoupdate too, what do you think ?

**Comment by CryoRenegade** [comment]
You forgot to add a newline to the end of the file.

**Comment by digrouz** [comment]
done :)

**Comment by CryoRenegade** [comment]
Now it is complaining about an array being a string?

**Comment by digrouz** [comment]
strange, I can install it without any issue.

**Comment by digrouz** [comment]
is it possible that it's because autoupdate don't support multiple urls ?

**Comment by CryoRenegade** [comment]
idk

**Comment by digrouz** [comment]
let's try to remove the autoupdate

**Comment by digrouz** [comment]
seems like it

**Comment by digrouz** [comment]
is there still something preventing the merge ?

**Comment by digrouz** [comment]
is there still something preventing the merge of this PR ?

**Comment by sualeh** [comment]
@digrouz  - is this a dupe of #2167?

**Comment by digrouz** [comment]
> @digrouz - is this a dupe of #2167?

yes :)

I don't know what to do to make it merge :(

**Comment by sualeh** [comment]
@digrouz - make your own bucket, or run from the Scoop file locally, since this issue is not getting merged to the Main bucket.

**Comment by digrouz** [comment]
@sualeh I know but still, I would like to understand what prevent it to be merged. @CryoRenegade any hint ?

**Comment by CryoRenegade** [comment]
Looks like a maintainer needs to review and merge the pr

**Comment by akirayamamoto** [comment]
Pushed to 2.0.24.

**Review by akirayamamoto — APPROVED** [review]
Pushed to 2.0.24.

**Pull request merged**
