### PR TITLE
Update rethinkdb.json to rethinkdb-2.4.3

### PR DESCRIPTION
**Pull request by srh**
Relates to #2848, which linked to https://github.com/rethinkdb/rethinkdb/issues/6814

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Please add checkver and autoupdate too, so that the manifest can be updated automatically. 

(Ref: https://github.com/ScoopInstaller/Main/commit/cf09bd93827222468fb9cc5b02bb50adf5ba4240)

**Comment by srh** [comment]
Sorry for the slowness.  RethinkDB's website update hooks weren't working so I was putting off the fix until that got working.

**Comment by rashil2000** [comment]
No worries :)

**Pull request merged**
