### PR TITLE
neovim: Update to version 0.3.5

### PR DESCRIPTION
**Pull request by h404bi**

### CODE REVIEW

**Comment by Ash258** [comment]
Manual update? 
New release process with `stable` release name will be permanent? If so, should not checkver reflect this change?

**Comment by h404bi** [comment]
They made a special `stable` tag for `v0.3.5`, it breaks autoupdate and I don't know whether they would use semver for the next release.

**Comment by niheaven** [comment]
It seems like they have `v0.3.5` tag, but only for source code.

`checkver` should changed also, likes this:

```json
"checkver": {
    "github": "https://github.com/neovim/neovim",
    "regex": "Release NVIM [\\d.]+"
},
```

**Comment by r15ch13** [comment]
https://github.com/lukesampson/scoop/issues/3464

**Comment by xarthurx** [comment]
@niheaven they also have a binary package now.
https://github.com/neovim/neovim/releases

**Comment by niheaven** [comment]
@xarthurx I mean `tag`, i.e. https://github.com/neovim/neovim/releases/tag/v0.3.5, under `0.3.5` there is no binary.

**Comment by xarthurx** [comment]
@niheaven asked here:https://github.com/neovim/neovim/issues/10011

**Comment by xarthurx** [comment]
Is this PR going to be approved sometime?

**Comment by niheaven** [comment]
https://github.com/neovim/neovim/tree/stable

> The stable tag is an alias to the current release tag.

**Comment by xarthurx** [comment]
It seems the hash has some problems:

```
Checking hash of nvim-win64.zip ... ERROR Hash check failed!
App:         main/neovim
URL:         https://github.com/neovim/neovim/releases/download/v0.3.5/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    ecde1d19b7045d785aede4e2f710ac66b987e775676d7c9d537238495eb534b1
Actual:      9ae6d74d19c30a8a23a84c378318c5ecd754d7cce340b5696596485a2e3740e7

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=neovim%400.3.5%3a+hash+check+failed
```

**Comment by xarthurx** [comment]
They also have a binary under tag `v0.3.5` now. So the original script should work I guess.

**Pull request closed without merging**
