### PR TITLE
rye: Add version 0.8.0

### PR DESCRIPTION
**Pull request by sitiom**
An Experimental Package Management Solution for Python

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by joe733** [comment]
[`rye 0.5.0`](https://github.com/mitsuhiko/rye/releases) was released.

**Comment by sitiom** [comment]
> [`rye 0.5.0`](https://github.com/mitsuhiko/rye/releases) was released.

Updated.

**Comment by joe733** [comment]
[`rye 0.8.0`](https://github.com/mitsuhiko/rye/releases) was released.

**Pull request merged**
