### PR TITLE
postgrest: install required DLLs

### LINKED ISSUE #5959: [Bug]: `postgrest` fails to start because of missing DLLs required
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

postgrest

### Expected/Current Behaviour

Expected:

a console window would blink

Instead:

`postgrest.exe` doesn't start, citing the absence of `LIBPQ.DLL` in a message box, see screenshot below 
VirtualBox_win10test_27_06_2024_15_46_23

### Steps to Reproduce

```console
0. Install Windows (e.g. Win10 LTSC 2021 evaluation), install chocolatey
1. `scoop install postgrest`, then open `scoop/shims` in Explorer
2. double-click postgrest.exe
```

### Possible Solution

Ship `{libcrypto-3-x64,libiconv-2,libintl-9,libssl-3-x64,libwinpthread-1,libpq}.dll` (as per https://github.com/PostgREST/postgrest/pull/3469/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR202) along with the `postgrest.exe`

### Scoop and Buckets Version

```console
PS C:\Users\vboxuser> scoop --version
Current Scoop version:
v0.4.2 - Released at 2024-05-14
```

### Scoop Config

```console
PS C:\Users\vboxuser> scoop config

last_update
-----------
2024-06-27T15:40:59.6824199+02:00
```

### PowerShell Version

```console
PS C:\Users\vboxuser> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

_No response_

UPD: sister issue for `chocolatey` — https://github.com/majkinetor/au-packages/issues/245

In before "why PostgREST does not ship them along with the executable" — https://github.com/PostgREST/postgrest/pull/3469. TL;DR: it's not out job; we don't know where to get them canonically; EnterpriseDB (first obvious source of them) license doesn't allow to redistribute them.

### PR DESCRIPTION
**Pull request by develop7**
Downloads DLLs postgrest.exe is linked against making postgrest work out of the box

Closes #5959 (see screenshot below) 

VirtualBox_win10test_27_09_2024_16_16_23

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by develop7** [comment]
> Create a separate manifest for psqlodbc instead.

@HUMORCE how should it look like to have #5959 go away? could you suggest some key points, or, better yet, give an example of a similar manifest?

**Comment by HUMORCE** [comment]
I mean creates `psqlodbc` as separate manifest as dependency for similar situation like this manifest.

**Comment by HUMORCE** [comment]
I created that: https://github.com/ScoopInstaller/Main/commit/081d2179531427f8ac70763f36316d664ac91f4f

**Comment by develop7** [comment]
> I created that: [081d217](https://github.com/ScoopInstaller/Main/commit/081d2179531427f8ac70763f36316d664ac91f4f)

@HUMORCE thank you for going forward and creating the needed app, but depending on the it doesn't help — `postgrest.exe` doesn't start quoting the lack of LIBPQ.DLL (see the screenshot below)
VirtualBox_win10test_27_09_2024_16_09_58

**Comment by develop7** [comment]
UPD: Added the screenshot with the #5959 fixed

**Comment by HUMORCE** [comment]
I forgot to add it to the PATH, fixed: https://github.com/ScoopInstaller/Main/commit/7bb9cffbef818a4b11781bc9d98a4f34e167ce70

Please test it again.

```
❯ scoop install psqlodbc postgrest
Installing 'psqlodbc' (17.00.0000) [64bit] from 'main' bucket
Loading psqlodbc_x64.msi from cache
Checking hash of psqlodbc_x64.msi ... ok.
Extracting psqlodbc_x64.msi ... done.
Linking ~\scoop\apps\psqlodbc\current => ~\scoop\apps\psqlodbc\17.00.0000
Adding ~\scoop\apps\psqlodbc\current\bin to your path.
'psqlodbc' (17.00.0000) was installed successfully!
Installing 'postgrest' (12.2.3) [64bit] from 'main' bucket
Loading postgrest-v12.2.3-windows-x64.zip from cache
Checking hash of postgrest-v12.2.3-windows-x64.zip ... ok.
Extracting postgrest-v12.2.3-windows-x64.zip ... done.
Linking ~\scoop\apps\postgrest\current => ~\scoop\apps\postgrest\12.2.3
Creating shim for 'postgrest'.
'postgrest' (12.2.3) was installed successfully!
'postgrest' suggests installing 'postgresql'.
~
❯ postgrest
27/Sep/2024:18:38:35 +0000: Starting PostgREST 12.2.3 (519615d)...
27/Sep/2024:18:38:35 +0000: Listening on port 3000
...
```

**Comment by develop7** [comment]
@HUMORCE works for me too, thank you!

**Pull request merged**
