### PR TITLE
Add tectonic to bucket

### PR DESCRIPTION
**Pull request by CryoRenegade**
Added Tectonic, a self contained latex compiler

### CODE REVIEW

**Comment by CryoRenegade** [comment]
And this is where I would ask for help.
So could I have some help in resolving the checkver and autoupdate?

**Comment by rashil2000** [comment]
Try this:
```json
"checkver": {
        "url": "https://github.com/tectonic-typesetting/tectonic/releases",
        "regex": "releases/tag/tectonic%40([\\d.]+)"
},
```

**Pull request merged**
