### PR TITLE
Add mingw

### PR DESCRIPTION
**Pull request by rashil2000**
Relates to https://github.com/ScoopInstaller/Main/issues/2933#issuecomment-971566422

### CODE REVIEW

**Comment by niheaven** [comment]
Then who will be the GCC?

**Comment by rashil2000** [comment]
There's no standalone GCC, as you said in your comment in the other PR.

**Comment by niheaven** [comment]
Yes, what I mean is, if user want GCC or only know GCC, should we provide a distro of GCC that fits user's need?

An alias or group selection may be better, but there isn't such feature. So I prefer left current one as GCC and change its name after the feature is added.

**Comment by rashil2000** [comment]
Okay, I renamed mingw.json to gcc.json, and added a note 👍

**Comment by niheaven** [comment]
I don't think such an outdated distro should be the default. But since I'm not target user of GCC, please wait other maintainers' feedback.

The one last thing I concerned is, please place build vendor behind app name, e.g., mingw-winlibs.

**Comment by rashil2000** [comment]
> I don't think such an outdated distro should be the default.

It is the official source of mingw-w64, what other option do we have? Others are all third party (including MSYS2).

**Comment by niheaven** [comment]
Don't confuse MinGW-w64 and GCC. MinGW-w64 is NOT GCC, it is just a C library that make GCC usable in Windows. Other distro use GCC from FSF and MinGW-w64 as underground C library.

**Comment by rashil2000** [comment]
Yes, I'm not saying they are the same thing. But there's no GCC without MinGW-w64 (on Windows).

**Comment by niheaven** [comment]
People is using GCC, not MinGW, so make GCC updated. `8.2.0` is far more outdated. (MinGW 9.0.0 is latest version, though)

**Comment by rashil2000** [comment]
There's no official source for GCC that we can use in the manifest (the gcc.gnu.org website does not provide binaries).

The runtime library that's used to compile GCC is made by mingw-w64.org, and they provide binaries, so I used that in the manifest.

**Comment by issaclin32** [comment]
I vote up for this solution. In regards to [Chawye's comment](https://github.com/ScoopInstaller/Main/pull/2967#issuecomment-971458707).

If the end-user **naively** installs *gcc* and compiles something with *gcc*, the MinGW-w64 is less likely to cause problems. However, we should **explicitly** point out that there are newer versions available in `notes`.

Such as:
```
You are installing the Mingw-w64 implementation of GCC (version 8).
This implementation has a better compatibility, but may not support newer C/C++ standards.
For GCC version 11, install 'mingw-winlibs.json'
```

**Review by issaclin32 — APPROVED** [review]

**Comment by tech189** [comment]
@rashil2000 - mingw-winlibs checkver is broken, regex101 says it detects catastrophic backtracking but I couldn't work out what you were trying to match, could you fix it please?

**Comment by rashil2000** [comment]
The URLs will need to be updated. checkver can be:
```
GCC ([\\d.]+) \\+ MinGW-w64 ([\\d.]+) \\(MSVCRT\\) - release ([\\d.]+)
```

**Comment by issaclin32** [comment]
> @rashil2000 - mingw-winlibs checkver is broken, regex101 says it detects catastrophic backtracking but I couldn't work out what you were trying to match, could you fix it please?

Fixed in https://github.com/ScoopInstaller/Main/commit/af540077b0dad8734983e977e5847c20d0bf156e

**Pull request merged**
