### PR TITLE
vcpkg: Add version 2022.05.10

### LINKED ISSUE #3633: [Request] Add vcpkg
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** vcpkg

**Description:** C/C++ dependency manager from Microsoft For all platforms, buildsystems, and workflows

**Homepage:** https://vcpkg.io/

**Download link(s):** https://github.com/microsoft/vcpkg-tool/releases/download/2022-05-05/vcpkg.exe

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

### PR DESCRIPTION
**Pull request by BennyDioxide**
* Closes #3633

* Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
There is a standalone version of `vcpkg.exe`. Should we use this one instead?
https://github.com/microsoft/vcpkg-tool/releases/tag/2022-05-05

**Comment by rashil2000** [comment]
It's possible the bootstrap script might be doing some additional setup apart from generating the binary

**Comment by UpChkLib** [comment]
> ~There is a standalone version of `vcpkg.exe`. Should we use this one instead?~ See comment below. https://github.com/microsoft/vcpkg-tool/releases/tag/2022-05-05

I know but I am worry about the docs inside the vcpkg directory so I add it back

**Comment by UpChkLib** [comment]
> It's possible the bootstrap script might be doing some additional setup apart from generating the binary

thanks!

**Comment by UpChkLib** [comment]
And this is wierd.
On the github page it says it's ver 2022.05.10 but running `vcpkg --version` returns
`vcpkg package management program version 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8`.

**Comment by UpChkLib** [comment]
> 

Yeah this is better than mine because it's the first time I contribute this project.

**Comment by UpChkLib** [comment]
Sorry noob for git and github

**Comment by rashil2000** [comment]
We should avoid making the install process interactive, as many times the installation is run in CI/automated environments. We can just do this:
```json
    "installer": {
        "file": "bootstrap-vcpkg.bat",
        "keep": true
    },
```

**Comment by BennyDioxide** [comment]
> We should avoid making the install process interactive, as many times the installation is run in CI/automated environments. We can just do this:
> 
> ```json
>     "installer": {
>         "file": "bootstrap-vcpkg.bat",
>         "keep": true
>     },
> ```

Ok, but I just stuck at disabling telementry

**Comment by rashil2000** [comment]
Don't disable it, the defaults are okay

**Comment by rashil2000** [comment]
You need to put extract_dir in autoupdate too

**Pull request merged**
