### PR TITLE
nexttrace: Add version 0.2.3

### LINKED ISSUE #4089: [Request] Nexttrace
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:**  nexttrace

**Description:**  An open source visual route tracking CLI tool

**Homepage:** https://github.com/sjlleo/nexttrace

**Download link(s):** https://github.com/sjlleo/nexttrace/releases

**Some indication of popularity/repute:** 532 stars

### PR DESCRIPTION
**Pull request by soenggam**
Closes #4089 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Hi, thanks for the PR!

Although this project satisfies the stars criteria, it's still very new (less than 6 months old) for the Main bucket. 

Could you raise this PR in the Extras bucket instead?

Thanks.

**Comment by soenggam** [comment]
> Hi, thanks for the PR!
> 
> Although this project satisfies the stars criteria, it's still very new (less than 6 months old) for the Main bucket.
> 
> Could you raise this PR in the Extras bucket instead?
> 
> Thanks.

done, check https://github.com/ScoopInstaller/Extras/pull/9653

**Pull request closed without merging**
