### PR TITLE
r: Added post_install script so r-studio can recognize it.

### PR DESCRIPTION
**Pull request by Zliced13**
Closes https://github.com/ScoopInstaller/Extras/issues/10533

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Why did you move bin and shortcuts outside the architecture block?

Also, I do not advocate modifying registry in the manifest. It should be optional.

/cc @niheaven

**Comment by Zliced13** [comment]
I moved the `bin` and `shortcuts` outside the `architecture` block because I have yet to see a 32bit version that comes with its own shortcuts and binaries. Also, I will make the registry changes optional.

**Comment by rashil2000** [comment]
> I moved the `bin` and `shortcuts` outside the `architecture` block because I have yet to see a 32bit version that comes with its own shortcuts and binaries. 

The path for those bins and shortcuts contains the term 'x64', so it should be inside the architecture block.

> Also, I will make the registry changes optional.

Okay.

**Comment by niheaven** [comment]
I don't like to change R's manifest, and have fixed the issue by https://github.com/ScoopInstaller/Extras/commit/fbcf30f6a858d2ae5a7483e094c0e5841c2c32fd (maybe, please test).

Local test passed.

**Comment by Zliced13** [comment]
I'll test it later on.

**Comment by Zliced13** [comment]
@niheaven it works, I closed both PRs.

**Pull request closed without merging**
