### PR TITLE
miniserve: Fix AU URL

### LINKED ISSUE #4011: miniserve hasn't been updated
## Bug Report

**miniserve** [name of package which has bug(s)]

### Current Behaviour

miniserve hasn't been updated

### Expected Behaviour

updated

### System details

**Windows version: 10** [e.g. 7, 8, 10]

**OS architecture: 64bit** [e.g. 32bit, 64bit]

**PowerShell version: 7.2.6** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
{
  "lastupdate": "2022-10-11T15:46:17.9549824+08:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-enabled": true
}
```

### PR DESCRIPTION
**Pull request by pengwon**
/verify

After v0.20，the github release link modified.

Closes #4011 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pengwon** [comment]
> 



> Hi, please update the manifest to 0.22 version

test

**Comment by rashil2000** [comment]
Hash

**Comment by pengwon** [comment]
> Hash

sorry, and for poor PR title.

**Pull request merged**
