### PR TITLE
podman: Update url to msi url

### LINKED ISSUE #3560: podman: miss some files
## Bug Report

**Package Name:** podman

### Current Behaviour

Compared to msi, zip packages are missing some files.
Such as `win-sshproxy.exe`, `winpath.exe` ...

image

### Expected Behaviour

image

### Possible Solution

Update source url with msi url.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.3

Relates: https://github.com/containers/podman/issues/13675

### PR DESCRIPTION
**Pull request by JadynWong**
Closes #3560

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
The manifest looks fine to me, but is there any advantage to use MSI installer over ZIP file?
Or, is there any information that says *podman* will provide only MSI installers in the future?

**Comment by JadynWong** [comment]
> The manifest looks fine to me, but:
> (1) Is there any advantage to use MSI installer over ZIP file?
> (2) Or, is there any information that says *podman* will provide only MSI installers in the future?

1. As mentioned in # 3560, ZIP is missing more files than MSI. This causes partial functions that cannot work.
2. No. The reason for modification as described above.

**Comment by issaclin32** [comment]
> > The manifest looks fine to me, but:
> > (1) Is there any advantage to use MSI installer over ZIP file?
> > (2) Or, is there any information that says _podman_ will provide only MSI installers in the future?
> 
> 1. As described in [podman: miss some files #3560](https://github.com/ScoopInstaller/Main/issues/3560), ZIP is missing more files than MSI. This causes partial functions that cannot work.
> 2. No. The reason for modification as described above.

Oh. I see.
Sorry that I forgot to check the linked issue first.

**Review by issaclin32 — APPROVED** [review]

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/commit/d1d58bea10134b3cf7c27a67a388f8d722077e0d

**Pull request merged**
