### PR TITLE
scripts: fix python uninstall-pep-514.reg

### LINKED ISSUE #4891: Script python/uninstall-pep-514.reg uninstalls all keys under HKCU\SOFTWARE\Python\PythonCore
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

python

### Expected/Current Behaviour

`uninstall-pep-514.reg` should only remove the keys for the version.

### Steps to Reproduce

```console
1. Install `python` and `python310`
2. Open `install-pep-514.reg` for `python` and `python310`; this will create `HKCU\SOFTWARE\Python\PythonCore\3.11` and `HKCU\SOFTWARE\Python\PythonCore\3.10`, respectively
3. Open `uninstall-pep-514.reg` for `python`; this will remove both `3.11` and `3.10`
```

### Possible Solution

Modify `uninstall-pep-514.reg` to only remove the key for the correct version, i.e. `HKCU\SOFTWARE\Python\PythonCore\3.11` for `python`, `HKCU\SOFTWARE\Python\PythonCore\3.10` for `python310`.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
7a531bb05 (HEAD -> master, origin/master, origin/HEAD) linphone: Update to version 5.0.18

'java' bucket:
5d81a6cb (HEAD -> master, origin/master, origin/HEAD) temurin11-nightly-jre: Update to version 11.0.20-6.0.202306151812
'main' bucket:
bf1ea1352 (HEAD -> master, origin/master, origin/HEAD) octave: Update manifest

'nerd-fonts' bucket:
735fc89 (HEAD -> master, origin/master, origin/HEAD) LXGWNeoXiHei: Update to version 1.101

'scoop-coatl-dev' bucket:
1ca5ad4 (HEAD -> coatl, origin/coatl, origin/HEAD) docs: update README

'versions' bucket:
7c420dddf (HEAD -> master, origin/master, origin/HEAD) webstorm-eap: Update to version 2023.2-232.7754.72
```

### Scoop Config

```console
PS> scoop config

cat_syle      : bat
private_hosts : {@{match=https://files.inductiveautomation.com/*; headers=Referer=https://inductiveautomation.com/}}
last_update   : 6/16/2023 10:23:11
scoop_branch  : master
scoop_repo    : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by thecesrom**
Closes #4891

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
It may cause registry entry of pre-version or uninstalled version cannot be remove by import the registry file.

**Comment by thecesrom** [comment]
Issue #4891 was created because I had `python27` and `python310` installed, and both create a registry key under `HKCU\Software\Python\PythonCore`; `2.7` and `3.10`, respectively.

I uninstalled `python310` and both `2.7` and `3.10` were removed, which was not expected.

The change I propose will only "allow" the version (`3.11`, `3.10`, etc.) to remove its registry key without affecting others that might exist.

**Comment by thecesrom** [comment]
Since what we have right now is already broken, whatever fixes this is more than welcome.

Not sure if you're only dealing in hypothetical cases, but this is what happened to me:

1. `scoop install python27`
2. `scoop install python310`
3. `scoop uninstall python310`
4. `HKCU\Software\Python\PythonCore\3.10` and `HKCU\Software\Python\PythonCore\2.7` were removed

Expected behavior:
Uninstalling `python310` should have only removed `HKCU\Software\Python\PythonCore\3.10`

**Comment by thecesrom** [comment]
> Scense:
> 
> 1. User installed `extras/ptyhon` at version 3.8.10 and imported registrys
> 2. User updated `extras/python` to version 3.10.11
> 3. User updated `extras/python` to version 3.11.4 and imported registrys
> 4. `scoop cleanup python`
> 
> With this change, user cannot remove registrys for older version by this file.

After reading this scenario carefully I still believe my solution is still valid.

In this case Python 3.8.10 is not upgraded to 3.10.11, and so on. All of these versions install side-by-side as these are versioned.

1. `scoop install python38` installs latest Python 3.8
2. `scoop install python310` installs latest Python 3.10
3. `scoop install python311` installs latest Python 3.11

If you were to run `uninstall-pep-514.reg` for `3.11`, all registry entries under `HKCU\Software\Python\PythonCore` will be removed.

With the change I propose uninstalling `python311` will only remove `HKCU\Software\Python\PythonCore\3.11` and keep others.

**Comment by HUMORCE** [comment]
> In this case Python 3.8.10 is not upgraded to 3.10.11, and so on. All of these versions install side-by-side as these are versioned.

In the case I provided, `main/python` is installed and rolling updates, not `versions/pythonXY`.

---

I am writing a script for this, to replaces the reg files. because I learn that registry entries is different between python 2.7, python 
3.5, and python >=3.6. even the different do not cause any effect in use.

**Pull request merged**
