### PR TITLE
pngquant: Fix checkver

### PR DESCRIPTION
**Pull request by rasa**
See #150

### CODE REVIEW

**Comment by niheaven** [comment]
Nope, that version is not Windows release version... Waiting for author's update should be better.

**Comment by rasa** [comment]
https://pngquant.org/pngquant-windows.zip contains pngquant.exe which is version 2.12.0:
```
c:\>pngquant.exe -V
2.12.0 (January 2018)
```

**Comment by niheaven** [comment]
Change its version to 2.12.0?

**Comment by rasa** [comment]
> Change its version to 2.12.0?

I would say no, as there is no way to know what the .exe's version is, other than to download it, unzip it, and run it.

**Comment by niheaven** [comment]
Then left it here, since the lastest version that we get from the website is 2.12.3...

**Comment by r15ch13** [comment]
2.12.1 and newer seem to only contain changes to the build system https://github.com/kornelski/pngquant/issues/312

**Pull request closed without merging**
