### PR TITLE
insect: Update to version 5.7.0

### PR DESCRIPTION
**Pull request by Chanakan55991**
Updated version to 5.7.0

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Could you add a `checkver` section here?

**Comment by Chanakan55991** [comment]
I've added `checkver`. is this correct?

**Comment by niheaven** [comment]
I've added one and now it's correct 😄

**Review by niheaven — APPROVED** [review]

**Pull request merged**
