### PR TITLE
sqlcl: update to 22.3.1.285.1825

### PR DESCRIPTION
**Pull request by delassiops**
- [ X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Already Verified:
> sql -v
> SQLcl: Release 22.3.1.0 Production Build: 22.3.1.285.1828

### CODE REVIEW

**Comment by delassiops** [comment]
Fix Broken download url

**Comment by rashil2000** [comment]
This change will make it impossible to install a previous version of sqlcl

**Comment by delassiops** [comment]
> This change will make it impossible to install a previous version of sqlcl

yes, as oracle changed the way retrieving software, via e delivery sofetware platform

thanks

**Comment by delassiops** [comment]
Already verified

**Pull request merged**
