### PR TITLE
nova: Add version 3.0.2

### PR DESCRIPTION
**Pull request by stevehipwell**
This PR adds Nova v3.0.2.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stevehipwell** [comment]
@rashil2000 the description is from the project README, `scoop` is a package manager and should not be in the business of writing copy for apps.

**Comment by rashil2000** [comment]
App descriptions should be concise and to the point. The exact same information can be conveyed in much less words than the current one. Besides, have a look at what they use in their About section:

image

**Comment by stevehipwell** [comment]
@rashil2000 where is that documented in a way that says what I've submitted here is not concise and to the point? Things like this are subjective and there aren't ever "correct" answers, I thought that the Scoop reboot, that I played a major part in starting, was going to get rid of petty nits in PRs. Unless something is explicitly documented and can be validated automatically we should be permissive rather than restrictive.

**Comment by rashil2000** [comment]
@issaclin32 thoughts?

**Comment by issaclin32** [comment]
I am fine with a longer "description". As long as it is clear enough and **does not look confusing** to users.

desc

**Pull request merged**
