### PR TITLE
Create gdu.json

### PR DESCRIPTION
**Pull request by caoli5288**
Disk usage analyzer with console interface written in Go

### CODE REVIEW

**Comment by telenieko** [comment]
Note that a PR for gdu is already open on lukesampson/scoop-extras#6098
Not submitted to Main because:

> Regarding the criteria for inclussion in the main bucket:
> 
> I do not think this is a reasonably well-know and/or widely used developer tool. The project is relatively new.

**Comment by rashil2000** [comment]
Merged in #2311 

This can be closed.

**Comment by rashil2000** [comment]
@stevehipwell You can close this

**Comment by stevehipwell** [comment]
Closed by #2311.

**Pull request closed without merging**
