### PR TITLE
vhs: Added version 0.1.1

### PR DESCRIPTION
**Pull request by Zliced13**
Also added ttyd, as vhs depends on it to work.

Closes https://github.com/ScoopInstaller/Extras/issues/9604

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@HUMORCE `/verify` is not working for some reason. Do you why there is a bug today with the bot?

**Comment by HUMORCE** [comment]
you can check it in repo actions.

**Comment by niheaven** [comment]
It seems like you put these two files under root dir, not `bucket`.

PS: Please do not use `master` branch to create PR, which is inconvenient for us to review it.

**Comment by Zliced13** [comment]
Oh ok, that's why it's not working let me close this then. Thanks for pointing it out @niheaven

**Pull request closed without merging**
