### PR TITLE
vswhere@3.0.1: update vswhere to latest release

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Review by tydunkel — APPROVED** [review]

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Main/commit/a748a20cc3c43fdf31eddf2b0eb6f35c3c43befd

Note: PRs for version bumps are not necessary. Manifests are updated automatically, unless of course the checkver/autoupdate fields need changing.

**Comment by heaths** [comment]
@rashil2000 thanks for clarifying. Does some pipeline run on a schedule to do that then?

Steps 4-6 in https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets might need an update. I added the original manifest to support automatically updating, but these docs made me think I still had to run `checkver.ps1 vswhere -u` and submit a PR.

**Comment by rashil2000** [comment]
> @rashil2000 thanks for clarifying. Does some pipeline run on a schedule to do that then?

Yes. See https://github.com/ScoopInstaller/Main/blob/master/.github/workflows/excavator.yml

> Steps 4-6 in https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets might need an update. I added the original manifest to support automatically updating, but these docs made me think I still had to run `checkver.ps1 vswhere -u` and submit a PR.

Those steps are for submitting new manifests or fixing some problems in current manifests. For just updating the version of a manifest, we do not recommend making PRs as the it will run into conflicts with the github-actions[bot]

**Pull request closed without merging**
