### PR TITLE
wasmer: Add wasmer 1.0.0

### PR DESCRIPTION
**Pull request by syrusakbary**
This PR adds [Wasmer](https://wasmer.io) to the Scoop project.

### CODE REVIEW

**Comment by Ash258** [comment]
Still same issue https://github.com/ScoopInstaller/Main/pull/741#issuecomment-581012549

image

**Comment by syrusakbary** [comment]
Thanks for the ping! We are working on releasing a new version that hopefully will avoid this issue :)

**Comment by syrusakbary** [comment]
Hi @Ash258 the issue should be fixed now! :)

**Comment by Ash258** [comment]
Pre-realeses are not accepted in Main bucket if there are stable releases. Ping me as soon as 1.0 make it into stable

**Comment by syrusakbary** [comment]
Will do, thanks!

**Comment by rasa** [comment]
It can be added to our Versions bucket, if you’d like.

**Comment by syrusakbary** [comment]
@rasa that would be great, so we can start testing everything! :)

**Comment by rasa** [comment]
Still in alpha: https://github.com/wasmerio/wasmer/releases/

**Comment by syrusakbary** [comment]
The work is continued here: https://github.com/ScoopInstaller/Main/pull/1759

**Pull request closed without merging**
