### PR TITLE
gopher360: add manifest

### PR DESCRIPTION
**Pull request by FriendlyNeighborhoodShane**
It would've been nice to be able to persist config.ini, but that file is created upon first launch, and as far as I can understand, there is no way to persist files that don't exist before installation.

### CODE REVIEW

**Comment by rashil2000** [comment]
It is possible, see https://github.com/ScoopInstaller/Main/blob/87a6c5f0bb98ff3524e2b89957c07f96d5b4bfb1/bucket/mpxplay.json#L8

**Comment by FriendlyNeighborhoodShane** [comment]
Ahhhh, thanks for the tip, I'll amend it in a moment.

(aside: that seems very roundabout. Why don't we just have a `persist_file`??)

**Comment by FriendlyNeighborhoodShane** [comment]
Hmmm... yeah, won't do. The program autogenerates the config upon first launch only if the file doesn't exist. An empty file just makes it do nothing.

The docs say it regenerates the config if the existing file is messed up. Wonder if I can make a 'default' mangled config to do this.

**Comment by rashil2000** [comment]
Why not put something meaningful there, as a default?

**Comment by FriendlyNeighborhoodShane** [comment]
But that creates an extra maintainance burden of having to keep a default. (I know, for a program that hasn't been updated in 4 years??! But still, I'd have preferred to not have to do this "duplication" of data.) Regardless, that might be the only viable option to take here.

Though the blame lands squarely on the program here for being so dumb. It should just use sensible defaults itself upon reading an empty config.

**Comment by rashil2000** [comment]
The other option is to not have a persist at all - given that the repo hasn't had a release for long, that is viable too.

**Comment by FriendlyNeighborhoodShane** [comment]
I think I'm satisfied with this, for now. Might PR/fork upstream to fix this (+ other issues) in the future.

**Review by rashil2000 — APPROVED** [review]

**Review by HUMORCE — CHANGES_REQUESTED** [review]
- missing `bin`, cli program does not need `shortcuts`.
- sort propetrys by repo requirements.

**Comment by FriendlyNeighborhoodShane** [comment]
> * sort propetrys by repo requirements.

Addressed.

> * missing `bin`, cli program does not need `shortcuts`.

This isn't exactly a CLI program.

It launches its own terminal if you launch the executable or its shortcut. You _can_ launch it inside your own terminal, but it sends escape codes that will mangle everything other than CMD (tried on git-bash+cmder). It takes no arguments, so there's no point to launching a terminal and having to type out its name. Moreover, launching it from the terminal makes it choose the current working directory (often home) for its `config.ini`. Launching it from the shortcut makes it use its own scoop directory, which is what we want. (Arguably, some of these are problems that should be fixed upstream.)

So yeah, it behaves more like a GUI app that happens to use a terminal as its interface.

**Comment by HUMORCE** [comment]
i think this app should be move to [extras bucket](https://github.com/ScoopInstaller/Extras).

@rashil2000

**Comment by rashil2000** [comment]
Okay, since it needs to be launched standalone, we can have it in Extras.

**Comment by FriendlyNeighborhoodShane** [comment]
Continued in https://github.com/ScoopInstaller/Extras/pull/7475

**Pull request closed without merging**
