### PR TITLE
uutils: add symlinks for various tools

### PR DESCRIPTION
**Pull request by neheb**
adds symlinks to the various tools. Similar to busybox.

- [x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Some people might not prefer creating so many shims, and many shims conflict with Windows internal tools. I would suggest creating a new manifest, similar to [busybox](https://github.com/ScoopInstaller/Main/blob/master/bucket/busybox.json) and [busybox-lean](https://github.com/ScoopInstaller/Main/blob/master/bucket/busybox-lean.json).

**Comment by neheb** [comment]
Sort of done.

Which shims conflict with Windows tools?

**Comment by rashil2000** [comment]
sort, date, whoami, echo, mkdir, rmdir, tar

**Comment by neheb** [comment]
Some of those don't come with Windows < 10. busybox currently comes with all of those symlinks.

**Pull request merged**
