### PR TITLE
odbc2parquet: Add version 6.0.0

### PR DESCRIPTION
**Pull request by igitur**
Add new package odbc2parquet ( https://github.com/pacman82/odbc2parquet )

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Just use `github` as checkver.

**Comment by igitur** [comment]
> Just use `github` as checkver.

Don't we need the regex to extract the correct version number from the tag name?

**Comment by niheaven** [comment]
It's standard version number format in release/latest tag, so we don't need the regex. Ref: https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases

**Comment by igitur** [comment]
Thanks. I didn't expect it to handle the `v`. Will update soon.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
