### PR TITLE
Add Determined AI CLI manifest

### PR DESCRIPTION
**Pull request by sirredbeard**
Adds the [Determined AI](https://github.com/determined-ai/determined) CLI manifest to Main

Determined has 1.8k ⭐

This manifest makes use of a [simple pass-through determined.exe file](https://github.com/sirredbeard/det-helper) but installs the main components via Python and pip.

[Auto-update function check](https://gist.github.com/sirredbeard/a615dc1276aa029f9584617d12ce52f8) passes.

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Hi!

We don't accept language-specific packages here in the Main bucket, because they are better managed by their respective package managers - PIP in this case. Unless the package is specifically distributed as a single, independent binary, that is.

**Comment by sirredbeard** [comment]
It is not distributed as a separate executable. Would it be accepted into extras?

**Comment by rashil2000** [comment]
Sorry, neither in Extras - the reason is the same - Scoop is not good at managing version-specific, transitive dependencies that PIP or NPM packages require, and installing them through Scoop will give users the wrong impression that it is indeed managing those dependencies itself.

**Comment by sirredbeard** [comment]
I see. In this case when a new release is tagged in GitHub, the CLI is also [pushed to PyPi](https://github.com/determined-ai/determined/blob/74dd27f393fcbccf1cb27b9419aed5e63e9193d8/.circleci/config.yml#L1173), so detection of a new release on GitHub would be a valid signal to upgrade via pip.

**Comment by sirredbeard** [comment]
I have created a third-party [Scoop bucket](https://github.com/sirredbeard/determined-bucket) and noted the issue you raised.

**Comment by rashil2000** [comment]
Thanks for the info! People searching for Determined package on Scoop will find the thread helpful!

**Pull request closed without merging**
