### PR TITLE
secman: Add version 6.2.0

### PR DESCRIPTION
**Pull request by abdfnx**
This Pull Request adds the [**Secman CLI**](https://secman.dev)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Hi @abdfnx, thanks for the PR!

Unfortunately this application does not fit the [Main bucket criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket) yet. I would recommend opening a package request for this instead so that we can track it.

**Comment by rasa** [comment]
Note they host https://github.com/scmn-dev/scoop/blob/main/secman.json 
and they mention scoop in their main readme at
https://github.com/scmn-dev/secman#scoop

@rashil2000 What criteria is not being met?

**Comment by rashil2000** [comment]
Well known (popularity)

**Pull request closed without merging**
