### PR TITLE
nmap-portable: Add version 7.80

### PR DESCRIPTION
**Pull request by r15ch13**
This provides a nmap installation without priviliges.
- Some small fixes for the nmap manifest
- Closes https://github.com/lukesampson/scoop/issues/1799

### CODE REVIEW

**Comment by r15ch13** [comment]
It would be possible to only extract the `npcap-*-oem.exe` and create a separate manifest for it Npcap this way. But I don't think the license would allow this.

https://nmap.org/npcap/#License
https://github.com/nmap/npcap/blob/master/LICENSE

**Comment by linsui** [comment]
If npcap need to be installed manully, why not use the zip package without npcap?
I wonder if it is allowed to install npcap by extracting and installing drivers with pnputil?

**Comment by r15ch13** [comment]
npcap will be installed to `C:\Program Files` and is available under `Add or remove programs`

**Comment by Ash258** [comment]
For me this could go in. Manifests looks good and for behavior I cannot really tell, as I am not consumer.

**Pull request merged**
