### PR TITLE
fix lynx depends: update the slproweb download url

### PR DESCRIPTION
**Pull request by JoaquinRChen**
fix lynx depends: update the slproweb download url

Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
Should we make lynx depend on `openssl1-light` from the Versions bucket? That way we don't have to manually update it in the lynx manifest.

**Comment by rashil2000** [comment]
We can't add a hard dependency on a different bucket.

**Comment by JoaquinRChen** [comment]
> We can't add a hard dependency on a different bucket.
> 
> Regardless, lynx doesn't even work, so I'm debating whether to even keep it or deprecate it

Hi, it works well here?
image

**Pull request merged**
