### PR TITLE
kustomize: update to 4.4.1

### PR DESCRIPTION
**Pull request by pratikpc**
Autoupdate re-enabled

Relates to #2848 

Thanks @natasha41575

### CODE REVIEW

**Review by rashil2000 — APPROVED** [review]

**Comment by pratikpc** [comment]
@natasha41575 could you please install this offline and test once?

**Comment by natasha41575** [comment]
I don't use windows or scoop, I'm just a kustomize maintainer who found your issue because it as linked in the kustomize issue.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
