### PR TITLE
watchman: Add version 2022.05.16.00

### PR DESCRIPTION
**Pull request by ClassicDarkChocolate**
[watchman](https://facebook.github.io/watchman/) is a file watching service by Facebook.

migrate from https://github.com/ScoopInstaller/Extras/pull/8493

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ClassicDarkChocolate** [comment]
> Append `\\bin` to extract_dir

I find that by doing this, there will be an empty folder `watchman-v2022.05.16.00-windows` left.

Shall I add a post_install script to remove the empty leftover folder?
```json
"post_install": "Remove-Item -Path $dir\\watchman-v2022.05.16.00-windows -Recurse -ErrorAction Ignore"
```

**Comment by rashil2000** [comment]
> Shall I add a post_install script to remove the empty leftover folder?
> 
> ```json
> "post_install": "Remove-Item -Path $dir\\watchman-v2022.05.16.00-windows -Recurse -ErrorAction Ignore"
> ```

```json
"post_install": "Remove-Item -Path $dir\\watchman-v$version-windows -Recurse -ErrorAction Ignore"
```

**Comment by rashil2000** [comment]
Sorry, I closed it by mistake.

Do we really need bins for all executables? Is there any documentation on each of them? I think they are for internal use.

**Comment by ClassicDarkChocolate** [comment]
> Do we really need bins for all executables? Is there any documentation on each of them? I think they are for internal use.

From official [documentation](https://facebook.github.io/watchman/docs/install.html#windows), they suggest:

> It contains a bin folder. Move that somewhere appropriate and update your PATH environment to reference that location.

I exclude `eledo-pty-bridge.exe` from bins though.

The others are:

-   `watchman-diag.exe`: [for debug](https://github.com/facebook/watchman/issues/884)
-   `watchman-make.exe`: https://facebook.github.io/watchman/docs/watchman-make.html
-   `watchman-replicate-subscription.exe`: https://facebook.github.io/watchman/docs/watchman-replicate-subscription.html
-   `watchman-wait.exe`: https://facebook.github.io/watchman/docs/watchman-wait.html
-   `watchman.exe`: https://facebook.github.io/watchman/docs/cli-options.html
-   `watchmanctl.exe`: not knowing about it

**Comment by rashil2000** [comment]
Okay so we can remove watchman-diag and watchmanctl from the list

**Comment by ClassicDarkChocolate** [comment]
> Okay so we can remove watchman-diag and watchmanctl from the list

Done.

**Pull request merged**
