### PR TITLE
magic-wormhole: Add version 0.12.0

### PR DESCRIPTION
**Pull request by sitiom**
Binaries from the Chocolatey package https://github.com/aquacash5/magic-wormhole-exe

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Is this an official wormhole outlet? If not, I'm afraid we can't add it to Main bucket

**Comment by sitiom** [comment]
No, but it is what is being used in the Chocolatey package and is listed in the Repology badge in the Wormhole [README](https://github.com/magic-wormhole/magic-wormhole#packaging-installation). I guess [`less`](https://github.com/ScoopInstaller/Main/blob/master/bucket/less.json) does something similar too.

**Comment by rashil2000** [comment]
> No, but it is what is being used in the Chocolatey package and is listed in the Repology badge in the Wormhole [README](https://github.com/magic-wormhole/magic-wormhole#packaging-installation). 

That does not make it official, though. Repology will show any package with that name, if available.

> I guess [`less`](https://github.com/ScoopInstaller/Main/blob/master/bucket/less.json) does something similar too.

less's official website mentions https://github.com/jftuga/less-Windows as the only source for Windows binaries.

image

**Comment by sitiom** [comment]
Hopefully, https://github.com/magic-wormhole/magic-wormhole/pull/436 resolves this.

**Comment by sitiom** [comment]
@rashil2000 All good now.

**Pull request merged**
