### PR TITLE
Update imagemagick-lean.json

### PR DESCRIPTION
**Pull request by ddarfantasy**
Make autoupdate aware of tail version changes since [this change](https://github.com/ImageMagick/ImageMagick/discussions/5749).

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
So the checkver is still picking up `7.1.0` as the version...

**Comment by ddarfantasy** [comment]
> So the checkver is still picking up `7.1.0` as the version...

I left it unchanged, it's the same as before and is consistent with the main imagemagick package. I have no idea why automated test give this result...

**Comment by ddarfantasy** [comment]
Oh, I see, the old zip file is still available, so the checkver thinks the old zip is newer (since old zip name is larger)...
I've asked developers to delete the old zips...

**Comment by rashil2000** [comment]
Cool, thanks for following up with the devs!

**Pull request merged**
