### PR TITLE
chore: Migration of nightlies to `Versions` bucket

### PR DESCRIPTION
**Pull request by niheaven**
Ref: https://github.com/ScoopInstaller/Versions/pull/318

Close https://github.com/ScoopInstaller/Main/issues/2948

### CODE REVIEW

**Comment by rashil2000** [comment]
- docker-nightly
- ffmpeg-nightly
- ffmpeg-nightly-shared
- ffmpeg-nightly-vulkan (no longer available)
- ffmpeg-nightly-shared-vulkan (no longer available)
- glslang-nightly
- neovim-nightly
- jar2app

Let's migrate these too in this PR.

**Comment by niheaven** [comment]
`jar2app` is a nightly app, but it doesn't need to be moved. I'll move all other ones.

**Comment by rashil2000** [comment]
> `jar2app`

It was mentioned in https://github.com/ScoopInstaller/Extras/issues/2821#issue-490708605, that's why.

There hasn't been any commit since 2018 in its source - should we deprecate it instead?

(Also, what is a Mac OS tool doing in Scoop repos? 😅)

**Comment by niheaven** [comment]
This was added in https://github.com/ScoopInstaller/Scoop/pull/3277, and I really don't know why...

**Review by rashil2000 — APPROVED** [review]

**Comment by pratikpc** [comment]
@niheaven in the interest of not breaking workflows, I believe we should not move the nightlies which update via Scoop

We should probably deprecate this though
> ffmpeg-nightly-vulkan (no longer available)
> ffmpeg-nightly-shared-vulkan (no longer available)

**Comment by niheaven** [comment]
We could keep them until scoop has an alias feature and redirect these manifests to versions' ones. Then after one or two months, delete them as this PR.

**Comment by JanPokorny** [comment]
Scoop really ought to have something like `"moved_to": "versions/docker-nightly"` which would tell the CLI to rewire the installed package to the new manifest. You can actually do this manually pretty easily.

**Comment by rashil2000** [comment]
I think this PR can be merged. The download links for all ffmpeg builds are dead anyway, and Neovim's wiki recommends using Versions bucket since a long time now:

image

**Comment by rashil2000** [comment]
Also glslang-nightly's manifest is wrong - the app is 64bit but there's no architecture block

**Comment by niheaven** [comment]
I'll resolve the conflicts.

**Pull request merged**
