### PR TITLE
oauth2c: Add version 1.15.0

### PR DESCRIPTION
**Pull request by igitur**
oauth2c: Add version 1.13.0

https://github.com/cloudentity/oauth2c

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Please add arm64 version and autoupdate.hash section as well.

**Comment by igitur** [comment]
Thanks @aliesbelik . Changes made.

**Comment by igitur** [comment]
@aliesbelik All changes done.

**Pull request merged**
