### PR TITLE
Add SpaceSniffer

### PR DESCRIPTION
**Pull request by mottosso**
Hi everyone,

I'd love to have [this lovely little program](http://www.uderzo.it/main_products/space_sniffer/) available through Scoop! It's my first attempt at making a manifest, trying my best to adhere to the [guide](https://github.com/lukesampson/scoop/wiki/App-Manifests), but let me know if anything is missing or incorrect. I've tested this on my end and it appears to work just fine.

Best,
Marcus

### CODE REVIEW

**Comment by linsui** [comment]
https://github.com/lukesampson/scoop-extras/blob/master/bucket/spacesniffer.json

**Comment by mottosso** [comment]
Thanks @linsui, should have looked more closely!

**Comment by mottosso** [comment]
How come that bucket isn't in this organisation? Would make it a little easier to find I think. Any other public buckets out there, or a collection of links to where they're hiding?

**Comment by Ash258** [comment]
This needs to be done by @lukesampson and it's his decision (lukesampson/scoop#3437)

**Pull request closed without merging**
