### PR TITLE
ffmpeg: Use alternative download URLs

### LINKED ISSUE #1379: Deprecate ffmpeg manifests until alternative builds are provided
Builds provided by Zeranoe will no longer be provided on 18.09.2020

image

### LINKED ISSUE #1406: ffmpeg@4.3.1: download via aria2 failed
ERROR Download failed! (Error 3) Resource was not found
ERROR https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip
    referer=https://ffmpeg.zeranoe.com/builds/win64/static/
    dir=D:\Software\Scoop\cache
    out=ffmpeg#4.3.1#https_ffmpeg.zeranoe.com_builds_win64_static_ffmpeg-4.3.1-win64-static.zip

ERROR & 'D:\Software\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Software\Scoop\cache\ffmpeg.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6872 --continue

### LINKED ISSUE #1415: ffmpeg@4.3.1: Download failed
Scoop will not install ffmpeg 4.3.1 due to a 404 error. I verified using my normal web browser that indeed this results in a 404, and the same problem occurs with Tor Browser (so it is not my ISP blocking this file).

```PS > scoop update
Updating Scoop...
Updating 'extras' bucket...
Updating 'main' bucket...
Scoop was updated successfully!
PS > scoop install ffmpeg
Installing 'ffmpeg' (4.3.1) [64bit]
The remote server returned an error: (404) Not Found.
URL https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip is not valid
PS C:\Users\sjmur>
```

### PR DESCRIPTION
**Pull request by lando-cal**
This addresses #1415 for 64-bit ffmpeg. It still needs 32 bit, but this got me through for now. Figured I'd contribute as a starting point for anyone else who wants to pick it up.

close #1415 
close #1406
close #1379
close https://github.com/lukesampson/scoop/issues/4105
close https://github.com/lukesampson/scoop/issues/4078

### CODE REVIEW

**Review by chawyehsu — APPROVED** [review]

**Review by rasa — APPROVED** [review]

**Comment by chawyehsu** [comment]
@rasa I can't close issues from https://github.com/lukesampson/scoop , can you merge this?

**Comment by thomastay** [comment]
hold on, it looks like the website has changed and https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-full_build.zip is now invalid. It looks like the author has added the date into the URL too. https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-2020-09-21-full_build.zip is the latest build. I'm not sure how to add the right date though.

**Comment by vig42** [comment]
> 
> 
> hold on, it looks like the website has changed and https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-full_build.zip is now invalid. It looks like the author has added the date into the URL too. https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-2020-09-21-full_build.zip is the latest build. I'm not sure how to add the right date though.

I was able to get around this issue using a pre-install script. This basically does the same thing as setting the "extract_dir", except we don't need to specify the name of the directory. So even though we cannot add the date, we can still get the files out of the subfolder.

```json
"pre_install": [
    "$subfolder = $(Get-ChildItem ${dir} -Directory)[0].fullname",
    "robocopy ${subfolder} ${dir} /e /move | Out-Null"
],
```

**Comment by moarbytes** [comment]
The [https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.zip](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.zip) and [https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip) URLs don't change, FYI. The lack of any versioning doesn't help with checking for updates though...

**Comment by wstein** [comment]
You may take my pull request #1454 in consideration. It uses the BtbN/FFmpeg-Builds builds. I think it is the most complete solution.

It handles the following variants: **ffmpeg**, **ffmpeg-shared**, **ffmpeg-nightly** (the shared and also the vulkan build)

**Comment by GyanD** [comment]
If you're considering my builds, is there any format you would like for the links, and the filenames?

**Comment by chawyehsu** [comment]
The pull request #1454 seems better. I would like to accept #1454. Closed this.

**Pull request closed without merging**
