### PR TITLE
fciv: deprecate manifest

### LINKED ISSUE #1817: fciv@2.05: Download failed
The remote server returned an error: (404) Not Found.

### PR DESCRIPTION
**Pull request by rashil2000**
Closes #1817

Both the Homepage and download link are dead. FCIV is no longer distributed.

### CODE REVIEW

**Review by pratikpc — APPROVED** [review]
https://support.microsoft.com/en-us/topic/d92a713f-d793-7bd8-b0a4-4db811e29559

**Comment by rashil2000** [comment]
There's no download link

**Comment by pratikpc** [comment]
@rashil2000 yes that's why I added it

For documentation reasons

**Review by issaclin32 — COMMENTED** [review]
I would suggest adding a third-party URL to keep the package working.
```
{
    "version": "2.05",
    "description": "A command-prompt utility that computes and verifies cryptographic hash values of files.",
    "homepage": "https://support.microsoft.com/en-us/kb/841290",
    "license": "Proprietary",
    "url": "http://down2.opdown.com:8019/opdown/fciv.exe.zip",
    "pre_install": "Expand-7zipArchive \"$dir\\Windows-KB841290-x86-ENU.exe\" -Removal",
    "hash": "f6f4753d019aaa5ebdcfc743827ee530962d853e0f90852860f0cec016430040",
    "bin": "fciv.exe"
}

```

**Comment by pratikpc** [comment]
@issaclin32 not the best of ideas IMHO.

If tomorrow the 3rd party URL starts distributing viruses, we would be responsible.

**Comment by rashil2000** [comment]
Yes, we can't vouch for third party sites always.

**Pull request merged**
