### PR TITLE
ALIEN: Add version 4.4.1

### PR DESCRIPTION
**Pull request by chrxh**
This PR adds ALIEN, a CUDA-powered artificial life simulation program: https://github.com/chrxh/alien

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Hi @chrxh! 

Why did you close this?

**Comment by chrxh** [comment]
Hi @rashil2000,
I closed this PR because the program is using a GUI. I had created an other PR in the Scoop/Extras bucket (it's already merged).

**Comment by rashil2000** [comment]
Oh, I see

**Pull request closed without merging**
