### PR TITLE
conftest: Add version 0.27.0

### PR DESCRIPTION
**Pull request by stevehipwell**

### CODE REVIEW

**Comment by jpreese** [comment]
Thanks @stevehipwell !

**Comment by stevehipwell** [comment]
Could someone review this please?

**Comment by stevehipwell** [comment]
@rasa sorry to tag you directly but as you merged my last PR (no good deed goes un-punished and all that) and there has been no action on this and https://github.com/ScoopInstaller/Main/pull/2127 could you take a look?.

**Comment by stevehipwell** [comment]
@r15ch13 @Ash258 apologies for adding you directly but you're the only two maintainers who appear to have been active recently. Could you take a look at this and the related #2127?

**Comment by stevehipwell** [comment]
@dwettstein could you take a look at this?

**Review by dwettstein — CHANGES_REQUESTED** [review]
So far so good. I assume the `extract_dir` parameter within `architecture` is optional, right (see `bat.json` for example)?

However, there is a typo in the hash url, the file name is actually `checksums.txt` (with an `s` at the end): https://github.com/open-policy-agent/conftest/releases/tag/v0.27.0.

**Comment by stevehipwell** [comment]
@dwettstein thanks for the review, I'll fix the typo. Re [extract_dir](https://scoop-docs.vercel.app/docs/concepts/App-Manifests.html#optional-properties), this is required if the archive contents is inside a folder, which it isn't here.

**Comment by stevehipwell** [comment]
@dwettstein could you re-review?

**Review by dwettstein — APPROVED** [review]
All good 👍

**Pull request merged**
