### PR TITLE
bluetooth-cli-tools: Add version 1.2.0.56

### PR DESCRIPTION
**Pull request by Zliced13**
Closes https://github.com/ScoopInstaller/Extras/issues/10917

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
What's the reason for having it here instead of in Extras?

**Comment by Zliced13** [comment]
It's a collection of CLI tools, I figured it belonged on the main bucket. Also, why should I add to the **extras** bucket, is it not that known.

**Comment by rashil2000** [comment]
> Is it not that known?

No, what's the indication for its popularity/repute?

**Comment by Zliced13** [comment]
Actually I searched it up, it's not that known. I'll move this to the extras bucket.

**Pull request closed without merging**
