### PR TITLE
nodejs-lts: fix checkver and add arm64 version

### PR DESCRIPTION
**Pull request by azrdn**
Due to the [redesign](https://nodejs.org/en/blog/announcements/diving-into-the-nodejs-website-redesign) of the Node.js website, the checkver of the nodejs-lts package is broken, this pull request fixes it, and also adds the arm64 version

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eteeselink** [comment]
For what it's worth: I'm not sure how to review this, but I tested it by running this:

```sh
scoop install https://raw.githubusercontent.com/ScoopInstaller/Main/0f5202c216bf79be81549880c86f33eef1218be9/bucket/nodejs-lts.json
```
(that's the raw URL of the file in this PR)

and it worked flawlessly on my computer. Thanks!

**Comment by f-cramer** [comment]
Seeing how long it takes to for those PRs to get merged, we should change the checkver script to instead get the latest version from https://nodejs.org/dist/index.json to no longer be dependent on the layout of nodejs.org.
See https://github.com/ScoopInstaller/Nonportable/pull/295 for my PR in the nonportable bucket that does exactly that.

**Pull request merged**
