### PR TITLE
air: Add version 1.42.0

### LINKED ISSUE #4619: [Request]: air - Live reload for Go apps
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

air

### Description

A live-reloading command line utility for developing Go applications.

### Homepage

https://github.com/cosmtrek/air

### Download Link(s)

https://github.com/cosmtrek/air/releases

### Some Indication of Popularity/Repute

Open sourced (GPL-3.0 license) on GitHub with 9.7k star

### PR DESCRIPTION
**Pull request by jonz94**
Closes #4619 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Please add autoupdate hash extraction via https://github.com/cosmtrek/air/releases/download/v1.42.0/air_1.42.0_checksums.txt

**Comment by jonz94** [comment]
@rashil2000 Done!

**Pull request merged**
