### PR TITLE
pacproxy: Add version 2.0.5

### PR DESCRIPTION
**Pull request by 0xced**
Add a new app manifest for the [pacproxy](https://github.com/williambailey/pacproxy) tool which is handy when you are working in an environment with many different proxy servers and your applications don't support proxy auto-configuration.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by tech189 — APPROVED** [review]
Tested installation 64bit & 32bit, autoupdate 👍

**Comment by rashil2000** [comment]
[Internal discussion maintainers#19]

**Comment by rashil2000** [comment]
Hi @0xced, thanks for the PR, but I'll have to close this one because unfortunately the tool does not meet the "well-known" criteria yet. 

However, you can create a package request for it so that we can keep track of it.

**Pull request closed without merging**
