### PR TITLE
docker-buildx: Add version 0.11.2

### LINKED ISSUE #4840: [Request]: docke-buildx
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

docker-buildx

### Description

Docker CLI plugin for extended build capabilities with BuildKit

### Homepage

https://github.com/docker/buildx

### Download Link(s)

https://github.com/docker/buildx/releases/download/v0.10.5/buildx-v0.10.5.windows-amd64.exe

### Some Indication of Popularity/Repute

[Repo](https://github.com/docker/buildx)
GitHub 2.6k star, 378 forks

### PR DESCRIPTION
**Pull request by AzureZeng**
Closes #4840

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
- Split the post_install into multiple lines using a string array.
- You can check for the `$global` variable, and if it's true, copy the plugin into `C:\ProgramData\Docker\cli-plugins` instead of `%USERPROFILE%\.docker\cli-plugins`
- Add the arm64 variant of the package

**Comment by AzureZeng** [comment]
@rashil2000 Updated the file according to your advice.

**Pull request merged**
