### PR TITLE
pngquant: update to v2.16.0

### PR DESCRIPTION
**Pull request by pratikpc**
add autoupdate

### CODE REVIEW

**Comment by rashil2000** [comment]
The URL isn't changing, why is autoupdate required?

**Comment by pratikpc** [comment]
Check with checkver.ps1 -Dir $env:SCOOP\buckets\main\bucket -App pngquant -Update

Without autoupdate present, it does not update the hash or version at the moment.

**Comment by pratikpc** [comment]
We are facing the same issue here as well

> The SSL connection could not be established, see inner exception.

**Comment by rashil2000** [comment]
This is something that needs to be fixed in Scoop core, as mentioned in my comment the other day

**Comment by Valinor** [comment]
I already do this work with #2847 Autoupdate manifest 2845, with lot of more update.
Why this PR? Should I remove #2847 ?

**Pull request closed without merging**
