### PR TITLE
dotnet-sdk: Update to version 3.1.100

### PR DESCRIPTION
**Pull request by CarlosDomingues**

### CODE REVIEW

**Comment by niheaven** [comment]
Please change `checkver` to

```json
"checkver": {
    "url": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json",
    "regex": "(?s)(?<rtv>[\\d.]+)[^\\d]*?([\\d.]+)[^\\d]*?lts"
},
```

and `autoupdate.hash` to

```json
"hash": {
    "url": "https://dotnetcli.blob.core.windows.net/dotnet/checksums/$matchRtv-sha.txt"
}
```

**Comment by linsui** [comment]
Why match `lts` ? How about

```
    "checkver": {
        "url": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json",
        "jsonpath": "$.releases-index[0].latest-sdk"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$version/dotnet-sdk-$version-win-x64.zip"
            },
            "32bit": {
                "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$version/dotnet-sdk-$version-win-x86.zip"
            }
        },
        "hash": {
            "url": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/$majorVersion.$minorVersion/releases.json",
            "regex": "(?s)$basename.*?$sha512"
        }
    }
```

or

```
    "checkver": {
        "url": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json",
        "jsonpath": "$.releases-index[0].latest-sdk"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$version/dotnet-sdk-$version-win-x64.zip",
                "hash": {
                    "url": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/$majorVersion.$minorVersion/releases.json",
                    "jsonpath": "$.releases[?(@.sdk.version == '$version')].sdk.files[?(@.name == 'dotnet-sdk-win-x64.zip')].hash"
                }
            },
            "32bit": {
                "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$version/dotnet-sdk-$version-win-x86.zip",
                "hash": {
                    "url": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/$majorVersion.$minorVersion/releases.json",
                    "jsonpath": "$.releases[?(@.sdk.version == '$version')].sdk.files[?(@.name == 'dotnet-sdk-win-x86.zip')].hash"
                }
            }
        }
    }
```

**Comment by niheaven** [comment]
For `checkver`, `$.releases-index[0]` might not always be stable version.

For `au.hash`, that hash txt file is the official checksum source and is much smaller than the json file.

**Comment by linsui** [comment]
What's the support phase of unstable version? Should we also match maintenance? And we can only extract the release-index object of lts version with jsonpath to make the regex more readable.
The size of json file is not important as it's only downloaded when update.

**Comment by niheaven** [comment]
See `versions` bucket for some other support-phase.

Who will use maintenance by default? For jsonpath, it doesn't work when there are more than one match.

A short, clear regex is more preferred than long, complex jsonpath, that's all.

**Comment by linsui** [comment]
What's the difference between this and [versions/dotnet-sdk-lts](https://github.com/ScoopInstaller/Versions/blob/master/bucket/dotnet-sdk-lts.json) ?

**Comment by niheaven** [comment]
Before ms's recent update, this one's support-phase is 'current', 'lts' and 'preview' are in `versions`.

Now there are no 'current' and 'preview', but two 'lts' (one for 3.x and one for 2.x) and several 'maintenance'. So use 'lts' for lts and this one, and let 'preview' wait for next preview. This is a logical choice.

**Comment by rasa** [comment]
#150

**Comment by r15ch13** [comment]
Possible solution:
```
    "checkver": {
        "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/LTS/latest.version",
        "regex": "[a-fA-F\\d]{40}\\s+([\\d.]+)"
    },
```
URL has been taken from the [dotnet install scripts](https://dotnet.microsoft.com/download/dotnet-core/scripts).
Checksums can be extracted from the [thank you page](https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.100-windows-x64-binaries).

```json
{
    "version": "3.1.100",
    "homepage": "https://www.microsoft.com/net/",
    "description": ".NET is a free, cross-platform, open source developer platform for building many different types of applications.",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.1.100/dotnet-sdk-3.1.100-win-x64.zip",
            "hash": "sha512:94ee575d6104058cdd31370fc686b5d1aa23bf4a54611843c1f93afc82cad3523217b5f2eaddd4b5c136bca252d2c9047092f7054052c8683fa0f363ca28ad11"
        },
        "32bit": {
            "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.1.100/dotnet-sdk-3.1.100-win-x86.zip",
            "hash": "sha512:51da4337cb56e997d120b738f92a896f081dd43fe557dec22c7f5b6224a1867031193bcddf10cb22f5fb8da4cba1286e54ce0ffa60023bb93f6975d3985dd19f"
        }
    },
    "bin": "dotnet.exe",
    "env_set": {
        "DOTNET_ROOT": "$dir",
        "MSBuildSDKsPath": "$dir\\sdk\\$version\\Sdks"
    },
    "checkver": {
        "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/LTS/latest.version",
        "regex": "[a-fA-F\\d]{40}\\s+([\\d.]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$version/dotnet-sdk-$version-win-x64.zip",
                "hash": {
                    "url": "https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-$version-windows-x64-binaries",
                    "regex": "id=\"checksum\".+value=\"([a-fA-F\\d]{128})\">"
                }
            },
            "32bit": {
                "url": "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$version/dotnet-sdk-$version-win-x86.zip",
                "hash": {
                    "url": "https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-$version-windows-x86-binaries",
                    "regex": "id=\"checksum\".+value=\"([a-fA-F\\d]{128})\">"
                }
            }
        }
    }
}
```

**Comment by niheaven** [comment]
version

If there is `current` version, it is the latest one. If not, `lts` is the latest. So latest version should be gotten by

```json
    "checkver": {
        "url": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json",
        "regex": "(?s)(?<rtv>[\\d.]+)[^\\d]*?([\\d.]+)[^\\d]*?(?:current|lts)"
    },
```

A pure checksum file's location can be found in https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.0/3.1.0.md.

**Pull request closed without merging**
