### PR TITLE
uv: Add version 0.1.2

### PR DESCRIPTION
**Pull request by Tyarel8**
uv is an extremely fast Python package installer and resolver, written in Rust.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by chawyehsu — COMMENTED** [review]
You may add `32bit` support when it is available.

**Comment by Tyarel8** [comment]
I don't know why the Checkver doesn't pass, it works fine for me.

**Comment by rasa** [comment]
Works for me too.

**Pull request merged**
