### PR TITLE
wingetcreate: Add version 1.2.5.0

### PR DESCRIPTION
**Pull request by sitiom**
Official Winget manifest creator tool

Settings are stored in `$env:LOCALAPPDATA\Microsoft\WindowsPackageManagerManifestCreator\settings.json`

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sitiom** [comment]
> - [ ] Autoupdate Hash Extraction

Extraction from https://github.com/microsoft/winget-create/releases/download/v1.2.5.0/wingetcreate.exe.txt fails?

**Comment by rashil2000** [comment]
Could you also add the `scoop install wingetcreate` instruction to https://github.com/microsoft/winget-create#install-from-the-github-repo? Thanks!

**Comment by sitiom** [comment]
Ok

**Pull request merged**
