### PR TITLE
aztfy: Add version 0.2.0

### LINKED ISSUE #3523: [Request] Azure Terrafy
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** Azure Terrafy (aztfy)

**Description:** A tool to bring existing Azure resources under Terraform's management

**Homepage:** https://github.com/Azure/aztfy

**Download link(s):** https://github.com/Azure/aztfy/releases/tag/v0.2.0

**Some indication of popularity/repute:** 400 stars

I have a manifest ready to open in a PR if you like.

### PR DESCRIPTION
**Pull request by Megasware128**
Closes #3523

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
*persist* is not needed because config/cache is at `$Env:LocalAppData`.
(This is a reminder, no need to modify anything)

**Review by issaclin32 — APPROVED** [review]

**Comment by issaclin32** [comment]
> /verify

Oh. I forgot that, but I think it is fine because I have tested autoupdate and installation locally.

**Comment by rashil2000** [comment]
>  I have tested autoupdate and installation locally.

I know :)

I just do it just in case because sometimes GitHub Actions and local verification do not match.

**Pull request merged**
