### PR TITLE
chafa: Add version 1.12.4

### LINKED ISSUE #4441: [Request]: Chafa
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

chafa

### Description

📺🗿 Terminal graphics for the 21st century.

### Homepage

https://hpjansson.org/chafa/

### Download Link(s)

Download Website: https://hpjansson.org/chafa/download/
Download link(1.12.4-1): https://hpjansson.org/chafa/releases/static/chafa-1.12.4-1-x86_64-windows.zip

### Some Indication of Popularity/Repute

GitHub Page: https://github.com/hpjansson/chafa

Stars: 1.9k stars
Watchers: 29
Forks: 43 forks

### PR DESCRIPTION
**Pull request by LaunchLee**
Closes #4441 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Could you send a PR upstream to update pages https://github.com/hpjansson/chafa/blob/master/README and https://hpjansson.org/chafa/download/ with Scoop instructions?

**Comment by LaunchLee** [comment]
Sure. I will try to do it.

**Comment by LaunchLee** [comment]
OK. The things should had been done. The developer of chafa would care about it.

**Comment by rashil2000** [comment]
Thanks!

**Pull request merged**
