### PR TITLE
cuda: update to version 11.6.1_511.65

### PR DESCRIPTION
**Pull request by tech189**
Relates to Excavator failure due to checkver: https://github.com/ScoopInstaller/Main/runs/5606329917?check_suite_focus=true#step:3:243

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Minor nit: Always capitalize the first letter of commit message, like this:
```
cuda: update to version 11.6.1_511.65
      v
cuda: Update to version 11.6.1_511.65
```

**Comment by tech189** [comment]
Oh sure thing! Also hope you don't mind the spam of PRs :P

**Comment by rashil2000** [comment]
Certainly not! I love that you're helping us out, your PR's are high quality and don't require much review - I just have to hit merge 😅

**Comment by tech189** [comment]
Haha thanks, it's fun and satisfying to know that these manifests are being used by lots of people! And thanks for your help too!😄

**Pull request merged**
