### PR TITLE
config-file-validator: Add version 1.7.1

### PR DESCRIPTION
**Pull request by sitiom**
Cross Platform tool to validate configuration files

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sitiom** [comment]
CC @kehoecj (you might be interested in this)

**Comment by kehoecj** [comment]
> CC @kehoecj (you might be interested in this)

Thanks for the add! I'll update the validator README to list Scoop as a download option once this PR gets merged

**Comment by sitiom** [comment]
I'm also adding it to Winget, please see https://github.com/Boeing/config-file-validator/pull/167

**Pull request merged**
