### PR TITLE
curl: Add `arm64` arch, Update URLs, Fix hash url

### LINKED ISSUE #3593: `scoop update curl` fails updating curl to recent version (7.83.1_1 atm)
## Bug Report

**Package Name:** curl

### Current Behaviour

`scoop update curl` fails updating curl to recent version (7.83.1_1 atm)

### Expected Behaviour

Successfully updating curl to recent version (7.83.1_1 atm)

### Additional context/output

```
PS C:\Users\przemoc> scoop update curl
curl: 7.83.0 -> 7.83.1_1
Updating one outdated app:
Updating 'curl' (7.83.0 -> 7.83.1_1)
Downloading new version
OperationStopped: C:\Users\przemoc\scoop\apps\scoop\current\lib\install.ps1:107
Line |
 107 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

- `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"` doesn't help.
- Running `scoop update curl` from `cmd` doesn't help.
- Before upgrading PowerShell from version 7.2.3, the issue was also there.

### System details

**Windows version:** 7
Microsoft Windows 7 Professional 6.1.7601 Service Pack 1 Build 7601

**OS architecture:** 64-bit

**PowerShell version:** 7.2.4

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-05-21T12:34:50.2158203+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

### PR DESCRIPTION
**Pull request by sitiom**
Curl homepage has moved to https://curl.se/

Closes #3593

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sitiom** [comment]
Url works just fine:
image
https://curl.se/windows/

**Comment by rashil2000** [comment]
Maybe we can keep the old domain for now (it does redirect automatically), till GitHub Action's DNS gets updated

**Comment by sitiom** [comment]
> till GitHub Action's DNS gets updated

What does this mean?

**Comment by rashil2000** [comment]
[Domain Name System - Wikipedia](https://en.wikipedia.org/wiki/Domain_Name_System)

GitHub Action is not able to find `curl.se` right now, because it's new

**Comment by sitiom** [comment]
How do you know it's new?

**Comment by rashil2000** [comment]
Looks like it did get updated.

**Pull request merged**
