### PR TITLE
gcc: expat package update to 2.2.10-1 and zst compression?!?

### PR DESCRIPTION
**Pull request by dionysius**
> URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid

Hi, couldn't install `gcc` because package `...2.2.9-1...tar.xz` is no longer available. I've updated it to `2.2.10-1`, but the file extension is tar.zst!? Do we support that?

While at it, I was looking through all the files. The same issue also with:
- gettext
- libiconv
- pkg-config
- zlib

### CODE REVIEW

**Comment by dionysius** [comment]
Just found matching issue #1086 , I have to add 2 more i686 updates, one second

**Comment by dionysius** [comment]
done, those two i686 packages according to the issue has been added as well

**Comment by chawyehsu** [comment]
> and zst compression?!?

zst is not supported by scoop's decompression functionality currently, thus zst-related updates will not be merged until the support launch, there is a hanging [PR](https://github.com/lukesampson/scoop/pull/4137) waiting for discussions and reviews.

For the time being, I suggest using alternative gcc packages like [llvm-mingw](https://github.com/chawyehsu/dorado/blob/master/bucket/llvm-mingw.json), [nuwen-mingw-gcc](https://github.com/chawyehsu/dorado/blob/master/bucket/nuwen-mingw-gcc.json), or [winlibs-mingw](https://github.com/chawyehsu/dorado/blob/master/bucket/winlibs-mingw.json).

**Comment by dionysius** [comment]
Thank you, one can come back to this PR once the support has been added. So far I helped as far as I could.

**Pull request closed without merging**
