### PR TITLE
fastfetch@2.0.4: Add arm64

### PR DESCRIPTION
**Pull request by CarterLi**
For smaller files to download

Closes #XXXX

Relates to #XXXX

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by HUMORCE — APPROVED** [review]

**Comment by CarterLi** [comment]
The arm64 binaries were built manually by me and I cannot ensure that they are available for every releases.

**Comment by HUMORCE** [comment]
> The arm64 binaries were built manually by me and I cannot ensure that they are available for every releases.

https://github.com/ScoopInstaller/Main/commit/8d70a46021c86288379db00c502d15a7509d302a

okay, create pr when you can provide it for long term.

**Comment by CarterLi** [comment]
Not before Github Action supports it.

**Pull request merged**
