### PR TITLE
cargo-binstall: Add version 1.6.0

### LINKED ISSUE #5373: [Request]: cargo-binstall
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

cargo-binstall

### Description

Binary installation for rust projects

### Homepage

https://github.com/cargo-bins/cargo-binstall

### Download Link(s)

https://github.com/cargo-bins/cargo-binstall/releases/download/latest/cargo-binstall-x86_64-pc-windows-msvc.zip

### Some Indication of Popularity/Repute

1.1K star

### PR DESCRIPTION
**Pull request by NobodyXu**
Closes #5373

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
You forgot to add the hashes

**Comment by NobodyXu** [comment]
> You forgot to add the hashes

`cargo-binstall` release does not provide hashes, it provides a signature instead (generated using `minisign`)

**Comment by rashil2000** [comment]
You can manually download the release packages and calculate their hashes using `Get-FileHash` in PowerShell.

**Comment by NobodyXu** [comment]
I can do that, in that case do I need to provide hash for autoupdate?

**Comment by rashil2000** [comment]
> do I need to provide hash for autoupdate?

No

**Comment by NobodyXu** [comment]
@rashil2000 Thanks, I've added sha256 hash using methods you described.

**Pull request merged**
