### PR TITLE
ncspot: Update to version 0.9.3

### PR DESCRIPTION
**Pull request by itytophile**
Update from `0.9.0` to `0.9.3`. Add `x86_64` to urls.

### CODE REVIEW

**Comment by rashil2000** [comment]
Can you fix the hash extraction?

**Comment by itytophile** [comment]
Hi, which command do you use to test if the manifest is correct? I replaced `"url": "$urlNoExt.sha256"` by `"url": "$baseurl/ncspot-v$version-windows-x86_64.sha256"` but I don't really know if this works. Thanks.

**Comment by rashil2000** [comment]
You can make the commit here, and then comment `/verify` like I did

**Pull request merged**
