### PR TITLE
torpar: Add version 1.0.0

### PR DESCRIPTION
**Pull request by Slach**
TUI Client for Torrent Paradise
https://github.com/varbhat/torpar

### CODE REVIEW

**Comment by pratikpc** [comment]
@Slach no need to apologise!

I guess it is ready but now its upto the maintainers to accept it

**Comment by akirayamamoto** [comment]
What is the criteria to approve a new package?

**Comment by issaclin32** [comment]
@pratikpc Thank you for the help!

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
