### PR TITLE
gauche: update to version 0.9.11-p1

### PR DESCRIPTION
**Pull request by tech189**
Relates to Excavator failure due to patch release not being standard name: https://github.com/ScoopInstaller/Main/runs/5585775074?check_suite_focus=true#step:3:250

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
Hmm should I incorporate `-p` patch numbering into the checkver regex?

**Comment by rashil2000** [comment]
> Hmm should I incorporate `-p` patch numbering into the checkver regex?

Yes

**Pull request merged**
