### PR TITLE
nu@0.86.0: Use the full binary for nushell

### LINKED ISSUE #5199: [Bug]: nu@0.86.0 does not include the dfr command
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

nu

### Expected/Current Behaviour

In the nu shell, the `dfr` command should be available. The binary available direct from the `nu` project website includes that command, but the `nu` installed via scoop does not.

### Steps to Reproduce

```console
PS> scoop info nu

Name        : nu
Description : A modern shell written in Rust
Version     : 0.86.0
Bucket      : main
Website     : https://www.nushell.sh
License     : MIT
Updated at  : 18/10/2023 16:12:17
Updated by  : github-actions[bot]
Installed   : 0.80.0
              0.83.0
              0.83.1
              0.84.0
              0.85.0
              0.86.0
Binaries    : nu.exe
PS> nu
nu> dfr
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ dfr
   · ─┬─
   ·  ╰── executable was not found
   ╰────
  help: program not found
```
```


### Possible Solution

The only fix I know of is to use the build from the nu project rather than scoop. I tried running `~\scoop\apps\nu\current\nu.exe` directly rather than using the shim, but that did not help.

### Scoop and Buckets Version

```console
❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'enk' bucket:
81f01ef (HEAD -> master, origin/master, origin/HEAD) pip 23.3

'extras' bucket:
b2ab29f34 (HEAD -> master, origin/master, origin/HEAD) argyllcms: Update to version 3.0.1

'java' bucket:
6ffbdc38 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.392-8.0.202310181914

'main' bucket:
a68197ca1 (HEAD -> master, origin/master, origin/HEAD) ov: Update to version 0.32.1

'versions' bucket:
5bd5b7925 (HEAD -> master, origin/master, origin/HEAD) zig-dev: Update to version 0.12.0-dev.1108
```
```


### Scoop Config

```console
❯ scoop config

last_update         scoop_repo                           scoop_branch
-----------         ----------                           ------------
19/10/2023 12:37:35 https://github.com/lukesampson/scoop master
```
```


### PowerShell Version

```console
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by pfmoore**
Closes #5199

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Please also add the arm64 variant in the manifest!

**Comment by pfmoore** [comment]
The arm64 variant wasn't in the original manifest, and I have neither a need for the arm64 variant, nor a means of testing it. So honestly, I'd rather not. Could that not be added as a separate PR by someone who has a need for it?

**Pull request merged**
