### PR TITLE
Update gcc.json

### PR DESCRIPTION
**Pull request by orpharion**
Previous dependencies no longer in msys repo

### CODE REVIEW

**Comment by pratikpc** [comment]
Does Scoop actually support zstd files?

I thought it does not

See also https://github.com/lukesampson/scoop/issues/3990

**Comment by orpharion** [comment]
It did download and build correctly

**Comment by Vektorweg** [comment]
> It did download and build correctly

It silently failed to unpack the zst. 

GCC itself doesn't depend on the listed dependencies, but programs to be compiled with GCC might expect that you have these.

**Comment by chawyehsu** [comment]
duplicate of #1761

**Pull request closed without merging**
