### PR TITLE
srvman: Fix download url

### PR DESCRIPTION
**Pull request by brandon93s**

### CODE REVIEW

**Comment by brandon93s** [comment]
> Add Description
> Add License

Trying to restore download functionality, no sense in blocking a fix to add those to an existing manifest.

> Why not autoupdate?
> That number after getfile is random?
Yes. It has also been at 1.0 for quite a while --- not actively changing.

**Comment by Ash258** [comment]
Then why not add some regex like `getfile/(?<id>[\\d]+)/....7z` and autoupdate with `$matchId/...7z`

**Comment by brandon93s** [comment]
It's been 1.0 since the manifest was added in 2016: 

https://github.com/lukesampson/scoop/pull/1155/files

May be better off just removing the checkver. Thoughts?

**Comment by r15ch13** [comment]
https://github.com/ScoopInstaller/Main/pull/77

**Pull request merged**
