### PR TITLE
r|rtools: Update to 4.2.x

### LINKED ISSUE #3532: [Bug] scoop install r and rstudio
#### Current Behavior

```
scoop install r
# or:
scoop install rstudio

Installing 'r' (4.1.3) [64bit]
The remote server returned an error: (404) Not found.
URL https://cloud.r-project.org/bin/windows/base/R-4.1.3-win.exe is not valid
```

#### Expected Behavior
Installation of newest version of R or Rstudio

### System details

**Windows version: 10

**OS architecture:** 64 bit

### LINKED ISSUE #3544: r@4.1.3: download via aria2 failed
Looks like r no longer has this binary available for download.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://cloud.r-project.org/bin/windows/base/R-4.1.3-win.exe
    referer=https://cloud.r-project.org/bin/windows/base/
    dir=C:\SDE\Scoop\cache
    out=r#4.1.3#https_cloud.r-project.org_bin_windows_base_R-4.1.3-win.exe

#### Scoop Configuration

```json
//# Your configuration here
```

### PR DESCRIPTION
**Pull request by eatonphil**
~The existing 4.1.3-win.exe link doesn't work (try it). This is the correct one.~

Update R and RTools to 4.2.x

- Closes #3532
- Closes #3544

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Modify autoupdate too

**Comment by justanothergithubber** [comment]
The latest version of R is 4.2.0, Vigorous Calisthenics

Would it be possible to update R to 4.2.0 instead?

**Comment by rashil2000** [comment]
Yes, please update it

**Comment by tech189** [comment]
We also need to fix hash extraction, the URL has changed to this for the latest version: https://cran.r-project.org/bin/windows/base/md5sum.R-4.2.0.txt

**Comment by tech189** [comment]
Here's my updated manifest with fixed checkver and hashes, plus removal of 32bit as it is no longer included.

```json
{
    "version": "4.2.0",
    "description": "A free software environment for statistical computing and graphics.",
    "homepage": "https://www.r-project.org",
    "license": "GPL-2.0-only",
    "notes": [
        "For source packages installation, please install 'rtools'.",
        "",
        "You'll need to type 'r.ps1' or 'r.cmd' to run R, because in Powershell 'r' runs the last command. Alternatively 'rterm' can be used to start the interactive R terminal session.",
        "",
        "You can remove Powershell's 'r' command with:",
        "    rm alias:\\r",
        "",
        "... but this only affects your current session: if you'd like to remove it for all future sessions you need to add the command above to your Powershell profile.",
        "",
        "Annoying, right?! You might want to check out Pshazz (scoop install pshazz)--this has a plugin to remove some crazy aliases from Powershell, as well as many other improvements."
    ],
    "url": "https://cloud.r-project.org/bin/windows/base/R-4.2.0-win.exe",
    "hash": "md5:7f73761dfaab031f1cbb25530c8dba9c",
    "innosetup": true,
    "architecture": {
        "64bit": {
            "bin": [
                "bin\\x64\\R.exe",
                "bin\\x64\\Rcmd.exe",
                "bin\\x64\\Rgui.exe",
                "bin\\x64\\Rscript.exe",
                "bin\\x64\\Rterm.exe"
            ],
            "shortcuts": [
                [
                    "bin\\x64\\Rgui.exe",
                    "R"
                ]
            ]
        }
    },
    "installer": {
        "script": [
            "Remove-Item \"$dir\\bin\\R,*.exe\" -Force",
            "Copy-Item \"$dir\\bin\\R.exe\" \"$dir\\bin\\Rscript.exe\"",
            "if (Test-Path (appdir 'rtools' $global)) {",
            "   $renvloc = \"$dir\\etc\\Renviron.site\"",
            "   $rtoolsloc = versiondir 'rtools' (current_version 'rtools' $global) $global",
            "   if (Test-Path $renvloc) {",
            "       $renv = Get-Content $renvloc -Encoding ASCII",
            "   } else {",
            "       $renv = @()",
            "   }",
            "   $rtoolspath = \"$rtoolsloc\\usr\\bin\"",
            "   if ($renv -cmatch 'PATH=') {",
            "       $renv = $renv -replace 'PATH=\"(.*)', ('PATH=\"' + $rtoolspath + ';$1')",
            "   } else {",
            "       $renv += \"`r`nPATH=\", '\"', $rtoolspath, ';${PATH}\"' -join ''",
            "   }",
            "   $renv | Set-Content $renvloc -Encoding ASCII",
            "}"
        ]
    },
    "checkver": {
        "url": "https://cloud.r-project.org/bin/windows/base/",
        "regex": "R-([\\d.]+)"
    },
    "autoupdate": {
        "url": "https://cloud.r-project.org/bin/windows/base/R-$version-win.exe",
        "hash": {
            "url": "$baseurl/md5sum.R-$version.txt"
        }
    }
}

```

**Comment by eatonphil** [comment]
Ok, updated with your version. Thanks!

**Comment by niheaven** [comment]
Move R413 to versions and add note that 4.2.0 needs UCRT, then update the manifest.

**Review by Ganesha2282882 — APPROVED** [review]
Looks good to me.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
