### PR TITLE
gping: Add version 0.1.7

### PR DESCRIPTION
**Pull request by wenmin92**
[gping](https://github.com/orf/gping), is a ping tool with graph.

See https://github.com/orf/gping/issues/106

### CODE REVIEW

**Comment by rasa** [comment]
Current version is `v1.0.1-post2` which fails thr internal github version regex.

**Comment by wenmin92** [comment]
> Current version is `v1.0.1-post2` which fails thr internal github version regex.

Thanks, will use explict checkver url and regex to fix it.

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
