### PR TITLE
spicetify-cli: Add version 2.9.2

### PR DESCRIPTION
**Pull request by sitiom**
Closes https://github.com/ScoopInstaller/Extras/issues/7962

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
/verify

Any persist?

**Comment by sitiom** [comment]
> Any persist?

None. The config folder is located at `~/.spicetify`

**Comment by rashil2000** [comment]
Okay, please rename the file to spicetify.json. The CLI  is implied.

**Comment by sitiom** [comment]
The name of the package on other package managers is called `spicetify-cli` ([See here](https://spicetify.app/docs/getting-started/advanced-installation)). The chocolatey package is even renamed to [`spicetify-cli`](https://community.chocolatey.org/packages/spicetify-cli) to match the naming.

**Pull request merged**
