### PR TITLE
avrdude: Add version 6.3-20171130

### PR DESCRIPTION
**Pull request by omerakgoz34**
AVRDUDE is software for programming Atmel AVR Microcontrollers
https://osdn.net/projects/avrdude

### CODE REVIEW

**Comment by chawyehsu** [comment]
Please try to add checkver and autoupdate, you can use https://osdn.net/projects/avrdude/releases/rss to find the version number.

**Comment by omerakgoz34** [comment]
I don't think any new version will be added anymore and I guess it's not possible to do in this RSS

**Review by rasa — APPROVED** [review]

**Comment by rasa** [comment]
Installed fine locally.

**Pull request merged**
