### PR TITLE
castxml: Add version 0.4.4

### PR DESCRIPTION
**Pull request by KevinGliewe**
Closes https://github.com/ScoopInstaller/Main/issues/3318

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

**Nodes:**
 - No need for persistence
 - I am not sure it is possible to implement `autoupdate`, since the download url contains a GUID.
 - It is only 64 bit.

### CODE REVIEW

**Comment by rashil2000** [comment]
It is possible to implement autoupdate. You will have to write a small script to follow links. See these examples:

- https://github.com/ScoopInstaller/Extras/blob/master/bucket/xmind.json
- https://github.com/ScoopInstaller/Extras/blob/master/bucket/inkscape.json
- https://github.com/ScoopInstaller/Extras/blob/master/bucket/ultravnc.json

**Comment by KevinGliewe** [comment]
Is there a way to use the hash from checkver?
Injecting it using `"hash": "sha512:$matchHash"` does seem to trigger the schematic validation.

https://github.com/KevinGliewe/Scoop-Main/blob/b9f612a0e1a2113a5947510ab2a98abaeb9c41f2/bucket/castxml.json#L27

**Comment by rashil2000** [comment]
> Is there a way to use the hash from checkver? 

Not currently.

> Injecting it using `"hash": "sha512:$matchHash"` does seem to trigger the schematic validation.

I think we can ignore it for now.

@niheaven what do you think?

**Comment by niheaven** [comment]
The main problem is, we could not use hash from checkver, and `"hash": "sha512:$matchHash"` here doesn't work. Use downloaded file to get hash until this `checkver` mode is added to autoupdate and delete this line.

**Comment by rashil2000** [comment]
Why is "Autoupdate Hash Extraction" showing passed then?

**Comment by niheaven** [comment]
It has `hash` section in au, but doesn't work, scoop downloaded the file and checked hash is correct, then the bot gives an `Autoupdate Hash Extraction` false positive...

**Comment by rashil2000** [comment]
We can construct the URL for hash in checkver, then use that URL and a custom regex in autoupdate.hash

**Comment by niheaven** [comment]
```json
    "checkver": {
        "script": [
            "$folder = Invoke-RestMethod -Uri 'https://data.kitware.com/api/v1/folder?parentType=folder&parentId=57b5de948d777f10f2696370&sort=lowerName&sortdir=-1' |",
            "    Where-Object { $_.name -match 'v\\d+\\.\\d+\\.\\d+' }",
            "$file = Invoke-RestMethod -Uri \"https://data.kitware.com/api/v1/item?folderId=$($folder[0]._id)&name=castxml-windows.zip\"",
            "Write-Output $folder[0].name $file[0]._id"
        ],
        "regex": "v([\\d.]+)\\s(?<fileid>.+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://data.kitware.com/api/v1/item/$matchFileid/download#/castxml-windows.zip",
                "hash": {
                    "url": "https://data.kitware.com/api/v1/item/$matchFileid/files",
                    "regex": "sha512.*$sha512"
                }
            }
        }
    }
```

**Comment by KevinGliewe** [comment]
Thanks for the help!

I committed the changes @niheaven suggested. Looks good now 👍

**Comment by rashil2000** [comment]
No worries.

Btw, as a first time contributor, your manifest was perfect!

**Pull request merged**
