### PR TITLE
rainbow: Add version 1.0.0

### PR DESCRIPTION
**Pull request by wenmin92**
**[rainbow](https://github.com/arsham/rainbow)**

Description: Print text in rainbow pattern.
License: Apache-2.0

Preview:
image

### CODE REVIEW

**Comment by Ash258** [comment]
Rainbow contains from files for checksums... There are no hashes relevant for that release

**Comment by wenmin92** [comment]
> Rainbow contains from files for checksums... There are no hashes relevant for that release

Sorry, I may not understand what you mean, I tested it, there is no problem in obtaining the hash.

**Comment by Ash258** [comment]
A

**Comment by wenmin92** [comment]
Thanks, now I understand.
But that's a typo error, I will create an issue to tell the author to fix this. For now, it not influence the update.

image

**Comment by wenmin92** [comment]
The rainbow author has fixed. See [release](https://github.com/arsham/rainbow/releases).

**Pull request merged**
