### PR TITLE
Update fio to v3.27 

### PR DESCRIPTION
**Pull request by Valinor**
- Update v3.27
- Add autoupdate

### CODE REVIEW

**Comment by Valinor** [comment]
I need some help for this one. Don't understand the error : 

image

Ok, so I check https://github.com/Ash258/Scoop-GithubActions/blob/main/Entrypoint.ps1 : 

image

This is ok so next : 
image

Hum, never see Hash done in log... So : repeat the command manually : 

image

Ok for me....

See diff to be sure :  

image
 

Really, I don't get it...

**Comment by rashil2000** [comment]
See my comment here https://github.com/ScoopInstaller/Main/pull/2847#issuecomment-955915603

**Comment by Valinor** [comment]
No more important, see #2847

**Pull request closed without merging**
