### PR TITLE
edgedriver: Update to version 82.0.449.0 (Chromium)

### PR DESCRIPTION
**Pull request by niheaven**
Legacy version has been moved to `versions`.

### CODE REVIEW

**Comment by Ash258** [comment]
Edge with chromimum is still in development and available for insiders (https://www.microsoftedgeinsider.com/en-us/) I do not think this is good move to replace current version with future version.

**Comment by niheaven** [comment]
So I put legacy version in `version`, and add description here to figure out it is Chromium version.

I'll add a note in this manifest.

**Comment by Ash258** [comment]
Yeah, but this should be merged as soon as chromium edge is realease globally as stable for all users and normal edge is retired.

**Comment by niheaven** [comment]
@Ash258 Edge is now stable: https://www.microsoft.com/en-us/edge

**Pull request merged**
