### PR TITLE
haxe, neko: fix env path

### PR DESCRIPTION
**Pull request by linsui**
fix https://github.com/lukesampson/scoop/issues/3808

### CODE REVIEW

**Comment by linsui** [comment]
Should we remove haxe-dev? It only matches pre-release versions which are sometimes even older than latest release versions.

**Comment by rishavs** [comment]
Can we tag the reviewers? I need to install Haxe and would love to do it via scoop.

**Comment by rishavs** [comment]
Thank you! <3

**Comment by rishavs** [comment]
@linsui This did not fix the original issue #3808

Haxelib still cannot find neko.dll

**Comment by linsui** [comment]
It works for me. Did you reinstall neko?

**Comment by rishavs** [comment]
i didn't. I will try right away and report back

**Comment by rishavs** [comment]
ok. Can confirm that its working fine. Thanks!

**Pull request merged**
