### PR TITLE
Update symfony-cli.json

### PR DESCRIPTION
**Pull request by BahmanMD**
Fix https://github.com/symfony-cli/symfony-cli/issues/36

And update from https://github.com/symfony-cli/scoop-bucket/blob/main/symfony-cli.json

### CODE REVIEW

**Comment by rashil2000** [comment]
What is the difference between https://github.com/symfony/cli/releases and https://github.com/symfony-cli/symfony-cli/releases? I see that https://github.com/symfony/cli/releases still gets very regular updates.

**Comment by chapterjason** [comment]
@rashil2000 https://github.com/symfony/cli/releases are releases from the version 4 which was closed source https://github.com/symfony-cli/symfony-cli/releases is the open source version which started with version 5.

**Comment by BahmanMD** [comment]
Thank you @chapterjason 
And v4 is not maintained anymore

**Pull request merged**
