### PR TITLE
chore: Update some very old apps

### PR DESCRIPTION
**Pull request by rashil2000**
Closes #XXXX

Relates to #XXXX

### CODE REVIEW

**Review by issaclin32 — APPROVED** [review]

**Comment by niheaven** [comment]
Why download such a big file (~90MB) while I only need `grep` or `sed`?

**Comment by rashil2000** [comment]
What's the alternative then?

Otherwise the apps will remain on very old versions.

**Comment by niheaven** [comment]
Take them from Chocolatey:

https://community.chocolatey.org/packages/sed Download: https://packages.chocolatey.org/sed.4.8.nupkg

https://community.chocolatey.org/packages/grep Download: https://packages.chocolatey.org/grep.3.7.nupkg

**Comment by rashil2000** [comment]
Okay, will make PR

**Comment by niheaven** [comment]
You could get `make` from Chocolatey, too.

**Comment by rashil2000** [comment]
Make source is standalone, small package, I don't think it's required

**Comment by niheaven** [comment]
If the source is SF, sha1 could be extracted from webpage, and it sounds good.

Chocolatey's file has native sha256, extracted by `$sha256.*?$basename` (this should works).

**Comment by niheaven** [comment]
The PR https://github.com/ScoopInstaller/Scoop/pull/3249 tries to use Chocolatey as distribution server and checkver on it. Maybe it is worth being merged.

**Comment by rashil2000** [comment]
Oh, that looks interesting, didn't know about it 🚀

**Comment by rasa** [comment]
We could have a process unzip https://nuwen.net/files/mingw/components-18.0.7z and push the components we want into https://github.com/ScoopInstaller/Binary .

**Comment by rashil2000** [comment]
But how will they autoupdate?

**Pull request merged**
