### PR TITLE
vcpkg@2024.01.12: add git repo integration for versioning

### LINKED ISSUE #4625: [Bug]: vcpkg fails to install package because vcpkg is not a git repo
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

vcpkg

### Expected/Current Behaviour

vcpkg fails to install a package because it relies on its root directory being a git repository https://github.com/microsoft/vcpkg/issues/22582#issuecomment-1015043685. I expect vcpkg to be able to install the package.

```
-- Running vcpkg install
Error: while checking out port boost-program-options with git tree 306ab169b6f177e71d82cb08c77a8629337a1b6a
Error: Failed to tar port directory
error: tar failed with exit code: (128).
fatal: not a git repository: 'C:\Users\Mark\scoop\apps\vcpkg\current\.git'

-- Running vcpkg install - failed
CMake Error at C:/Users/Mark/scoop/apps/vcpkg/current/scripts/buildsystems/vcpkg.cmake:886 (message):
  vcpkg install failed.  See logs for more information:
  C:\Repositories\bethesda\Champollion\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Users/Mark/scoop/apps/cmake/3.26.2/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:16 (project)


-- Configuring incomplete, errors occurred!
```

### Steps to Reproduce

```console
scoop install git cmake vcpkg

git clone git@github.com:Orvid/Champollion.git
cd Champollion
cmake -DCMAKE_BUILD_TYPE=Release -B build -S . -DCMAKE_TOOLCHAIN_FILE=C:\Users\Mark\scoop\apps\vcpkg\current\scripts\buildsystems\vcpkg.cmake
```

### Possible Solution

I did not look into why exactly vcpkg needs a git repo. However, the following did manage to get the build I needed to work:

```
cd C:\Users\Mark\scoop\apps\vcpkg\current\
git init
git remote add origin git@github.com:microsoft/vcpkg.git
git fetch origin
git symbolic-ref HEAD refs/heads/2023.02.24
```

That is probably hacky. If it's possible to specify in the manifest that scoop should use git to clone the repo instead of downloading a zip, that would be ideal.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'dorado' bucket:
65e1af7e (HEAD -> master, origin/master, origin/HEAD) zap: Update to version 0.7.7-beta

'extras' bucket:
61554af46 (HEAD -> master, origin/master, origin/HEAD) todolist: Update to version 8

'java' bucket:
b94e23bd (HEAD -> master, origin/master, origin/HEAD) openjdk21: Update to version 21-16-ea

'main' bucket:
f5fbf9b31 (HEAD -> master, origin/master, origin/HEAD) slang: Update to version 0.27.5

'nirsoft' bucket:
28db834 (HEAD -> master, origin/master, origin/HEAD) Excluded two pad files that require a password. They need to be updated manually.

'nonportable' bucket:
edd19da (HEAD -> master, origin/master, origin/HEAD) 10x-np: Update to version 1.0.6

'versions' bucket:
1c6be06a1 (HEAD -> master, origin/master, origin/HEAD) vlc-nightly: Update to version 20230403
```

### Scoop Config

```console
last_update         aria2-enabled scoop_branch scoop_repo
-----------         ------------- ------------ ----------
2023-04-02 22:08:51         False master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by shad0wshayd3**
vcpkg's versioning scheme uses commit hashes from vcpkg's GitHub repo as a baseline to determine the minimum versions of all package dependencies for a project. Packages can optionally be constrained to a minimum version higher than the baseline or be overridden to specific versions below the baseline. It expects VCPKG_ROOT (the vcpkg install directory) to be a clone of the vcpkg GitHub repo in order to facilitate this.

This PR adds a `pre_install` step to vcpkg's scoop manifest that initializes the vcpkg installation folder as a clone of the vcpkg GitHub repo. The actual `.git` folder is stored persistently using `--seperate-git-dir` the first time vcpkg is installed or updated with the new manifest. Subsequent runs update a plaintext .git file to point to the persistent folder per git spec, to cut down on time spent fetching between updates. The `.git` folder is appropriately cleared when running `uninstall -p`. `autoupdate` has been adjusted accordingly to ensure that the correct tag has been checked out after an update.

Closes #4625

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
- Adding `depends` on git is not a good idea (because people might install git from sources other than Scoop). What can be done here instead is: you can add a check for the git command (if it's available - if not, print a note and exit).
- You should put all $dir/$persist_dir variables in doubles quotes, and use `\\` instead of `/`.

**Comment by shad0wshayd3** [comment]
I changed the git `depends` to a `suggest` and wrapped the `pre_install` script with a `Get-Command` check to see if Git is available, if not it just mentions that it's being skipped. Also applied the changes to the paths.

**Pull request merged**
