### PR TITLE
ffmpeg: use BtbN builds (static/shared/nightly/vulkan)

### LINKED ISSUE #1110: ffmpeg-git-shared(or nightly-shared)
https://ffmpeg.zeranoe.com/builds/
There are 3 different versions of ffmpeg available on Scoop

1. ffmpeg-release-static(as ffmpeg)
2. ffmpeg-release-shared(as ffmpeg-shared)
3. ffmpeg-git-static(as ffmpeg-nightly)

But ffmpeg-git-shared (or nightly-shared) is not. Is there any reason for that ?

### LINKED ISSUE #1379: Deprecate ffmpeg manifests until alternative builds are provided
Builds provided by Zeranoe will no longer be provided on 18.09.2020

image

### LINKED ISSUE #1406: ffmpeg@4.3.1: download via aria2 failed
ERROR Download failed! (Error 3) Resource was not found
ERROR https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip
    referer=https://ffmpeg.zeranoe.com/builds/win64/static/
    dir=D:\Software\Scoop\cache
    out=ffmpeg#4.3.1#https_ffmpeg.zeranoe.com_builds_win64_static_ffmpeg-4.3.1-win64-static.zip

ERROR & 'D:\Software\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Software\Scoop\cache\ffmpeg.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6872 --continue

### LINKED ISSUE #1415: ffmpeg@4.3.1: Download failed
Scoop will not install ffmpeg 4.3.1 due to a 404 error. I verified using my normal web browser that indeed this results in a 404, and the same problem occurs with Tor Browser (so it is not my ISP blocking this file).

```PS > scoop update
Updating Scoop...
Updating 'extras' bucket...
Updating 'main' bucket...
Scoop was updated successfully!
PS > scoop install ffmpeg
Installing 'ffmpeg' (4.3.1) [64bit]
The remote server returned an error: (404) Not Found.
URL https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip is not valid
PS C:\Users\sjmur>
```

### LINKED ISSUE #1445: a ffmpeg refresh needed
Since the shutdown of zeranoe builds, scoop ffmpeg unusable now.
Note there are already solutions  #1424 #1425 , and needed to pick one.

1 https://github.com/BtbN/FFmpeg-Builds/releases	

2 https://www.gyan.dev/ffmpeg/builds/packages/

3 https://ottverse.com/ffmpeg-builds/

4 https://github.com/AnimMouse/ffmpeg-stable-autobuild/releases

1 and 2 are from official ffmpeg.org download page, 4 is stable and has win32 builds while others only 64bit, 1 is nightly by now, 3 weekly git , 2 both twice-weekly git and stable releases.

### LINKED ISSUE #1459: ffmpeg@4.3.1: download via aria2 failed

### LINKED ISSUE #1477: ffmpeg@4.3.1: download via aria2 failed
C:\Users\Administrator>scoop install ffmpeg
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'ffmpeg' (4.3.1) [64bit]
Starting download with aria2 ...
Download: 10/06 08:38:36 [ERROR] CUID#8 - Download aborted. URI=https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip
Download:   -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: 鏃犳硶杩炴帴鍒版湰鍦板畨鍏ㄦ満鏋?
Download: (80090304)
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c05ada|ERR |       0B/s|D:/app/Scoop/cache/ffmpeg#4.3.1#https_ffmpeg.zeranoe.com_builds_win64_static_ffmpeg-4.3.1-win64-static.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip
    referer=https://ffmpeg.zeranoe.com/builds/win64/static/
    dir=D:\app\Scoop\cache
    out=ffmpeg#4.3.1#https_ffmpeg.zeranoe.com_builds_win64_static_ffmpeg-4.3.1-win64-static.zip

ERROR & 'D:\app\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\app\Scoop\cache\ffmpeg.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=10976 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ffmpeg%404.3.1%3a+download+via+aria2+failed

********************************************
https://ffmpeg.zeranoe.com can't access.

### PR DESCRIPTION
**Pull request by wstein**
FFmpeg update, to use the builds from https://github.com/BtbN/FFmpeg-Builds/releases:

variants handled by this commit:
ffmpeg
ffmpeg-shared
ffmpeg-nightly (shared and vulkan!)

- Closes #1110 
- Closes #1379 
- Closes #1406 
- Closes #1415 
- Closes #1445 
- Closes #1459 
- Closes #1477

### CODE REVIEW

**Review by chawyehsu — APPROVED** [review]

**Comment by BtbN** [comment]
If you want to be sure those URLs work for longer than 14 days, make sure to use the last build of the month.
Those are kept for one year. Otherwise only the last 14 daily builds are kept around: https://github.com/BtbN/FFmpeg-Builds/blob/master/util/prunetags.sh

**Comment by chawyehsu** [comment]
@BtbN My concern is that those two stable versions (ffmpeg, ffmpeg-shared) can't be updated to use the last build because the version number doesn't change and then Autoupdate will not perform.

And why the build number of the two stable versions doesn't change between builds?

**Comment by BtbN** [comment]
There is no build number. The number is the number of commits since the N tag, which is how ffmpeg versions itself.

**Comment by chawyehsu** [comment]
Ok, I see. So the number `20` should be considered a part of the version number.

**Comment by wstein** [comment]
Adding 20 to the Version would mean every day a new stable version?

**Comment by BtbN** [comment]
Not sure what you mean.
The logic to only build when changes happened would be way too complex to implement, and it would also make it hard to find the latest build from the stable branch, since it could be several days or even weeks ago and you then have to go digging in old releases. Plus, it could be pruned away if no commits happen in 14 days.
Just building it every day is way easier.
Additionally, dependencies might be updated, which result in no change in the version number whatsoever.

**Comment by chawyehsu** [comment]
> Adding 20 to the Version would mean every day a new stable version?

If I understand correctly, only new commits to the `release/xx` branch can change the commits number `20`.

Adding commits number can't ensure to use the last build yet.

The problem is if there is no new commits to the release branch, the version number would still be `4.3.1-20`. Download URLs in the manifest will not be updated when the version number does not change, but the old tags will be deleted after 14 days which makes URLs unavailable.

**Comment by wstein** [comment]
Ok, not daily, but frequently:
- 2020-09-27: ffmpeg-n4.3.1-18
- 2020-09-30: ffmpeg-n4.3.1-19
- 2020-10-02: ffmpeg-n4.3.1-20

That is a bout a week. I would not expect, getting 3 Updates a week on a stable branch.

**Comment by BtbN** [comment]
The download URL changes with every build, because the tag name is part of the URL, and the date + time is in there.
So you can update the URL to point to a newer build of the same commit.

And I really don't get your complaint about commits getting backported to stable branches. That's the whole point of stable branches to begin with, backports of fixes only, no new features.
Would you rather have bugs remain unfixed?

**Comment by wstein** [comment]
Don't get me wrong, backports are OK, but I am wondering about the frequency. Are this all urgent hotfixes?

**Comment by BtbN** [comment]
Just look at the commit log if you want to know what got backported http://git.videolan.org/?p=ffmpeg.git;a=shortlog;h=refs/heads/release/4.3
I don't see how 3 commits in one month are in any way critical. Before new micro releases, hundreds of commits are backported even.

**Comment by wstein** [comment]
Ok, I see, thanks.

**Comment by slaughtering** [comment]
Finally. You guys' work rock.

**Comment by Boscop** [comment]
@BtbN What's the difference between your builds and https://github.com/AnimMouse/ffmpeg-autobuild ? :)

**Comment by BtbN** [comment]
I have never heard of or seen those builds, so I can't really tell you.
fdk-aac has a questionable license, so distributing it with GPLed software is questionable at best.

**Comment by Boscop** [comment]
@BtbN What's questionable about its license? Does it not allow distribution?

**Comment by BtbN** [comment]
It is not GPL compatible, and the GPL does not allow distribution alongside non-GPL-compatible code.

**Pull request merged**
