### PR TITLE
k3sup: Add version 0.11.0

### PR DESCRIPTION
**Pull request by wenmin92**
close https://github.com/ScoopInstaller/Main/issues/2690

### CODE REVIEW

**Comment by wenmin92** [comment]
I didn't use this tool either, simply because I happened to see the [request](https://github.com/ScoopInstaller/Main/issues/2690), so I simply submitted it. My original idea was to have someone use it and submit an issue, and then improve it accordingly. I'm sorry for this hasty action.

Maybe we should consult with people who have used it (@paalkr)

**Comment by issaclin32** [comment]
> My original idea was to have someone use it and submit an issue, and then improve it accordingly. I'm sorry for this hasty action.

No worries. I do not think the manifest needs to be "perfect" either.
I just want to avoid some crucial problems that might affect users who uses and updates the package using *Scoop*.

**Comment by issaclin32** [comment]
The config file is located at `%userprofile%\.k3sup`. Therefore *persist* is not needed.

**Pull request merged**
