### PR TITLE
hledger: Add version 1.27

### LINKED ISSUE #1975: [Request] Add hledger
Easy-to-use command-line/curses/web plaintext accounting tool; a modern and largely compatible Haskell rewrite of Ledger.

Project Link: https://github.com/simonmichael/hledger
Releases Link: https://github.com/simonmichael/hledger/releases/

There's a [personal bucket](https://github.com/earnestma/scoop-earne) I found that has this program, however it would be nice to add it to the main repository as it's a standalone binary.

### PR DESCRIPTION
**Pull request by ratsclub**
Close #1975

### CODE REVIEW

**Comment by ratsclub** [comment]
I'm not sure what I should do to pass the other test.

**Comment by CryoRenegade** [comment]
Add a newline at the end of the file.

**Comment by ratsclub** [comment]
Thanks you for your fast reply.

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
