### PR TITLE
Add WinSW

### PR DESCRIPTION
**Pull request by SonaliBendre**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SonaliBendre** [comment]
https://github.com/winsw/winsw/releases/download/v3.0.0-alpha.10/WinSW-net461.exe is more smaller file, can we use that? will it work in x86 system? I don't have x86 machine to test. Also they provide zip file

**Comment by rashil2000** [comment]
Don't add alpha version. Use the stable release.

Use the x86 and x64 exe files which they provide, they are self contained.

**Comment by rashil2000** [comment]
Use sha256 (no prefix required).

**Pull request merged**
