### PR TITLE
MAVEN: Update download URL

### PR DESCRIPTION
**Pull request by delassio**
- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Why do this change?

**Comment by delassio** [comment]
> Why do this change?

changing the download server from archive to dlcdn server

**Comment by maiq123** [comment]
The dlcdn server doesn't have older versions. Trying to install maven@3.6.0 but dlcdn doesn't have that. This change has made it difficult to install older versions of maven. Can we have a new feature of 'old_url' in the manifest to specify some and old url and if the package is not available in curren 'url' than it can also check the old url for the version?

**Pull request merged**
