### PR TITLE
lynx: update openssl url and hash

### PR DESCRIPTION
**Pull request by rgibbons-dev**
lynx install was failing previously,
`URL https://slproweb.com/download/Win32OpenSSL_Light-1_1_1j.exe is not valid`

installs as expected after change

### CODE REVIEW

**Comment by igitur** [comment]
@rgibbons-dev Can you please rebase and fix the conflict?

**Comment by rgibbons-dev** [comment]
oh my
think i'm a little out of my depth here

**Comment by igitur** [comment]
> oh my
> think i'm a little out of my depth here

No worries. I created a new, simpler PR that does the same at https://github.com/ScoopInstaller/Main/pull/2542 . I think you can close this one. Now we just hope they merge it soon. It seems they have a backlog.

**Comment by igitur** [comment]
@rgibbons-dev lynx should be fixed now.

**Pull request closed without merging**
