### PR TITLE
Add beeflang-nightly to scoop

### PR DESCRIPTION
**Pull request by mundusnine**
Tested autoupdate and installation.

### CODE REVIEW

**Comment by mundusnine** [comment]
Just fixed issues with checkver regex to replace adequatly.

**Comment by mundusnine** [comment]
@rasa  just compared both hashes and they are the same on my end... is there a way to see the output of the checks ? Can pushing after the pull request was created be an issue, were the test only takes the first commit ?

**Comment by niheaven** [comment]
Please move this PR to https://github.com/ScoopInstaller/Versions/

**Pull request closed without merging**
