### PR TITLE
add tool: wincryptsshagent

### PR DESCRIPTION
**Pull request by acuteaura**
References: https://github.com/buptczq/WinCryptSSHAgent

### CODE REVIEW

**Comment by acuteaura** [comment]
Let me know if "has a tray icon" already counts as GUI, I can throw this into extras too.

**Comment by pratikpc** [comment]
You can use a # at the end of the URL to rename it  @CryoRenegade 

Check https://github.com/ScoopInstaller/Main/blob/master/bucket/aws-copilot.json

**Comment by acuteaura** [comment]
Getting this out of my open PR listing.

**Pull request closed without merging**
