### PR TITLE
resvg: Add version 0.25.0

### PR DESCRIPTION
**Pull request by brian6932**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
What's the function of each of these utilities?
image

Shouldn't they be included too?

**Comment by brian6932** [comment]
@rashil2000 a lot of those are either gui, or seperate programs that use the library, the cli util is the current one

**Comment by brian6932** [comment]
usvg is a cli util, optionally you could make a package for that in main

**Comment by rashil2000** [comment]
You can add multiple URLs in a manifest and make bins for them, see https://github.com/ScoopInstaller/Versions/blob/master/bucket/gcc-msys.json for example.

**Comment by rashil2000** [comment]
I think we should add viewsvg (create a bin for it) and resvg-explorer-extension (no need for bin here) too

**Comment by brian6932** [comment]
@rashil2000 Main is a scoop bucket for developer/CLI programs, viewsvg, and resvg-explorer-extension are gui and codecs for gui programs respectively, is this wise?
Maybe a separate manifest should be made for viewsvg and resvg-explorer-extension on `extras` or `versions`?

**Comment by rashil2000** [comment]
I think it's fine: the primary app is resvg, which is CLI. Its helper apps can be GUI. (for example, main/7zip)

**Comment by niheaven** [comment]
viewsvg is 32.8MB while resvg is 1.11MB and usvg is 779kB. Put it in extras IMO.

**Pull request merged**
