### PR TITLE
uutils-coreutils@0.0.23: Update homepage

### PR DESCRIPTION
**Pull request by YDX-2147483647**
This is a trivial PR. It has a dedicated homepage now, which should be preferred over the repo.

Relates to #5743

Relates to https://github.com/uutils/coreutils/pull/2897

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by YDX-2147483647** [comment]
It fails because [release artifacts for v0.0.24 and v0.0.25 are missing · Issue #5929 · uutils/coreutils](https://github.com/uutils/coreutils/issues/5929), so let's just wait.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
