### PR TITLE
jfrog: Update to version 1.44.0

### LINKED ISSUE #1969: JFrog CLI Frozen at 1.43.2
The JFrog CLI is not autoupdating and is now stuck at 1.43.2. The checkver URL is valid but seems to stop at v 1.44.0. Latest is 1.45.2. PR #1821 seems to be a fix but is waiting on review.

### PR DESCRIPTION
**Pull request by nixxo**
address issue in #150

Close #1969

### CODE REVIEW

**Review by pratikpc — CHANGES_REQUESTED** [review]
Could you also change checkver to GitHub?
```json
    "checkver": {
        "github": "https://github.com/jfrog/jfrog-cli"
    },
```
Using a GitHub checkver is usually more popular with most Scoop projects and usually less prone to breakage.

**Comment by nixxo** [comment]
I think it's better to check the version in the same repository where the build is available.
On github is only available the source code and not the build package.

I don't know the release schedule of the jfrog project and I don't know if they release the source code and the build at the same time or maybe they release the source code before and the nthe build server creates the release... etc.

So I think it's better to check the version in the same place where you actually download the package because it gives you exactly the latest available package to download.

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
