### PR TITLE
payload-dumper-go: Add version 1.2.2

### LINKED ISSUE #4254: [Request]: Add payload-dumper-go
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

payload-dumper-go

### Description

an android OTA payload dumper written in Go

### Homepage

https://github.com/ssut/payload-dumper-go

### Download Link(s)

https://github.com/ssut/payload-dumper-go/releases

### Some Indication of Popularity/Repute

 872 stars, 83 forks

### PR DESCRIPTION
**Pull request by soenggam**
Closes #4254 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Should we call it `android-payload-dumper` instead of `payload-dumper-go`?

**Comment by soenggam** [comment]
> Should we call it `android-payload-dumper` instead of `payload-dumper-go`?

There are many other android payload dump implementations on GitHub
https://github.com/search?q=payload+dumper

**Comment by rashil2000** [comment]
Still, we need something in the name to tell that this application is related to android stuff

**Pull request merged**
