### PR TITLE
update sudo

### LINKED ISSUE #747: sudo unmaintained
sudo does not work with powershell core. 
See 
- https://github.com/lukesampson/psutils/pull/29
- https://github.com/ScoopInstaller/Main/blob/master/bucket/sudo.json

There is a lot of dependencies using `sudo`, seems that `psutils` was last updated 2 years ago: https://github.com/lukesampson/psutils

I see a few option

- fork `psutils` into ScoopInstaller
- accept another `psutils` fork where `sudo` at least is fixed.
  - see https://github.com/lukesampson/psutils/pull/32
- switch to `gsudo` ?

### PR DESCRIPTION
**Pull request by casz**
fixes #747

### CODE REVIEW

**Comment by casz** [comment]
@Ash258 clearly psutils is not being actively maintained last commit was two years ago and there are no responses on https://github.com/lukesampson/psutils

**Comment by casz** [comment]
For those who actively uses powershell core it would be nice if sudo was updated.

**Comment by h404bi** [comment]
I don't think it's a good idea to change it to a fork repository.

**Comment by casz** [comment]
Not likely it will be merged into the main repo 🙄

**Comment by h404bi** [comment]
> Not likely it will be merged into the original repo 🙄

I'll do the pull-request review of sudo.

**Comment by casz** [comment]
👉 https://github.com/lukesampson/psutils/pull/32

**Comment by casz** [comment]
Updated to use original repo, thanks to @h404bi for merging psutils :)

**Comment by linsui** [comment]
See https://github.com/ScoopInstaller/Main/commit/5e33474356f9c911cb6d6776cf254f43891cb0c8

**Comment by casz** [comment]
That automation ❤️

**Comment by casz** [comment]
@Ash258 @h404bi as a contributor it can be hard to know who has write access if you took offence with me forking the repo I am sorry.

Many thanks for merging my pull request @h404bi 🙇

**Pull request closed without merging**
