### PR TITLE
mosdns: Add version 3.9.0

### PR DESCRIPTION
**Pull request by ShaoqiangLu**
Add [mosdns](https://github.com/IrineSistiana/mosdns), a DNS forwarder.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Link to English documentation?

**Comment by ShaoqiangLu** [comment]
> Link to English documentation?

I'm afraid that there is no English doc but only English help info.
image

Does this bucket only accept software with English doc?

**Comment by ShaoqiangLu** [comment]
Will reopen when there is English doc.

**Pull request closed without merging**
