### PR TITLE
Add Intermodal v0.1.10

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
New update was pushed yesterday that I was unaware of.

**Comment by ThatNerdyPikachu** [comment]
@rasa Fixed.

**Review by rasa — APPROVED** [review]

**Comment by rasa** [comment]
```
intermodal: 0.1.12 (scoop version is 0.1.11) autoupdate available
Forcing autoupdate!
Autoupdating intermodal
Downloading imdl-v0.1.12-x86_64-pc-windows-msvc.zip to compute hashes!
imdl-v0.1.12-x86_64-pc-windows-msvc.zip (1.4 MB) [===========================================================================================================================================] 100%
Computed hash: 86dba0c9426f81284f61443f45e5b804c7718a11aa770aed0855d181a70fda88
Writing updated intermodal manifest
```

**Pull request merged**
