### PR TITLE
gum: Fixed bin to be more accurate with the application name.

### PR DESCRIPTION
**Pull request by Zliced13**
Reason: I am about to implement a package in Scoop called **gum** by [charmbracelet](https://github.com/charmbracelet).

Relates to #4209

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@rashil2000 is this ok with you? Do you know anybody that uses this application?

**Comment by rashil2000** [comment]
Renaming the file would be a breaking change, but renaming the bin should be fine.

**Pull request merged**
