### PR TITLE
Authenticate api requests in script blocks

### PR DESCRIPTION
**Pull request by kazzarin**
Api requests were hitting the rate limit which may be causing issues in the excavator. Added the github token and put it in a try-catch to prevent issues.
[Actions run][1]
<details><summary>Related log</summary>

```
Invoke-WebRequest: 
Line |
   4 |  $releases = $(Invoke-WebRequest $url).Content | ConvertFrom-Json
     |                ~~~~~~~~~~~~~~~~~~~~~~
     | {"message":"API rate limit exceeded for 52.173.12.16. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

ConvertFrom-Json: 
ERROR Could not match version string in 'https://api.github.com/repos/pnpm/pnpm/releases'
Line |
   4 |  $releases = $(Invoke-WebRequest $url).Content | ConvertFrom-Json
     |                                                  ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
```

</details>

Also, pnpm is failing to update because it is trying to update to the prerelease version. Filtered the prerelease versions for both pnpm and pester.
[Actions run][2]
<details><summary>Related log</summary>

```
pnpm: 8.0.0 (scoop version is 7.27.1) autoupdate available
Autoupdating pnpm
Downloading pnpm-win-x64.exe to compute hashes!
VERBOSE: GET with 0-byte payload
VERBOSE: received 5856-byte response of content type application/json
VERBOSE: Content encoding: utf-8
The remote server returned an error: (404) Not Found.
URL https://github.com/pnpm/pnpm/releases/download/v8.0.0/pnpm-win-x64.exe#/pnpm.exe is not valid
ERROR Could not update pnpm, hash for pnpm-win-x64.exe failed!
```

</details>

[1]: https://github.com/ScoopInstaller/Main/actions/runs/4271690036/jobs/7436335757#step:3:561
[2]: https://github.com/ScoopInstaller/Main/actions/runs/4272531020/jobs/7437758443#step:3:590

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
The try-catch shouldn't be required, see https://github.com/ScoopInstaller/Scoop/pull/5407

**Comment by kazzarin** [comment]
@rashil2000 Done. Good to know it's being addressed.

**Pull request merged**
