### PR TITLE
rustup: Update note

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Actually, the note from this manifest should be removed entirely, because MSVC tools are not required for the GNU toolchain

**Comment by b4imetu** [comment]
> Actually, the note from this manifest should be removed entirely, because MSVC tools are not required for the GNU toolchain

🤣So that's it. It can be replaced with other tool dependencies

**Comment by rashil2000** [comment]
What do you mean?

**Comment by b4imetu** [comment]
> What do you mean?

[Link](https://www.reddit.com/r/rust/comments/a63dlt/comment/ebrbi8d/)
I thought rust-gnu was dependent on the installation of MinGW to run, but it turns out that it can be run directly🤣
Never mind. I will delete the notes🤣

**Pull request merged**
