### PR TITLE
yt-dlp: add plugins directory

### PR DESCRIPTION
**Pull request by silver886**
According to [document](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#installing-plugins), there is another path for loading plugins.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by tech189 — COMMENTED** [review]
Thanks for this, does this mean that plugins in future should be stored in `yt_dlp_plugins` but old ones still work if they are located in `ytdlp_plugins`?

If so, we could write a script to move plugins to the new folder.

**Comment by silver886** [comment]
I haven't use old plugins and I'm not sure about that.
However, the plugin I used need to be placed in the new folder and it wouldn't work if be placed in the old directory.

I think we should leave the folder contents as is to avoid any impact to users.
The plugin structure seems different between these two plugin system.
Ref. https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/plugins.py#L138-L171

**Comment by tech189** [comment]
Okay, I see. Isn't `yt_dlp_plugins` the new folder name though? Your PR has `yt-dlp-plugins` instead (with hyphens not underscores).

**Comment by dyphire** [comment]
I'm having this issue and can only manually create the `yt-dlp-plugins` directory now. Hopefully this PR will be merged soon.

**Review by tech189 — APPROVED** [review]

**Pull request merged**
