### PR TITLE
scrcpy: fix shim error

### LINKED ISSUE #4268: [Bug]: scrcpy 1.25 extracted incorrectly
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

scrcpy

### Expected/Current Behaviour

The directory of scrcpy should look like this
image
But with the 1.25 update looks like this
image

### Steps to Reproduce

```console
scoop install scrcpy
Installing 'scrcpy' (1.25) [64bit] from main bucket
Loading scrcpy-win64-v1.25.zip from cache
Checking hash of scrcpy-win64-v1.25.zip ... ok.
Extracting scrcpy-win64-v1.25.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\scrcpy\current => ~\scoop\apps\scrcpy\1.25
Creating shim for 'scrcpy'.
Can't shim 'scrcpy.exe': File doesn't exist.
```

### Possible Solution

extract in another way

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
62dc8ad92 (HEAD -> master, origin/master, origin/HEAD) xampp@8.1.12-0: Fix config and Add setup (#9897)

'java' bucket:
41eebc21 (HEAD -> master, origin/master, origin/HEAD) temurin-nightly-jre: Update to version 20.0.0-29.0.202212230402

'main' bucket:
d57014dab (HEAD -> master, origin/master, origin/HEAD) sonar-scanner: Update to version 4.8.0.2856

'nonportable' bucket:
922cf9d (HEAD -> master, origin/master, origin/HEAD) spotx-np: Update to version 1.6-20221222-81dcb2

'sysinternals' bucket:
3bce1cc (HEAD -> main, origin/main, origin/HEAD) autoruns: Removes /accepteula arg (#3)

'versions' bucket:
710deb33 (HEAD -> master, origin/master, origin/HEAD) firefox-nightly: Update to version 110.0a1.20221223043251
```

### Scoop Config

```console
last_update                       virustotal_api_key                                               scoop_branch scoop_repo
-----------                       ------------------                                               ------------ ----------
2022-12-23T09:30:06.6353291-05:00 bc27ac74690c8f5769e12be6843d3705839e542c06a233b7db45f95ecdf85270 master       https://github.com/ScoopInstalle...
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by Lutra-Fs**
Closes #4268 

Seems like in 1.25 scrcpy is packed in a dir in the zip file

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onsamyj** [comment]
Is there a way to test if there is a folder inside `.zip` or not?

It is a possibility that it would revert to `.zip` file without a folder in the next update, so having a robust solution would be ideal.

**Comment by sitiom** [comment]
> Is there a way to test if there is a folder inside `.zip` or not?
> 
> It is a possibility that it would revert to `.zip` file without a folder in the next update, so having a robust solution would be ideal.

No, publishers should be consistent in how they release their binaries.

**Comment by onsamyj** [comment]
> No, publishers should be consistent in how they release their binaries. If they inconsistently switch from folder to no folder in the next releases, that should be taken issue in their repo.

It can be a one time issue, and next release would go back to `.zip` without folder inside. Should manifest be fixed at all, then?

**Comment by sitiom** [comment]
> It can be a one time issue, and next release would go back to `.zip` without folder inside. Should manifest be fixed at all, then?

Yes, and hopefully they would consistently do it that way on the next releases.

**Comment by onsamyj** [comment]
> Yes, and hopefully they would consistently do it that way on the next releases.

Why not both? It fixed right now so scoop users have a working app, and talk to devs of said app, so they would not break it again.

**Pull request merged**
