### PR TITLE
lame@3.100-20190806: Fix hash

### PR DESCRIPTION
**Pull request by dodorz**

### CODE REVIEW

**Comment by Ash258** [comment]
It is not that hard to open issue with two clicks from terminal.

If you want to fix the hashes manually then provide the reason why the hashes were changed.

- Post regarding this
- Author clarification
- Timeline of github release

**Comment by dodorz** [comment]
How could I know why the hash was changed? I even don't know if it was changed. I just found an error and fixed it.

**Comment by Ash258** [comment]
- Vendors blog post
- File timestamp
- Release page
- Timestamp of hash files
- Stability and credibility of vendor
- Previous issues with hashes and vendor statement on it
	- Their timeframe
	- Process of how binaries are normally rebuild
	- How vendor react to it
- Email to vendor
- New issue regarding it

There are lots of ways how to do it.

**Comment by rasa** [comment]
Superseded.

**Pull request closed without merging**
