### PR TITLE
fix: lf: add lfcd to shims

### LINKED ISSUE #3796: [Request] lf: add lfcd to shims
[lf](https://github.com/gokcehan/lf) [manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/lf.json) should add [lfcd.ps1](https://github.com/gokcehan/lf/blob/master/etc/lfcd.ps1) and/or [lfcd.cmd](https://github.com/gokcehan/lf/blob/master/etc/lfcd.cmd) (there are also versions for other shells) to shims. `lfcd` provides a way to change working directory to the last directory in `lf` on exit. Which is a common [use case](https://github.com/gokcehan/lf/issues/631).

### PR DESCRIPTION
**Pull request by Valinor**
see the issue for details on the typos fixed

fixes issue #3796 

Closes #3796 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Would be better to download these in the URL field itself. The ps1 script should also be added

**Comment by rashil2000** [comment]
We should copy the .cmd and .ps1 scripts (as you had done earlier), so that they are directly accessible and don't get overwritten

**Comment by Valinor** [comment]
> We should copy the .cmd and .ps1 scripts (as you had done earlier), so that they are directly accessible and don't get overwritten

instead of use post_install, I use the **bin** part to create shims from cmd and ps1, isn't that a better solution?

**Comment by rashil2000** [comment]
No, because:
- `lfcd.cmd` will create `lfcd.cmd` and `lfcd` (sh script)
- `lfcd.ps1` will create `lfcd.cmd` (which will overwrite the one created above), `lfcd` (sh script) ((which will again overwrite the one created above) and `lfcd.ps1`

So you see there'll be no use of creating shell-specific shims this way. That's why we need to copy them instead.

**Comment by tech189** [comment]
@rashil2000 I restored the shim copy to `pre_install` and moved the removal to `post_uninstall`. It's in `post_uninstall` so that if you uninstall while `lf.exe` is still running and try again after closing it, Scoop won't complain that the shims don't exist because they've already been deleted. Could you take a look?

**Comment by rashil2000** [comment]
Perfect!

**Pull request merged**
