### PR TITLE
win-acme: update to version 2.1.20.1185 & fix autoupdate field

### PR DESCRIPTION
**Pull request by delassiops**
Update manifest version and fix auto-update field ( revert to matchHead version variable)

Closes #XXXX

Relates to #XXXX

### CODE REVIEW

**Comment by rashil2000** [comment]
@delassiops can you fix this? https://github.com/ScoopInstaller/Main/runs/4346458400?check_suite_focus=true

**Comment by delassiops** [comment]
verified: checkver.ps1 -App win-acme is ok

**Comment by rashil2000** [comment]
I was talking about autoupdate - it is failing.

**Comment by delassiops** [comment]
sorry i will do, i only try checkver.ps1

**Comment by delassiops** [comment]
Hi, 

when looking file: [https://github.com/win-acme/win-acme.github.io/blob/master/_config.yml](url) 

the version variable  **releasename**: 2.1.20.1 and **releasebuild**: 2.1.20.1185  are defined manually and used in the download url,

this make impossible to automate script, or add the possibility to retrieve multiple version from checkver.ps1

thanks

**Comment by rashil2000** [comment]
Can you open an issue in their repo and ask the author how the build number is obtained?

**Comment by delassiops** [comment]
> Can you open an issue in their repo and ask the author how the build number is obtained?

after checking repo, almost it's manually,

also the problem is in the download url: the download folder & file name doesn't match

https://github.com/win-acme/win-acme/releases/download/v**2.1.20.1**/win-acme.v**2.1.20.1185**.x64.trimmed.zip 

it's can't replaced by only one variable, maybe two will solve the problem

thanks,

**Comment by delassiops** [comment]
i have opened an issue to fix from origine  : https://github.com/win-acme/win-acme/issues/2003

**Comment by rashil2000** [comment]
Great, thanks!

**Comment by WouterTinus** [comment]
The part of the download url that you're trying to guess is based on the tag given to the commit that is released, which is set manually. The full version build number and file names on the other hand are generated by build automation. I will try to remember to be more consistent now that I know that some people depend on it, but I cannot guarantee that I won't forget or someone else might publish a release in the future that doesn't know about this. 

> or add the possibility to retrieve multiple version from checkver.ps1
> it's can't replaced by only one variable, maybe two will solve the problem

This seems to be the only real solution. If you can get the tag and the build number from Github, you can reliably produce the download link. 

Alternatively you could maybe just get the *full* download link from either Github or even better https://www.win-acme.com/. That way even if we'd change to a whole different platform it could keep working.

**Comment by rashil2000** [comment]
We can get as many variables as we want from checkver, we just need to use a custom regex to capture those named variables.

**Comment by delassiops** [comment]
Hi, this code make possible to retrieve tag and build number from www.win-acme.com that it published under repo:

https://github.com/win-acme/win-acme.github.io

we can check file: _config.yml, and get value of releasetag: 2.1.20.1, releasebuild: 2.1.20.1185

`   "checkver": {
        "url": "https://raw.githubusercontent.com/win-acme/win-acme.github.io/master/_config.yml",
		"regex": "releasename: ([\\d.]+)",
                "regex": "releasetag: ([\\d.]+)"
    }`

thanks,

**Comment by rashil2000** [comment]
You can't have 2 fields with the same name. 

Refer to this manifest, where it captures the `date` and `sha` variables, and uses them as `matchDate` and `matchSha` - https://github.com/ScoopInstaller/Extras/blob/master/bucket/synfig-studio.json

**Comment by delassiops** [comment]
autoupdate is fixed, how to make new edit

**Comment by delassiops** [comment]
i found an issue on file generated by "Writing updated win-acme manifest"

**Pull request merged**
