### PR TITLE
dxc: Add version 1.7.2212.1

### LINKED ISSUE #4601: [Request]: dxc - DirectXShaderCompiler
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

dxc

### Description

HLSL shader compiler from Microsoft, widely used for DirectX and other Graphics APIs.

### Homepage

https://github.com/microsoft/DirectXShaderCompiler

### Download Link(s)

https://github.com/microsoft/DirectXShaderCompiler/releases

### Some Indication of Popularity/Repute

Open sourced on github with 2.5k star 👉 [microsoft/DirectXShaderCompiler](https://github.com/microsoft/DirectXShaderCompiler)

### PR DESCRIPTION
**Pull request by Locietta**
Closes #4601.

Upstreamed from my personal bucket: https://github.com/Locietta/sniffer/blob/master/bucket/dxc.json

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Please don't use `master` branch to create PR. Change your branch and create new one.

**Comment by Locietta** [comment]
Reopened at #4606.

**Pull request closed without merging**
