### PR TITLE
rizin: Add version 0.3.4 (cutter will be moved to extras)

### PR DESCRIPTION
**Pull request by segevfiner**
Closes N/A (I can open one if you want me to).

P.S. Cutter is a GUI tool (For the underlying rizin CLI tool). Are you sure it should be in `main` and not in `extras`?

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
If the CLI is available standalone, we can add that to Main. Otherwise, yes, it should be moved to Extras.

**Comment by segevfiner** [comment]
> If the CLI is available standalone, we can add that to Main. Otherwise, yes, it should be moved to Extras.

It is. https://github.com/rizinorg/rizin/releases/tag/v0.3.4

**Comment by rashil2000** [comment]
Can you add it to Main here?

**Comment by rashil2000** [comment]
Move cutter.json from here to Extras (make a PR there).

Also, difference between the rizin installer and zip download?

**Comment by segevfiner** [comment]
They only have a 64-bit zip for some reason 🤷‍♂️ Which is why I opted to extract the installer.

**Comment by rashil2000** [comment]
Ah okay, no worries.

**Comment by rashil2000** [comment]
Put 64bit URLs before 32bit URLs

**Pull request merged**
