### PR TITLE
helix: Scooping config file path

### LINKED ISSUE #4948: [Bug]: Helix should store its config in the persist directory
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

helix

### Expected/Current Behaviour

I think that Helix should store its config file in the persist directory and the shim should start helix using that config.  Currently, Helix looks for its config outside the Scoop directory.

### Steps to Reproduce

```console
scoop install main/helix
```

### Possible Solution

The shim for Helix can be configured with a "--config" parameter.  Helix appears to work without error even if the config file doesn't exist (for the case when a user doesn't have a Helix config in the persist dir).  In addition, the file passed to the config parameter will be opened/created when running the Helix command "config-open".

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
4b705adba (HEAD -> master, origin/master, origin/HEAD) youtubedownloader: Update to version 1.10

'nerd-fonts' bucket:
a000339 (HEAD -> master, origin/master, origin/HEAD) SarasaGothic-ttc@0.41.3: Fix hash (Closes #248)
```

### Scoop Config

```console
last_update
-----------
7/14/2023 9:42:36 PM
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by michael-taylor**
I added the "--config" parameter to the Helix shims to point to a config file that can be stored in the persis directory.

Closes #4948

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by HUMORCE — APPROVED** [review]

**Comment by HUMORCE** [comment]
I added a migration script and hints about this changes to manifest.

**Comment by rashil2000** [comment]
I don't think this should be done - this PR essentially disables the `--config` parameter for the hx.exe binary - in case a user wants to supply another config file from the commandline.

**Comment by HUMORCE** [comment]
> I don't think this should be done - this PR essentially disables the --config parameter for the hx.exe binary - in case a user wants to supply another config file from the commandline.

`helix --config A --config B`, B overrides A

**Comment by rashil2000** [comment]
Oh, I didn't know that was possible, thanks!

**Pull request merged**
