### PR TITLE
gtypist: Add version 2.9.5

### PR DESCRIPTION
**Pull request by zStruCat**
gnu typist, also known as gtypist, is a typing tutor helps improving type skill.
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zStruCat** [comment]
\verify

**Comment by rashil2000** [comment]
Excellent manifest! Just some minor comments. Use this:

```json
{
    "version": "2.9.5",
    "description": "A universal typing tutor allowing one to practise regularly.",
    "homepage": "https://www.gnu.org/software/gtypist/",
    "license": "GPL-3.0-or-later",
    "url": "http://ftp.gnu.org/gnu/gtypist/w32_binaries/gtypist-2.9.5-w32.7z",
    "hash": "8f3a021833acc81ba9291062c91c956f88ebb4d9225b9a955cb8b60cd6cdb0d3",
    "extract_dir": "gtypist-2.9.5-w32",
    "bin": [
        [
            "gtypist.exe",
            "gtypist",
            "$dir/lessons/gtypist.typ"
        ]
    ]
}
```

Not that I removed checkver and autoupdate, since the last release was in 2014, it is unlikely to get updated.

**Pull request merged**
