### PR TITLE
tickrs: Add version 0.14.8

### PR DESCRIPTION
**Pull request by jrhawley**
[tickrs](https://github.com/tarkah/tickrs) is a TUI to interact with realtime ticker data.

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
This is a 64bit application, so please use the `architecture` block for url and autoupdate

**Comment by rashil2000** [comment]
Please create the PR from a new branch (different from `master`); this one has a lot of extraneous commits

**Comment by rashil2000** [comment]
Closing this because of above...

**Comment by jrhawley** [comment]
Oops, I thought that if it just had 1 architecture, either `32bit` or `64bit` that I didn't need to use the `architecture` block. I can fix that. I saw the [autoupdate examples](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#adding-autoupdate-to-a-manifest) for packages with both `32bit` and `64bit`, but I missed the mysql example with only `64bit`.

I'll try again from a new branch.

**Pull request closed without merging**
