### PR TITLE
typstyle: Add version 0.11.34

### PR DESCRIPTION
**Pull request by chillcicada**
This pr add support for [typstyle](https://github.com/Enter-tainer/typstyle), a beautiful and reliable typst code formatter.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chillcicada** [comment]
cc @Enter-tainer, you might be interested in this.

**Comment by Enter-tainer** [comment]
looks cool! thank you for adding this!

is there any action i need to take? it looks like this pr is opened 1mo ago and doesnt get merged yet.

**Comment by chillcicada** [comment]
That's all for now, and @niheaven would you want to take some time and do a review?

**Comment by aliesbelik** [comment]
> Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks).

Submitted tool doesn't fit the [Main criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).
Guess you could try with `Extras` bucket instead.

**Comment by chillcicada** [comment]
Thanks for your advice, i will open a pr for scoop extras.

**Comment by Enter-tainer** [comment]
hi @chillcicada , I have good news for you. typstyle just reached 500 stars recently. I guess it is eligible for main bucket now?

**Comment by Enter-tainer** [comment]
related: https://github.com/ScoopInstaller/Main/pull/6746

**Pull request closed without merging**
