### PR TITLE
opa: Add version 0.32.0

### PR DESCRIPTION
**Pull request by stevehipwell**

### CODE REVIEW

**Comment by stevehipwell** [comment]
Could someone review this please?

**Comment by stevehipwell** [comment]
@r15ch13 could you take a look at this?

**Comment by stevehipwell** [comment]
@rasa could you take a look at this? I assume I can't review my own PRs?

**Comment by stevehipwell** [comment]
@dwettstein could you take a look at this?

**Review by dwettstein — APPROVED** [review]
LGTM

Eventually you could even simplify the `checkver` part a bit, similar to `bat.json`:
https://github.com/ScoopInstaller/Main/blob/441cd180de60d8ce77afe478a2420db99e78e744/bucket/bat.json#L17

**Comment by stevehipwell** [comment]
@dwettstein thanks for the review. The simplified `"checkver": "github"` only works when the homepage is a GitHub repo.

**Comment by dwettstein** [comment]
@stevehipwell, good to know, thanks. (y)

**Pull request merged**
