### PR TITLE
avr-gcc: Update to 11.1.0

### PR DESCRIPTION
**Pull request by thushan**
Fixes broken avr-gcc package and updates it to use the official [Zak Kemble](https://blog.zakkemble.net/avr-gcc-builds/)'s repository which is updated regularly.

Fixes issues:
* https://github.com/lukesampson/scoop/issues/4371 (main scoop repo)
* https://github.com/tinygo-org/tinygo/issues/1323#issuecomment-850894969 (Tinygo)

```
$ scoop install avr-gcc.json
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'avr-gcc' (11.1.0) [64bit]
Loading avr-gcc-11.1.0-x64-windows.zip from cache.
Checking hash of avr-gcc-11.1.0-x64-windows.zip ... ok.
Extracting avr-gcc-11.1.0-x64-windows.zip ... done.
Linking ~\scoop\apps\avr-gcc\current => ~\scoop\apps\avr-gcc\11.1.0
Creating shim for 'avr-addr2line'.
Creating shim for 'avr-ar'.
Creating shim for 'avr-as'.
Creating shim for 'avr-c++'.
Creating shim for 'avr-c++filt'.
Creating shim for 'avr-cpp'.
Creating shim for 'avr-elfedit'.
Creating shim for 'avr-g++'.
Creating shim for 'avr-gcc-11.1.0'.
Creating shim for 'avr-gcc-ar'.
Creating shim for 'avr-gcc-nm'.
Creating shim for 'avr-gcc-ranlib'.
Creating shim for 'avr-gcc'.
Creating shim for 'avr-gcov-dump'.
Creating shim for 'avr-gcov-tool'.
Creating shim for 'avr-gcov'.
Creating shim for 'avr-gdb'.
Creating shim for 'avr-gprof'.
Creating shim for 'avr-ld.bfd'.
Creating shim for 'avr-ld'.
Creating shim for 'avr-lto-dump'.
Creating shim for 'avr-nm'.
Creating shim for 'avr-objcopy'.
Creating shim for 'avr-objdump'.
Creating shim for 'avr-ranlib'.
Creating shim for 'avr-readelf'.
Creating shim for 'avr-run'.
Creating shim for 'avr-size'.
Creating shim for 'avr-strings'.
Creating shim for 'avr-strip'.
'avr-gcc' (11.1.0) was installed successfully!
```
And subsequently:

```
$ avr-gcc --version
avr-gcc.exe (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Please refrain from changing the repository from this to others as Zak does update this library frequently!

### CODE REVIEW

**Comment by dwettstein** [comment]
This was actually suggested by @LumitoLuma with #2156.

**Review by dwettstein — COMMENTED** [review]
Principally LGTM. Are there any drawbacks for the users when merging this, as the software is built differently?

**Comment by dwettstein** [comment]
Resolves #2275, #2418

**Comment by LumitoLuma** [comment]
Also closes #2156

**Comment by thushan** [comment]
Looks good from my end for TinyGo.

**Review by dwettstein — APPROVED** [review]
LGTM

**Pull request merged**
