### PR TITLE
dart-sass-embedded: Remove autoupdate

### PR DESCRIPTION
**Pull request by jmooring**
We no longer wish to auto-update this app.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
To disable autoupdates, removing checkver is sufficient. So we can keep the `autoupdate` field as is.

**Comment by jmooring** [comment]
@rashil2000 Thank you for the review; changed as requested.

/verify

**Pull request merged**
