### PR TITLE
bun(-baseline): Add version 1.1.0

### PR DESCRIPTION
**Pull request by sitiom**
Closes https://github.com/ScoopInstaller/Main/issues/5092

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sitiom** [comment]
CC @chawyehsu

**Review by chawyehsu — APPROVED** [review]

**Comment by sitiom** [comment]
@chawyehsu Can you explain to me what it means to "leak" DLL imports? Perhaps the [`bun.sh/install.ps1`](https://bun.sh/install.ps1) script is leaking as well?
```powershell
  $IsBaseline = $ForceBaseline
  if (!$IsBaseline) {
    $IsBaseline = !( `
      Add-Type -MemberDefinition '[DllImport("kernel32.dll")] public static extern bool IsProcessorFeaturePresent(int ProcessorFeature);' `
        -Name 'Kernel32' -Namespace 'Win32' -PassThru `
    )::IsProcessorFeaturePresent(40);
  }
```

**Comment by chawyehsu** [comment]
>  "leak" DLL imports?

That means leaking imported methods to the current PS session, literally. By _directly_ using `Add-Type` to load assemblies to current session there is no way to **unload** it unless starting a new session. In most cases, this won't cause issues as imported methods have namespaces specified, but one may not want to have imported methods persistent in current session.

Yeah it's leaking the imported method as well. You may validate `[Win32.Kernel32]::IsProcessorFeaturePresent` available after runing the install script.

**Pull request merged**
