### PR TITLE
temporal-cli: Add version 0.10.5

### LINKED ISSUE #4804: [Request]: Temporal.io CLI
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

temporal-cli

### Description

Command-line interface for running Temporal Server and interacting with Workflows, Activities, Namespaces, and other parts of Temporal

### Homepage

https://docs.temporal.io/cli

### Download Link(s)

https://github.com/temporalio/cli/releases/

### Some Indication of Popularity/Repute

[temporalio/cli]() repo has  170 stars, but this is a relatively new official CLI for the more popular temporal workflow service ([temporalio/temporal](https://github.com/temporalio/temporal)) which has 7.1k stars and is used by companies such as Datadog, Netflix, Instacart, and more.

### PR DESCRIPTION
**Pull request by tehmantra**
Closes #4804

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Hi, please add the arm64 variant too

**Comment by tehmantra** [comment]
@rashil2000 done. Apologies, I did not see `arm64` listed as a supported architecture. I have opened a separate issue to update the wiki.

**Comment by tehmantra** [comment]
Anything I can do to get this one moving?

**Comment by rashil2000** [comment]
Hey, really sorry for the delay here. The manifest looks good to go, I just have one more question. What's the difference between the binary provided at https://github.com/temporalio/temporal/releases and the one provided at https://github.com/temporalio/cli/releases?

**Comment by tehmantra** [comment]
* `temporalio/temporal` is the production server process,
* `temporalio/cli` is the cli for interacting with the server process, it also includes a lightweight dev-server.

A typical user will install temporal-cli on their workstation to do local development and testing, and to interact with local or remote temporal server(s).

There are a couple of confusing issues
1. The binary from temporalio/temporal is `temporal-server.exe`, while the binary from temporalio/cli is `temporal.exe`.
2. The installation instructions in the main temporalio/temporal README.md are actually how to install the temporalio/cli https://github.com/temporalio/temporal/blob/52d1ebecf001cdd5cdba62708a804ffbcef6125b/README.md?plain=1#L27C1-L32C113

I think it would be acceptable to name this manifest either "temporal-cli" or "temporal".

**Comment by rashil2000** [comment]
Got it. 

Just update the manifest to v0.10.5 and I'll merge it then.

**Comment by tehmantra** [comment]
Updated & tested the manifest.

```
$ scoop install .\bucket\temporal-cli.json

Installing 'temporal-cli' (0.10.5) [64bit]
temporal_cli_0.10.5_windows_amd64.zip (22.7 MB) [=================================================================================] 100%
Checking hash of temporal_cli_0.10.5_windows_amd64.zip ... ok.
Extracting temporal_cli_0.10.5_windows_amd64.zip ... done.
Linking ~\scoop\apps\temporal-cli\current => ~\scoop\apps\temporal-cli\0.10.5
Creating shim for 'temporal'.
'temporal-cli' (0.10.5) was installed successfully

$ temporal --version

temporal version 0.10.5 (server 1.21.4) (ui 2.17.0)
```

**Pull request merged**
