### PR TITLE
winpython: Switch to full distribution

### LINKED ISSUE #688: winpython@3.8.1.0: invalid download url
<details>
 <summary>The console output</summary>

```bash
Updating 'winpython' (3.7.4.1 -> 3.8.1.0)
Downloading new version
Starting download with aria2 ...
Download: 12/30 07:57:04 [ERROR] CUID#8 - Download aborted. URI=https://downloads.sourceforge.net/project/winpython/WinPython_3.8/3.8.1.0/WinPython64-3.8.1.0Zero.exe#/dl.7z
Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://downloads.sourceforge.net/project/winpython/WinPython_3.8/3.8.1.0/WinPython64-3.8.1.0Zero.exe
Download:   -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 368396|ERR |       0B/s|C:/Users/ch199/scoop/cache/winpython#3.8.1.0#https_downloads.sourceforge.net_project_winpython_WinPython_3.8_3.8.1.0_WinPython64-3.8.1.0Zero.exe_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://downloads.sourceforge.net/project/winpython/WinPython_3.8/3.8.1.0/WinPython64-3.8.1.0Zero.exe#/dl.7z
    dir=C:\Users\ch199\scoop\cache
    out=winpython#3.8.1.0#https_downloads.sourceforge.net_project_winpython_WinPython_3.8_3.8.1.0_WinPython64-3.8.1.0Zero.exe_dl.7z

ERROR & 'C:\Users\ch199\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\ch199\scoop\cache\winpython.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=25060 --continue --all-proxy='127.0.0.1:1081'

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=winpython%403.8.1.0%3a+download+via+aria2+failed
ch199@tkit-pc ~/scoop/apps/cmder-full/current
```

</details>

The correct url should be

https://sourceforge.net/projects/winpython/files/WinPython_3.8/3.8.1.0/Winpython64-3.8.1.0dot.exe

and

https://sourceforge.net/projects/winpython/files/WinPython_3.8/3.8.1.0/Winpython32-3.8.1.0dot.exe

### LINKED ISSUE #717: winpython@3.8.1.0: download via aria2 failed
C:\Users\winda>scoop install winpython
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'winpython' (3.8.1.0) [64bit]
Starting download with aria2 ...
Download: 01/07 23:10:09 [ERROR] CUID#8 - Download aborted. URI=https://downloads.sourceforge.net/project/winpython/WinPython_3.8/3.8.1.0/WinPython64-3.8.1.0Zero.exe#/dl.7z
Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://downloads.sourceforge.net/project/winpython/WinPython_3.8/3.8.1.0/WinPython64-3.8.1.0Zero.exe
Download:   -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c1ab92|ERR |       0B/s|C:/Users/winda/scoop/cache/winpython#3.8.1.0#https_downloads.sourceforge.net_project_winpython_WinPython_3.8_3.8.1.0_WinPython64-3.8.1.0Zero.exe_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://downloads.sourceforge.net/project/winpython/WinPython_3.8/3.8.1.0/WinPython64-3.8.1.0Zero.exe#/dl.7z
    dir=C:\Users\winda\scoop\cache
    out=winpython#3.8.1.0#https_downloads.sourceforge.net_project_winpython_WinPython_3.8_3.8.1.0_WinPython64-3.8.1.0Zero.exe_dl.7z

ERROR & 'C:\Users\winda\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\winda\scoop\cache\winpython.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=12396 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=winpython%403.8.1.0%3a+download+via+aria2+failed

### PR DESCRIPTION
**Pull request by rasa**
- Closes #717
- Closes #688 

See #520

### CODE REVIEW

**Comment by niheaven** [comment]
Zero version ('dot' for 3.8) is better.

**Comment by rasa** [comment]
Per https://github.com/winpython/winpython/releases, perhaps `winpython` is the full 414MB+ version, and we add a new `winpython-dot` that is the 21MB+ version:
```
    "checkver": {
        "github": "https://github.com/winpython/winpython/",
        "regex": "-([\\d.]+)dot\\.exe",
        "reverse": true
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://downloads.sourceforge.net/project/winpython/WinPython_$majorVersion.$minorVersion/$version/WinPython64-${version}dot.exe#/dl.7z",
                "extract_dir": "WPy64-$cleanVersion\\python-$majorVersion.$minorVersion.$patchVersion.amd64"
            },
            "32bit": {
                "url": "https://downloads.sourceforge.net/project/winpython/WinPython_$majorVersion.$minorVersion/$version/WinPython32-${version}dot.exe#/dl.7z",
                "extract_dir": "WPy32-$cleanVersion\\python-$majorVersion.$minorVersion.$patchVersion"
            }
        },
```

**Comment by niheaven** [comment]
We have `python`, why use WinPython as just another python dist?

I don't like `extract_dir` here, porting and using all WinPython's tools are much better.

**Comment by rasa** [comment]
Please vote on if we should:
1. Fix this package
2. Remove this package
3. Fix it, but move it to versions, as it essentially duplicates an existing package.

**Comment by niheaven** [comment]
Fix it, but as a full python dist, i.e., using full release, porting all exes, etc.

**Comment by h404bi** [comment]
vote for full dist only.

**Comment by niheaven** [comment]
I've updated `winpython` to full dist, and added usefull bins and shortcuts. Other versions (e.g. Ps2 or cod) are submitted to `versions` bucket. (https://github.com/ScoopInstaller/Versions/pull/194)

**Comment by StormPooper** [comment]
Tried this locally and I get `(404) Not Found`, same as on master - see #688.

**Comment by niheaven** [comment]
@StormPooper Please try again.

**Comment by StormPooper** [comment]
@niheaven looks to be working, currently downloading. Thanks 👍

**Comment by StormPooper** [comment]
One thing I've noticed with this version is that my Python scripts are no longer directly accessible from the command line.

I think the environment variables are wrong, `PYTHONPATH` resolves to `%PY_HOME%\Lib;%PY_HOME%\DLLs;%PY_HOME%\Lib\lib-tk`, with `PY_HOME` being `%SCOOP%\apps\winpython\current`.

The problem is that the paths in `PYTHONPATH` actually live in `%PY_HOME%\python-3.8.1.amd64\<whatever>`, so even if I were to add `%PY_HOME\Scripts` to my path it wouldn't resolve correctly.

**Comment by niheaven** [comment]
I just port everything that WinPython dist has. You may need to run the script in WinPython Prompt, or run `winpython_prompt` from cli first...

**Comment by StormPooper** [comment]
Thanks, added `winpython_prompt.ps1` to my PowerShell startup script and it works.

**Comment by niheaven** [comment]
`scripts\env.bat` set enviroment variables (include %HOME%, which breaks git). `WinPython_PS_Prompt.ps1` does the same thing under PowerShell...

What I mean is run `winpython_prompt.ps1` before your script, this one doesn't affect any system settings, just likes original WinPython installation. I don't know why Winpython set `%HOME%` to `%WINPYDIRBASE%\settings`, any software that sets `%HOME%` is not user-friendly.

**Pull request merged**
