### PR TITLE
go-jsonnet: Add version 0.17.0

### PR DESCRIPTION
**Pull request by vivainio**
Moved from scoop-extras to main bucket as instructed in https://github.com/lukesampson/scoop-extras/pull/5957

### CODE REVIEW

**Comment by vivainio** [comment]
@Ash258 any advice what I need to do further here?

**Review by stevehipwell — APPROVED** [review]

**Comment by stevehipwell** [comment]
@vivainio could you look at the error I'm geting?

```
PS ~> scoop install go-jsonnet
Installing 'go-jsonnet' (0.17.0) [64bit]
go-jsonnet_0.17.0_Windows_x86_64.tar.gz (2.6 MB) [================================================================================] 100%
Checking hash of go-jsonnet_0.17.0_Windows_x86_64.tar.gz ... ok.
Extracting go-jsonnet_0.17.0_Windows_x86_64.tar.gz ... Exception: C:\Users\hipwells\scoop\apps\scoop\current\lib\core.ps1:510
Line |
 510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'go-jsonnet_0.17.0_Windows_x86_64'! (error 16)
```

**Comment by stevehipwell** [comment]
@vivainio you don't need the `extract_dir` values, could you open a new PR to remove these?

**Comment by vivainio** [comment]
@stevehipwell done, see https://github.com/ScoopInstaller/Main/pull/2654

**Pull request merged**
