### PR TITLE
Idris 2: Add version 0.5.1

### PR DESCRIPTION
**Pull request by ColeDeanShepherd**
Adding an auto-updating app manifest for Chez Scheme v9.5.8.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ColeDeanShepherd** [comment]
Note: This depends on my other PR #4067

**Comment by rashil2000** [comment]
Building packages is not allowed in Scoop's official buckets. Only pre-packaged applications. 

It looks like prebuilt binaries are not available for Idris 2.

Idris 1 is already present in the Main bucket though (https://github.com/ScoopInstaller/Main/blob/master/bucket/idris.json).

**Pull request closed without merging**
