### PR TITLE
far: Use portable configuration

### PR DESCRIPTION
**Pull request by Neiromaster**

### CODE REVIEW

**Comment by Ash258** [comment]
Why are `$env:APPDATA\Far Manager` and `$env:LOCALAPPDATA\Far Manager` needed?

**Comment by Neiromaster** [comment]
By default the app data is located there
%APPDATA%\Far Manager - for general configuration
%LOCALAPPDATA%\Far Manager - for history and cache

**Comment by Neiromaster** [comment]
Is the configuration file created during the first installation without post_install?

**Comment by Ash258** [comment]
What?

The configuration file is copied from example

**Comment by Neiromaster** [comment]
At what point pre_install hook will be called?
"$dir\\Far. exe.example.ini\ " will already be available?

**Comment by Ash258** [comment]
After extraction...

A

**Comment by Neiromaster** [comment]
Thanks. I only recently started dealing with Scoop

**Comment by rashil2000** [comment]
It will fail every time. Let's just merge it.

**Pull request merged**
