### PR TITLE
vulkan@1.3.231.1: Add registry notes and cleanup (Fix #4218)

### LINKED ISSUE #4218: [Bug]: vulkan package doesn't write necessary registry keys
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

vulkan

### Expected/Current Behaviour

Official Vulkan SDK installer writes windows registry to register VK layers provided by Khronos. Current manifest doesn't write those keys nor give any notes about it. 

Without registries written, corresponding layers can't be found by vulkan programs. (Which causes tutorials like https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers fail.)

### Steps to Reproduce

```console
scoop install vulkan
```

### Possible Solution

I've implemented a solution at my personal bucket 👉 [manifest](https://github.com/Locietta/sniffer/blob/master/bucket/vulkansdk.json)

Post-install & pre-uninstall scripts are used to write registries. For non-global installation, registries are written to HKCU (modification of which doesn't require elevated rights). For global installation with elevated rights, registries are written to HKLM. And all added entries will be deleted with pre-uninstall scripts.

I can open a PR if people here feel the solution is ok.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
cec6e4513 (HEAD -> master, origin/master, origin/HEAD) xdelta3-cross-gui: Update to version 1.3.1

'java' bucket:
93dd38f8 (HEAD -> master, origin/master, origin/HEAD) graalvm-nightly: Update to version 23.0.0-dev-20221212_0450

'main' bucket:
4519a8e41 (HEAD -> master, origin/master, origin/HEAD) ImageMagick: Update to version 7.1.0-54 (#4216)

'sniffer' bucket:
a8459b6 (HEAD -> master, origin/master, origin/HEAD) xanmod-WSL2: Update to version 6.0.12-1.1
```

### Scoop Config

```console
PS> scoop config

proxy                 : 127.0.0.1:7890
last_update           : 2022/12/12 19:11:19
gh_token              : <Removed>
aria2-enabled         : False
aria2-warning-enabled : False
root_path             : D:\Scoop
global_path           : D:\Scoop\global
scoop_branch          : master
scoop_repo            : git@github.com:ScoopInstaller/Scoop.git
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by Locietta**
Closes #4218

Implementation follows the advice and discussion in corresponding issue.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Hi, please check the CI error: https://github.com/ScoopInstaller/Main/actions/runs/3705661906/jobs/6283564718#step:4:22

**Comment by Locietta** [comment]
Hi, CI fails because I use @XXX@ pattern as placeholders in .ps1, which is considered as syntax error.
I've fixed that now and am waiting for approval to re-trigger the CI workflow.

**Pull request merged**
