### PR TITLE
cppcryptfsctl: Add version 1.4.4.1

### PR DESCRIPTION
**Pull request by bharatvaj**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Adding this to Main since it is recommended by gocryptfs

### CODE REVIEW

**Comment by HUMORCE** [comment]
We should download both `cppcryptfs` and `cppcryptfsctl`.

**Comment by rashil2000** [comment]
> We should download both `cppcryptfs` and `cppcryptfsctl`.

Yes, I think so too

**Comment by bharatvaj** [comment]
> > We should download both `cppcryptfs` and `cppcryptfsctl`.
> 
> Yes, I think so too. And you can rename `cppcryptfsctl32.exe` in the URL field itself, using `#/cppcryptfsctl.exe`

Hey thanks, will make the changes

**Comment by bharatvaj** [comment]
Apologies, should've done this sooner. I did the mentioned changes, hope everything is alright.

**Comment by rashil2000** [comment]
- You forgot to modify the autoupdate field.
- The bins are common for both 32 and 64bit, so it can be moved out of the architecture field.

**Pull request merged**
