### PR TITLE
linkerd: Add version 22.1.3

### PR DESCRIPTION
**Pull request by ksaffarian**
- Add linkerd version 22.1.3

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
- Don't add app name in description
- Use `#/` to change downloaded bin's name, so you could remove the two `Rename-Item` lines
- Use `https://linkerd.io` as homepage
- And, is there some file that could be persisted?

**Comment by rashil2000** [comment]
The stable version of this application already exists - https://github.com/ScoopInstaller/Extras/blob/master/bucket/linkerd.json

The `edge` builds are weekly - so rename the manifest to linkerd-edge.json and create the PR in Versions bucket.

**Pull request closed without merging**
