### PR TITLE
chart-releaser: Add version 1.5.0

### PR DESCRIPTION
**Pull request by stevehipwell**
This PR adds the Helm [chart-releaser](https://github.com/helm/chart-releaser) CLI.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rashil2000 — CHANGES_REQUESTED** [review]
- Arm64 variant
- `chart-releaser.json` -> `helm-chart-releaser.json`

**Comment by stevehipwell** [comment]
@rashil2000 I've added `arm64` configuration and renamed the manifest to `helm-chart-releaser`.

**Pull request merged**
