### PR TITLE
selene: Add version 0.19.1

### PR DESCRIPTION
**Pull request by sitiom**
A blazing-fast modern Lua linter written in Rust

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
This package too does not meet the criteria, yet

**Comment by sitiom** [comment]
So in the extras bucket, I guess?

**Comment by sitiom** [comment]
https://github.com/ScoopInstaller/Extras/pull/8807

**Pull request closed without merging**
