### PR TITLE
fix(script): use scoop prefix to correctly find scoop's path

### PR DESCRIPTION
**Pull request by niheaven**

### CODE REVIEW

**Comment by Valinor** [comment]
image

Ok, it's better to use true PowerShell command, but performance is bad. 15% minimum worst.

**Comment by niheaven** [comment]
Ten milliseconds lost is acceptable, right?

**Comment by pratikpc** [comment]
@Valinor to me it looks like that's down to scoop-prefix being slow

I took a look at the code.

It loads all 4 first, when it doesn't always need all 4 of them and doesn't outright use manifest and buckets

```
. "$psscriptroot\..\lib\core.ps1"
. "$psscriptroot\..\lib\help.ps1"
. "$psscriptroot\..\lib\manifest.ps1"
. "$psscriptroot\..\lib\buckets.ps1"
```

After a few changes in the scoop-prefix.ps1, I was able to get

(Measure-Command {..\bin\scoop.ps1 prefix scoop}).TotalMilliseconds
61.1987
(Measure-Command {resolve-path (split-path (split-path (..\bin\scoop.ps1 which scoop)))}).TotalMilliseconds
72.7342

Will create a PR later.

**Comment by niheaven** [comment]
@pratikpc Just commit your fix to this one

**Comment by pratikpc** [comment]
@niheaven @Valinor created a PR

https://github.com/ScoopInstaller/Scoop/pull/4493

**Review by Valinor — APPROVED** [review]

**Pull request merged**
