### PR TITLE
clink: Persist profile

### LINKED ISSUE #1715: clink's  profile persist doesn't work now
the following refs maybe helpful:
https://chrisant996.github.io/clink/clink.html#lua-scripts-location
https://chrisant996.github.io/clink/clink.html#filelocations

### PR DESCRIPTION
**Pull request by Heniker**
Fix profile persist for clink. PR also adds profile migration.

Closes #1715

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
People usually version control shell configurations. This will be a breaking change for them as it changes the default location for config files. For Clink, IMO it would be better to not use persist_dir at all.

**Comment by rashil2000** [comment]
Closing this for the reason above

**Comment by Heniker** [comment]
AFAIK this change is no different than deprecating `-portable` configurations. Only this one actually has data migration.
Anyway, if this PR is closed - it's better to remove `persist` option from clink config and close related issue as well.

**Comment by rashil2000** [comment]
I have updated it: https://github.com/ScoopInstaller/Main/commit/a8f0b56d0bfc1db9ae2adef98395b70cae48ded7

**Pull request closed without merging**
