### PR TITLE
gdisk: Add version 1.0.9

### PR DESCRIPTION
**Pull request by brian6932**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Hi @brian6932, have you tested both the 32bit and 64bit installations?

**Comment by brian6932** [comment]
How would you test a 32bit `pre_install` on a 64bit computer? I'm sure it works, but interested to know if that's actually possible with Scoop.

**Comment by brian6932** [comment]
Anyway, I manually set it to 32bit, and it works fine

**Comment by rashil2000** [comment]
> How would you test a 32bit `pre_install` on a 64bit computer? 

`scoop install gdisk -a 32bit`

**Pull request merged**
