### PR TITLE
tfsec: Add version 1.28.0

### PR DESCRIPTION
**Pull request by Dany-coder778**
Added tfsec.json in the bucket

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Did you change the line endings or something? The whole file seems to be edited.

**Comment by Dany-coder778** [comment]
I've added one binary in "bin" key.
Maybe by mistake I also changed the hash link, but anyway it works the same.

**Comment by Dany-coder778** [comment]
> I've added one binary in "bin" key.
Because now it is unpacking an archive that includes an executable that was previously excluded

**Pull request merged**
