### PR TITLE
vhs: Add version 0.1.1

### PR DESCRIPTION
**Pull request by Zliced13**
Also added ttyd, as vhs depends on it to function properly.

Closes ScoopInstaller/Extras#9604

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@niheaven

**Review by niheaven — APPROVED** [review]

**Comment by rashil2000** [comment]
Hey @Zliced13!

Could you update the Readmes of `vhs` and `ttyd`, mentioning the Scoop installation method? Thanks :)

**Pull request merged**
