### PR TITLE
hgrep: Add version 0.2.1

### PR DESCRIPTION
**Pull request by gaeulbyul**
> Grep with human-friendly search results
> https://github.com/rhysd/hgrep

### CODE REVIEW

**Comment by rashil2000** [comment]
Your PRs will be closed as you have not followed the instructions in the template.

**Comment by rashil2000** [comment]
Create a Package Request issue for each of the PRs, and then you can reopen them.

**Comment by gaeulbyul** [comment]
I'm going to create an issue but,

- [x] a non-GUI tool
- [ ] *a reasonably well-known and widely used developer tool* <- since the hgrep is a fairly new app, I'm not sure it could be considered as "well-known" or "widely used". Is it acceptable?
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

**Comment by rashil2000** [comment]
> since the hgrep is a fairly new app, I'm not sure it could be considered as "well-known" or "widely used". Is it acceptable?

The project was started a month ago. I'm afraid for safety reasons we can't allow it as of now.

**Pull request closed without merging**
