### PR TITLE
espanso: Update to version 2.1.8

### PR DESCRIPTION
**Pull request by heinzhi**
Update of application to v2.1.8, see https://github.com/espanso/espanso/releases

Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by heinzhi** [comment]
Line updatet.
Please verify again.

**Comment by aliesbelik** [comment]
> Line updatet. Please verify again.

```
Searching hash for Espanso-Win-Installer-x86_64.exe in https://github.com/espanso/espanso/releases/download/v2.1.8/Espanso-Win-Installer-x86_64.exe.sha256.txt
Could not find hash in https://github.com/espanso/espanso/releases/download/v2.1.8/Espanso-Win-Installer-x86_64.exe.sha256.txt
Downloading Espanso-Win-Installer-x86_64.exe to compute hashes!
```

I wonder the issue with autoupdate hash extraction caused not by url value provided (both variants above seem to be correct) but by whitespace(s)/line endings presence in checksum file (like ScoopInstaller/Scoop#4180, ScoopInstaller/Scoop#4688, although should be fixed in ScoopInstaller/Scoop#4619).

**Comment by rashil2000** [comment]
Hmm. @niheaven, any ideas?

**Comment by niheaven** [comment]
CleanShot 2023-01-06 at 23 52 01@2x

Please see the file... It's encoded as Unicode Little-Endian, and the `FF FE` could not be extracted by `\s`.

And I've tried some regex but could not found useful one.

**Comment by rashil2000** [comment]
Hmm. @heinzhi please remove the autoupdate hash extraction, for now.

**Comment by heinzhi** [comment]
> extracted

removed the hash extraction. pls verify again.

**Pull request merged**
