### PR TITLE
npcap: Add version 1.79

### LINKED ISSUE #6050: [Request]: npcap
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

npcap

### Description

Nmap Project's Windows packet capture and transmission library

### Homepage

https://npcap.com/

### Download Link(s)

https://npcap.com/dist/npcap-1.79.exe#/npcap_setup.exe

### Some Indication of Popularity/Repute

almost 3k stars on Github

### PR DESCRIPTION
**Pull request by bt4ibwem8**
Closes #6050

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by leumasme** [comment]
> - [x] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

I really do not think that this fits the main bucket criteria at all. This is a non-portable driver with a non-silent admin installer

> 'THIS APPLICATION INSTALLER HAS NO SILENT INSTALLATION SWITCH, A INSTALLATION PROMPT WILL APPEAR IN A FEW MOMENTS.'

Silent installation [is available](https://npcap.com/guide/npcap-users-guide.html), but `only for Npcap OEM`

**Comment by bt4ibwem8** [comment]
@leumasme
oh, sorry, you are right... So it could be moved to Extras bucket?

**Comment by leumasme** [comment]
See:
https://github.com/ScoopInstaller/Nonportable/issues/15
https://github.com/ScoopInstaller/Extras/issues/8012

**Comment by bt4ibwem8** [comment]
@issaclin32 wrote "Unfortunately npcap only allows silent install for the OEM version". But nonportable bucket should be for not silent apps, correct?

**Comment by bt4ibwem8** [comment]
closed because it probably belongs to nonportable bucket

**Pull request closed without merging**
