### PR TITLE
Update 1password-cli to version 2.0.0

### PR DESCRIPTION
**Pull request by astelmachonak-nydig**
This PR updates 1password-cli to v2.0.0. Note: v2 is a major release and changes command line API completely: https://developer.1password.com/docs/cli/upgrade/#step-2-update-your-scripts

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by astelmachonak-nydig** [comment]
We might want to wait with merging this - the CLI commands is very different and pushing this is simple update will break lots of people.

**Comment by astelmachonak-nydig** [comment]
Also, since download URLs changed, I can't install older version after this one is installed using `scoop install 1password-cli@1.12.4` as well. Not sure what is the best way to handle this...

**Comment by rashil2000** [comment]
The best way in this case would be to use the old manifest manually

**Pull request merged**
