### PR TITLE
megacmd: fix checkver

### PR DESCRIPTION
**Pull request by pratikpc**
No releases anymore.

Only tags

#2843

### CODE REVIEW

**Review by rashil2000 — APPROVED** [review]

**Review by Valinor — APPROVED** [review]
This licence seem more correct, is it possible to change it? 

https://github.com/meganz/MEGAcmd/blob/master/LICENSE

**Comment by pratikpc** [comment]
@Valinor should I fix it here or create a new PR for new users to contribute to?

**Comment by Valinor** [comment]
> @Valinor should I fix it here or create a new PR for new users to contribute to?

New PR 👍

**Pull request merged**
