### PR TITLE
ncspot: Add version 0.8.2

### PR DESCRIPTION
**Pull request by rashil2000**
Cross platform CLI Spotify player

Like https://github.com/ScoopInstaller/Main/blob/master/bucket/mpxplay.json but for Spotify :)

### CODE REVIEW

**Comment by rashil2000** [comment]
@dwettstein requesting review :)

I raised a bunch of other PRs recently. Since I can't assign reviewers, is it okay if I mention you?

**Comment by rashil2000** [comment]
@issaclin32 requesting review :)

**Comment by dwettstein** [comment]
> I raised a bunch of other PRs recently. Since I can't assign reviewers, is it okay if I mention you?

That's OK. However, I will just response on a best effort level. 😇

**Review by dwettstein — APPROVED** [review]
LGTM

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
