### PR TITLE
fix cuda installation

### PR DESCRIPTION
**Pull request by specter119**
organize the file locations by recent cuda official installation.
fix https://github.com/ScoopInstaller/Main/issues/1638

### CODE REVIEW

**Comment by specter119** [comment]
@r15ch13 would you mind review this PR?

**Review by jat001 — APPROVED** [review]

**Comment by jat001** [comment]
Well, the reviewer needs write access. I do not have it.

**Comment by specter119** [comment]
@jat001 thanks, I will wait others to review.

**Comment by specter119** [comment]
@r15ch13 would you please review this pr?

**Pull request closed without merging**
