### PR TITLE
powersession-rs: Add version 0.1.6

### PR DESCRIPTION
**Pull request by ibigbug**
Add PowerSession Rust version

Relates to https://github.com/Watfaq/PowerSession/pull/48

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by sitiom — CHANGES_REQUESTED** [review]
Manifests should be in lowercase. Also, only one manifest per PR.

**Comment by ibigbug** [comment]
thanks @sitiom!

**Comment by sitiom** [comment]
You still haven't fixed the urls from the two suggestions I gave.

**Comment by sitiom** [comment]
You haven't fixed the urls yet.

**Comment by sitiom** [comment]
Fix the other url inside `architecture` as well.

**Comment by ibigbug** [comment]
yea just got it

**Comment by sitiom** [comment]
Remove the `#/PowerSession.exe` at the end of both URLs (did you see my "Redundant naming" suggestion?)

**Comment by ibigbug** [comment]
no where did you put the suggestion?

**Comment by sitiom** [comment]
I can't seem to link it but check the reviews above

**Comment by ibigbug** [comment]
interesting don't see review notes - were those "Published"?

**Comment by sitiom** [comment]
> interesting don't see review notes - were those "Published"?

You could always see the reviews in the [Files changed](https://github.com/ScoopInstaller/Main/pull/3640/files) section and on this thread. Also, mark the reviews as resolved if they have been fixed.

**Comment by ibigbug** [comment]
that's where I don't see anything :)

maybe you didn't "Submit"

image

**Review by sitiom — CHANGES_REQUESTED** [review]

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
