### PR TITLE
wapm-cli: Add version 0.5.4

### LINKED ISSUE #3785: WAPM is not installed with wasmer
https://github.com/ScoopInstaller/Main/blob/aa2eee1b1e4ca4008165ead195d29e85faf25543/bucket/wasmer.json#L16-L19

Hello, I would've liked WAPM to be installed with WASMER but I see that it is not added by default. Can you please add it to the WASMER version?

Edit: Wax can't even run because it requires WAPM, which is not installed by default.

@syrusakbary
@Ash258
@r15ch13 
@HUMORCE

### PR DESCRIPTION
**Pull request by HUMORCE**
Closes #3785

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wmstack** [comment]
Hmm, I believe that something would be still off about `wasmer`'s app manifest: last I tried the `wax` cli doesn't function unless `wapm` is installed.

So `wapm-cli` should be more than just a suggestion, it should be a requirement for the correct functioning of wasmer. I believe that, since people might want to use wasmer by itself, that wax should be installed with the `wapm-cli`, and `wasmer` should be installed alone.

**Comment by HUMORCE** [comment]
it's two things, imo.

**Comment by wmstack** [comment]
> it's two things, imo.

Not sure what you mean, do you mean that wax should be a separate manifest? Well, sure. I guess why not. Consider adding it as another suggestion to wasmer as well.

**Comment by HUMORCE** [comment]
I mean that `wapm-cli` should not be a dependency of `wasmer`. it's all.

**Comment by wmstack** [comment]
I hadn't seen that the `wax` cli had moved to the wasm manifest. All good.

**Review by rashil2000 — APPROVED** [review]

**Comment by wmstack** [comment]
What is up with the windows powershell checks? Is this special for this pull request or does this always happen?

**Comment by rashil2000** [comment]
> What is up with the windows powershell checks? Is this special for this pull request or does this always happen?
> 
> Edit: I mean why they are failing.

Upstream issue, can be ignored for now

**Pull request merged**
