### PR TITLE
Add xpdf-tools language support packages

### PR DESCRIPTION
**Pull request by HUMORCE**
Closes https://github.com/ScoopInstaller/Main/issues/1896

### CODE REVIEW

**Comment by ssfjhh** [comment]
Is it better to remind users copy the content of "add-to-xpdfrc" to xpdfrc and correct the path in it?

**Comment by HUMORCE** [comment]
POINT:
the LSPs is components, not interface translation packages.

**Comment by HUMORCE** [comment]
@ssfjhh 
when having a script for replace path with windows/scoop style.

**Pull request closed without merging**
