### PR TITLE
poetry: Add version 1.1.12

### PR DESCRIPTION
**Pull request by Shikanime**
Thanks to the initial work done by @uyha on #1726, I'm proposing the evolution of the pull request.

### CODE REVIEW

**Comment by rashil2000** [comment]
You should keep python as a dependency. Otherwise the installer will fail.

**Comment by rashil2000** [comment]
Also please stick to the order of fields in the PR template.

**Comment by Shikanime** [comment]
@rashil2000 Certain fields are not in the PR template such as "depends" and "autoupdate". I look at few manifest and copied the order.

**Review by rashil2000 — APPROVED** [review]

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
