### PR TITLE
Updated armclient to 1.8

### PR DESCRIPTION
**Pull request by abatishchev**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
URL is not accessible https://github.com/projectkudu/ARMClient/releases/download/v1.8/ARMClient.zip

**Comment by tech189** [comment]
I made an issue here: https://github.com/projectkudu/ARMClient/issues/60

**Comment by abatishchev** [comment]
I've reached out to the owner, he'll take a look.

**Comment by abatishchev** [comment]
The owner has released 1.9

**Comment by abatishchev** [comment]
Please reopen. I uploaded zip file to both 1.8 and 1.9.

**Comment by tech189** [comment]
No need - the Excavator GitHub action will run within the next hour and update to 1.9 automatically.

**Comment by abatishchev** [comment]
@tech189 perfect, thanks!

**Pull request closed without merging**
