### PR TITLE
sapling: Fix checkver

### PR DESCRIPTION
**Pull request by shiena**
~~The sapling version schema was changed by https://github.com/facebook/sapling/commit/360873f1498a5a8fe313f861f273bd2b49eb9940 from `VERSION-%Y%m%d-%H%M%S-HASH` to `VERSION-%Y%m%d-%H%M%S-rHASH`.~~
The sapling version schema was changed by https://github.com/facebook/sapling/commit/388343cc8b14039e12a952a2f56c451ccdd0181e from `MAJOR.MINOR-%Y%m%d-%H%M%S-rHASH` to `MAJOR.MINOR-%Y%m%d-%H%M%S-hHASH`.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Why not using `0.1.20221201` as version number?

**Comment by shiena** [comment]
> Why not using `0.1.20221201` as version number?

There is no particular reason because we applied the sapling version schema as is.

**Comment by rashil2000** [comment]
Merged in #4229

**Pull request closed without merging**
