### PR TITLE
postgresql@13.3: update download URL

### PR DESCRIPTION
**Pull request by igitur**
Correct details:

"url": "https://get.enterprisedb.com/postgresql/postgresql-13.3-2-windows-x64-binaries.zip",
"hash": "b9027435bbfe1a10f25dac0689c09fe541f26a381c15aec37bc4636e09e537c3"

### CODE REVIEW

**Comment by pratikpc** [comment]
Looks like checkver has an issue

Is there a way to update it?

**Comment by igitur** [comment]
@pratikpc Where do you see the checkver issue?

**Comment by pratikpc** [comment]
This is release 13.3-2 correct?

Now autoupdate is set to https://get.enterprisedb.com/postgresql/postgresql-$version-1-windows-x64-binaries.zip and the version detected is 13.3

Hence the selected URL is 13.3-1 due to the -1 present in the autoupdate URL.

If we could find a way to extract the 13.3-2 version instead of 13.3-1, we could download the correct file.

Is this possible?

**Comment by igitur** [comment]
On the [download page](https://www.enterprisedb.com/download-postgresql-binaries), they publish it only as `13.3`, with not 3rd-level number, so checkver cannot detect anything more. That's why I believe a manual update is the only way to point to the new 13.3-2 files. I'm open to being corrected, though.

**Comment by igitur** [comment]
@rasa Can you get this one through, please?

**Comment by igitur** [comment]
This is superceded by https://github.com/ScoopInstaller/Main/commit/54fe638dd6c90d75fab0f74085c0d058648c76de

**Pull request closed without merging**
