### PR TITLE
Manifests update 11 01 21

### PR DESCRIPTION
**Pull request by Valinor**
**Update manifest for** 
* clink.json
* concourse-fly.json
* gawk.json
* just.json
* jx.json
* k3d.json
* lessmsi.json
* macchina.json
* mdcat.json
* neovim-nightly.json
* oh-my-posh3.json
* pandoc.json
* rink.json
* rust-analyzer.json
* s3deploy.json
* tflint.json
* vim-nightly.json
* wasmtime.json
* xmake.json
* yq.json

Tested (install / uninstall )

**Not updated :** 
* terraform-provider-ibm.json

Dependancy to version bucket. Not tested

### CODE REVIEW

**Comment by rashil2000** [comment]
Would we have to this manually now?

**Comment by Valinor** [comment]
> Would we have to this manually now?

I don't know, I have a automate process which work each day to check some stuffs (not update, this is a side effect). And because I see some latency with some packages, I propose this temporary push.

Exemple : https://github.com/JanDeDobbeleer/oh-my-posh/releases : 
- scoop version is 5.16.2
- current version is v5.16.4 (2 day ago)

But maybe it's not usefull, and we can discard this push. I will be happy with that

**Review by pratikpc — APPROVED** [review]

**Comment by pratikpc** [comment]
Approved from my end

Does neovim-nightly even need a autoupdate block given the URL does not change anyways?

**Comment by rashil2000** [comment]
> Approved from my end
> 
> Does neovim-nightly even need a autoupdate block given the URL does not change anyways?

You're right, it doesn't need it

**Comment by pratikpc** [comment]
@Valinor gawk is the same TLS issue as well

```
INFO: Starting bucket/gawk.json checks

Manifest: /github/workspace/bucket/gawk.json

INFO: Hashes

The SSL connection could not be established, see inner exception.
At /SCOOP/apps/scoop/current/lib/install.ps1:130 char:9
+         throw $e
```

**Comment by rashil2000** [comment]
I think the Sourceforge website uses a version of TLS that's not compatible with Scoop (in Actions)

**Comment by stevehipwell** [comment]
Was this process always manual? If not there might be some thoughts required around this as the expected Scoop behaviour has changed. At a minimum I think something is required to split failing packages into a separate PR so the good updates can be merged ASAP.

**Review by rasa — APPROVED** [review]

**Comment by rasa** [comment]
> > Does neovim-nightly even need a autoupdate block given the URL does not change anyways?
> 
> You're right, it doesn't need it

@pratikpc @stevehipwell So the hash will get updated even though there is no `autoupdate` section?

**Comment by stevehipwell** [comment]
> @pratikpc @stevehipwell So the hash will get updated even though there is no autoupdate section?

I'm not sure, it may well do if there isn't a URL to template.

**Comment by rashil2000** [comment]
@rasa It looks like Excavator hasn't run on the repo for two days, we might have a problem here.

**Comment by r15ch13** [comment]
@rashil2000 Excavator is still running, but it constantly runs into Github's API call limiter.

**Comment by rashil2000** [comment]
So can we use @Scoopbot account to split the load? What alternative do you suggest?

**Comment by rashil2000** [comment]
Or maybe we can use a scheduled GitHub Action (like https://github.com/rasa/scoop-directory does) to check for updates every 3 hours or so, and commit them?

**Comment by r15ch13** [comment]
> So can we use @Scoopbot account to split the load? What alternative do you suggest?

Nope, it's an IP limitation. The amount of checked manifests has to be split up. But that doesn't work with the current codebase.

**Comment by rashil2000** [comment]
Yes, that why I was suggesting GitHub Actions. If there's a limit of say 100 (I'm not aware of the actual limit), then we can schedule the Actions to run 8 times per day (we have around 800 manifests total). Is such a thing possible?

**Comment by rasa** [comment]
I added an Excavator workflow in #2871

**Pull request merged**
