### PR TITLE
postgresql@16.0: fix checkver (#5224)

### LINKED ISSUE #5222: [Request]: PostgreSQL 16 is out
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

postgresql

### Description

The World's Most Advanced Open Source Relational Database

### Homepage

https://www.postgresql.org/

### Download Link(s)

https://get.enterprisedb.com/postgresql/postgresql-16.0-1-windows-x64-binaries.zip#/dl.zip_

### Some Indication of Popularity/Repute

PostgreSQL is a powerful, open source object-relational database system with over 35 years of active development that has earned it a strong reputation for reliability, feature robustness, and performance.

### LINKED ISSUE #5224: [Bug]: postgresql didn't get updated to the latest version 16.0
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

postgresql

### Expected/Current Behaviour

PostgreSQL 16 is released already but scoop fetch v15.4 instead 
https://www.postgresql.org/about/news/postgresql-16-released-2715/

### Steps to Reproduce

```console
PS D:\dev\> scoop install postgresql
Installing 'postgresql' (15.4) [64bit] from main bucket
postgresql-15.4-1-windows-x64-binaries.zip (317.4 MB) [======================================================================================================] 100%    
Checking hash of postgresql-15.4-1-windows-x64-binaries.zip ... ok.
Running pre_install script...
Linking ~\System32\scoop\apps\postgresql\current => ~\System32\scoop\apps\postgresql\15.4
Creating shortcut for pgAdmin 4 (pgAdmin4.exe)
Persisting data
Running post_install script...
'postgresql' (15.4) was installed successfully!
Notes
-----
Run run 'pg_ctl start' or 'pg_ctl stop' to start and stop the database or
register it as a service by running 'pg_ctl register -N PostgreSQL' from an elevated shell.
Default superuser login: postgres, password: <blank>
```

### Possible Solution

Check the latest version with "https://www.postgresql.org/ftp/source/" for the following reasons:

1. https://www.postgresql.org/download/ mentions this as the main file browser for source

> The source code can be found in the main [file browser](https://www.postgresql.org/ftp/source/) or you can access the source control repository directly at [git.postgresql.org](https://git.postgresql.org/gitweb/?p=postgresql.git;a=summary). Instructions for building from source can be found in the [documentation](https://www.postgresql.org/docs/current/installation.html).

2. https://www.enterprisedb.com/download-postgresql-binaries page layout is prone to change as we can see in the [previous commit](https://github.com/ScoopInstaller/Main/commit/500e8b10b9079ac67e404f5e770a2045f09bd66a)

3. The version number length is not fixed, so one may have to write extra pattern-match condition

### Scoop and Buckets Version

```console
PS D:\dev> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
8062e9a32 (HEAD -> master, origin/master, origin/HEAD) okular: Update to version 23.08.2-1562

'java' bucket:
68f3bbd3 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.392-8.0.202310271855

'main' bucket:
4f64599e3 (HEAD -> master, origin/master, origin/HEAD) pulumi: Update to version 3.91.1

'versions' bucket:
87fef4356 (HEAD -> master, origin/master, origin/HEAD) rstudio-daily: Update to version 2023.12.0-daily-232
```

### Scoop Config

```console
PS D:\dev> scoop config

aria2-warning-enabled : False
last_update           : 10/28/2023 2:11:46 PM
debug                 : True
root_path             : C:\Users\kiwap\System32\scoop
scoop_repo            : https://github.com/ScoopInstaller/Scoop
scoop_branch          : master
```

### PowerShell Version

```console
PS D:\dev> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by Elkiwa**
Closes #5224, closes #5222

### CODE REVIEW

**Comment by rashil2000** [comment]
The current checkver.url is also showing v16 as latest, any idea why that isn't working?

image

**Comment by Elkiwa** [comment]
> The current checkver.url is also showing v16 as latest, any idea why that isn't working?
> 
> image

The original pattern-matching is not strict, so it can accept both "16" and "16.0"  as the version string.

Before: If the version stays "16", then the zip name will be `postgresql-16-1-windows-x64-binaries.zip`, which doesn't work.

image

After: If the version becomes "16.0", then the zip name will be `postgresql-16.0-1-windows-x64-binaries.zip`, and we don't need to add an extra ".0".
image

**Comment by rashil2000** [comment]
Oh, got it, thanks!

**Pull request merged**
