### PR TITLE
enomic: Fix checkver URL

### PR DESCRIPTION
**Pull request by rasa**
Per https://github.com/ScoopInstaller/Main/runs/5537110586?check_suite_focus=true#step:3:257

Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
I just noticed this file is called `enomic.json` with an 'm', should be an 'n'.

**Comment by tech189** [comment]
Is checkver failing because there is an update available?

**Comment by rasa** [comment]
/verify

I have no idea why the checkver is failing. It works fine when I run checkver.ps1 locally.

**Comment by rasa** [comment]
> Is checkver failing because there is an update available?
> 
> https://github.com/ScoopInstaller/Main/runs/5543184605?check_suite_focus=true#step:3:248

@tech189 It appears you were right. Thanks for the help.

**Pull request merged**
