### PR TITLE
cmctl: Add version 2.1.0

### LINKED ISSUE #5942: [Request]: Add cmctl (CLI for cert-manager)
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

`cmctl`

### Description

`cmctl` is the CLI for `cert-manager`, a popular tool to automatically provision and manage TLS certificates in Kubernetes.

### Homepage

https://cert-manager.io/docs/reference/cmctl/

### Download Link(s)

https://github.com/cert-manager/cmctl/releases/download/v2.1.0/cmctl_windows_amd64.exe https://github.com/cert-manager/cmctl/releases/download/v2.1.0/cmctl_windows_arm64.exe

### Some Indication of Popularity/Repute

`cmctl` very recently moved to [its own repository](https://github.com/cert-manager/cmctl) to facilitate independent updates.  Previously it lived in [the main cert-manager repository](https://github.com/cert-manager/cert-manager).  Shown below are the stars and forks for both.

|          | Old Repo | New Repo |  Total |
|----------|---------:|---------:|-------:|
| ⭐ Stars |   11,664 |       24 | 11,688 |
| 🍴 Forks |    2,024 |        7 |  2,029 |

(as of 2024-06-23)

### PR DESCRIPTION
**Pull request by sharpjs**
Adds new package `cmctl` to resolve #5942.

### Prerequisites

- [x] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### Criteria

- [x] Non-GUI tool
- [x] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [x] English interface (or at least English documentation)
- [x] Latest stable version
- [x] Full version (i.e. not a trial version)
- [x] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name
`cmctl`

### Description
`cmctl` is the CLI for `cert-manager`, a popular tool to automatically provision and manage TLS certificates in Kubernetes.

This Scoop manifest also provides an example of extracting hashes from a SBOM (Software Bill of Materials) file in [SPDX JSON format](https://spdx.github.io/spdx-spec/v2.3/).  A search did not find any example of this having been done before.

### Homepage
https://cert-manager.io/docs/reference/cmctl/

### Download Link(s)
https://github.com/cert-manager/cmctl/releases/download/v2.1.0/cmctl_windows_amd64.exe
https://github.com/cert-manager/cmctl/releases/download/v2.1.0/cmctl_windows_arm64.exe

### Some Indication of Popularity/Repute
`cmctl` very recently moved to [its own repository](https://github.com/cert-manager/cmctl) to facilitate independent updates.  Previously it lived in [the main cert-manager repository](https://github.com/cert-manager/cert-manager).  Shown below are the stars and forks for both.

|          | Old Repo | New Repo |  Total |
|----------|---------:|---------:|-------:|
| ⭐ Stars |   11,664 |       24 | 11,688 |
| 🍴 Forks |    2,024 |        7 |  2,029 |

(as of 2024-06-23)

### CODE REVIEW

**Comment by sharpjs** [comment]
Anything I need to do get attention on this?  It's not urgent.  I just see it on my open-PRs list every day and wonder.  I _thought_ I have done all the things, but this being my first Scoop manifest, maybe I've missed something.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
