### PR TITLE
ipinfo-cli: Add version 2.10.1

### LINKED ISSUE #4444: [Request]: ipinfo-cli
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

ipinfo-cli

### Description

This is the official CLI for the IPinfo.io IP address API

### Homepage

https://github.com/ipinfo/cli

### Download Link(s)

https://github.com/ipinfo/cli/releases

### Some Indication of Popularity/Repute

1.3k github stars.

### PR DESCRIPTION
**Pull request by echizenryoma**
Closes #4444

Relates to #4444

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Could you make a PR to update https://github.com/ipinfo/cli/blob/master/README.md with Scoop installation instructions?

**Comment by echizenryoma** [comment]
@rashil2000 alright

**Comment by rashil2000** [comment]
Thanks!

**Comment by echizenryoma** [comment]
https://github.com/ipinfo/cli/pull/132

merged

**Pull request merged**
