### PR TITLE
ossgadget: Add version 0.1.314

### LINKED ISSUE #3248: [Request] Add OSSGadget
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** OSSGadget

**Description:** Collection of tools for analyzing open source packages.

**Homepage:** https://github.com/microsoft/OSSGadget

**Download link(s):** https://github.com/microsoft/OSSGadget/releases

**Some indication of popularity/repute:** https://github.com/microsoft/OSSGadget

### PR DESCRIPTION
**Pull request by bykenx**
OSS Gadget is a collection of tools that can help analyze open source projects.

Home page https://github.com/microsoft/OSSGadget

Closes #3248

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
- Update to 0.1.316
- Is this application 64bit or 32bit?

**Comment by bykenx** [comment]
> * Update to 0.1.316
> * Is this application 64bit or 32bit?
> * Move homepage below description

@rashil2000  This application is PE32+ executable 64bit.

And all changes have been applied.

**Pull request merged**
