### PR TITLE
eac3to@3.50: update from 3.36

### PR DESCRIPTION
**Pull request by coolpringles**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by coolpringles** [comment]
I did not mean to do that

**Review by tech189 — CHANGES_REQUESTED** [review]
Hi, thanks for this update, could you please:
- restore autoupdate (point to the same url as checkver but add on the end `https://www.rationalqm.us/eac3to/eac3to_$version.rar`
- reorder the manifest to the regular order here: https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets
- restore the same number of spaces for indentation as standard for all manifests (4) - this is set in `.editorconfig` if your editor checks that

**Review by tech189 — APPROVED** [review]

**Comment by tech189** [comment]
Thanks for your contribution!

For reference, this PR updates the download, checkver, and autoupdate to www.rationalqm.us as it says on the [old forum post](https://forum.doom9.org/showthread.php?t=125966):

> [EDIT] New versions here https://www.rationalqm.us/board/viewforum.php?f=18 [/EDIT]

**Pull request merged**
