### PR TITLE
ctop: add version 0.7.7

### PR DESCRIPTION
**Pull request by astelmachonak-nydig**
Adds [ctop](https://github.com/bcicen/ctop) command-line utility

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
We can add hash extraction via https://github.com/bcicen/ctop/releases/download/v0.7.7/sha256sums.txt

**Comment by astelmachonak-nydig** [comment]
@rashil2000 let me check that

**Comment by astelmachonak-nydig** [comment]
@rashil2000 updated, please check now

**Comment by rashil2000** [comment]
Could you make a PR to the ctop repo for adding Scoop instructions? (similar to brew)

**Comment by astelmachonak-nydig** [comment]
@rashil2000 already done: https://github.com/bcicen/ctop/pull/295

**Comment by rashil2000** [comment]
Ah, sorry I didn't check it :(

**Pull request merged**
