### PR TITLE
garnet: Add version 1.0.11

### LINKED ISSUE #5717: [Request]: garnet
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

garnet

### Description

A high-performance cache-store from Microsoft Research, which implements RESP protocol, so it is compatible with unmodified Redis clients.
It can be a good alternative to Redis for several reasons, faster performance and MIT license.
This manifest is for its standalone version of Garnet.

### Homepage

https://microsoft.github.io/garnet

### Download Link(s)

https://github.com/microsoft/garnet/releases/

### Some Indication of Popularity/Repute

As of May 3, 2024, The package project has
9276 stars and 425 forks.

### PR DESCRIPTION
**Pull request by Capella87**
Closes #5717 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Capella87** [comment]
I've added config directory as a persist, which is for persisting configuration files easily.

**Review by tech189 — COMMENTED** [review]
Can't test with the latest version 1.0.9 because of this bug https://github.com/microsoft/garnet/pull/396 but it works well with 1.0.7! Let's merge once the next version is released.

**Pull request merged**
